-- This line added by Srinivasa Rao Akula

-- *******************************************************************************
-- FileName:             B78207PO_Purchase_Orders.sql
-- To be called from wnoetxu2.sql or wnoetxu2_legacy.sql
-- Given as per SR# 00078207
-- Purpose:              To bring the vendor contact information from R12 onwards
-- Date Created:         2016/Mar/15 07:16:35
-- Created By:           nasir
--
-- *******************************************************************************
-- output to B78207PO_Purchase_Orders.lst file

@utlspon B78207PO_Purchase_Orders


SET DEFINE OFF;
WHENEVER SQLERROR EXIT 903;


INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'PO_Purchase_Orders',
      1.0,
      'PPTY',
      12.0,
      'AR',
      'HZ_PARTIES',
      null,
      '12.0+',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nasir',
      'nasir',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'PO_Purchase_Orders',
      1.0,
      'HOC',
      13.0,
      'AR',
      'HZ_ORG_CONTACTS',
      null,
      '12.0+',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nasir',
      'nasir',
      'N'
   );

update n_view_column_templates 
set product_version ='11.5-11.9',
last_updated_by='nasir',
last_update_date=sysdate
where view_label = 'PO_Purchase_Orders'
and  column_label in ('Vendor_Contact_Department', 'Vendor_Contact_First_Name', 'Vendor_Contact_Full_Name','Vendor_Contact_Last_Name','Vendor_Contact_Middle_Name')
and table_alias ='VCONT';

INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Purchase_Orders',
      1.0,
      'Vendor_Contact_Department',
      'HOC',
      'DEPARTMENT',
      10.1,
      'COL',
      'Vendor contact department.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '12.0+',
      'Y',
      'Y',
      'nasir',
      'nasir'
   );
   INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Purchase_Orders',
      1.0,
      'Vendor_Contact_First_Name',
      'PPTY',
      'PERSON_FIRST_NAME',
      10.2,
      'COL',
      'Vendor Contact First Name',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '12.0+',
      'Y',
      'Y',
      'nasir',
      'nasir'
   );
INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Purchase_Orders',
      1.0,
      'Vendor_Contact_Full_Name',
      'PPTY',
      'PPTY.PERSON_LAST_NAME||DECODE(PPTY.PERSON_FIRST_NAME||PPTY.PERSON_MIDDLE_NAME,NULL,NULL,'','')
||DECODE(PPTY.PERSON_FIRST_NAME,NULL,NULL,'' ''||PPTY.PERSON_FIRST_NAME)||DECODE(
PPTY.PERSON_MIDDLE_NAME,NULL,NULL,'' ''||PPTY.PERSON_MIDDLE_NAME)',
      10.3,
      'EXPR',
      'Vendor Contact Full Name (Last Name, First Name Middle Name)',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '12.0+',
      'Y',
      'Y',
      'nasir',
      'nasir'
   );
   INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Purchase_Orders',
      1.0,
      'Vendor_Contact_Last_Name',
      'PPTY',
      'PERSON_LAST_NAME',
      10.4,
      'COL',
      'Vendor Contact Last Name',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '12.0+',
      'Y',
      'Y',
      'nasir',
      'nasir'
   );
  INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Purchase_Orders',
      1.0,
      'Vendor_Contact_Middle_Name',
      'PPTY',
      'PERSON_MIDDLE_NAME',
      10.5,
      'COL',
      'Vendor Contact Middle Name or Middle Initial',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '12.0+',
      'Y',
      'Y',
      'nasir',
      'nasir'
   );
  INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Purchase_Orders',
      1.0,
      23.0,
      'AND VCONT.PER_PARTY_ID  = PPTY.PARTY_ID (+)',
      null,
      '12.0+',
      'Y',
      'Y',
      'nasir',
      'nasir'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Purchase_Orders',
      1.0,
      24.0,
      'AND  HOC.ORG_CONTACT_ID(+) =VCONT.ORG_CONTACT_ID',
      null,
      '12.0+',
      'Y',
      'Y',
      'nasir',
      'nasir'
   );
commit;
 
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff
