@utlspon GT_Role_And_Subject_Area_u2

Insert into N_ROLE_TEMPLATES
   (ROLE_LABEL, APPLICATION_LABEL, META_DATA_TYPE, DESCRIPTION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, ORIGINAL_VERSION, CURRENT_VERSION)
 Values
   ('FIN_GT', 'GL', 'Views', 'Finance (Global Trade)', 
    'NOETIX', TO_DATE('05/01/1998 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '090102', TO_DATE('10/01/2002 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '1.0.0', '6.3.0.1272');
COMMIT;

Insert into N_ROLE_VIEW_TEMPLATES
   (ROLE_LABEL, VIEW_LABEL, PRODUCT_VERSION, INCLUDE_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('FIN_GT', 'AR_Customer_Addresses', '*', 'Y', 
    'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'), 'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'));

Insert into N_ROLE_VIEW_TEMPLATES
   (ROLE_LABEL, VIEW_LABEL, PRODUCT_VERSION, INCLUDE_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('FIN_GT', 'RA_Customers', '*', 'Y', 
    'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'), 'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'));


Insert into N_ROLE_VIEW_TEMPLATES
   (ROLE_LABEL, VIEW_LABEL, PRODUCT_VERSION, INCLUDE_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('FIN_GT', 'PO_GT_Vendor_Sites_Vsat', '*', 'Y', 
    'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'), 'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'));

Insert into N_ROLE_VIEW_TEMPLATES
   (ROLE_LABEL, VIEW_LABEL, PRODUCT_VERSION, INCLUDE_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('FIN_GT', 'INV_Items', '*', 'Y', 
    'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'), 'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'));

Insert into N_ROLE_VIEW_TEMPLATES
   (ROLE_LABEL, VIEW_LABEL, PRODUCT_VERSION, INCLUDE_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('FIN_GT', 'INV_Manufacturer_Item_Details', '*', 'Y', 
    'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'), 'nemuser', TO_DATE('12/22/2014 05:24:05', 'MM/DD/YYYY HH24:MI:SS'));


Insert into N_PL_FOLDER_TEMPLATES
   (T_FOLDER_ID, FOLDER_NAME, FOLDER_DESCRIPTION, PARENT_T_FOLDER_ID, SORT_ORDER, SEARCH_FOLDER_NAME, INSTANCE_TYPE_CODE, FOLDER_USAGE_CODE, FOLDER_TYPE_CODE, DISPLAY_VIEWS_IN_PARENT_FLAG, PRODUCT_VERSION, INCLUDE_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (998, 'NoetixViews for Global Trade', 'NoetixViews for Global Trade', 
    1, 25, 'NoetixViews for Global Trade', 'G', 
    'ALL', 'FG', 
    'N', '*', 'Y', 'NOETIX', TO_DATE('06/18/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'NOETIX_SYS', TO_DATE('06/18/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;



Insert into N_PL_FOLDER_TEMPLATES
   (T_FOLDER_ID,   APPLICATION_LABEL, ROLE_LABEL, FOLDER_NAME, FOLDER_DESCRIPTION, PARENT_T_FOLDER_ID, 
    SORT_ORDER, SEARCH_FOLDER_NAME, INSTANCE_TYPE_CODE, KFF_ID_FLEX_CODE, KFF_ID_FLEX_APPLICATION_ID, 
    HIERARCHY_NAME, FOLDER_USAGE_CODE, FOLDER_TYPE_CODE, ORG_TYPE_CODE, DIM_TYPE_CODE, 
    DISPLAY_VIEWS_IN_PARENT_FLAG, ROLE_REQUIRED_IN_PARENT_CODE, PRODUCT_VERSION, INCLUDE_FLAG, USER_INCLUDE_FLAG, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, VERSION_ID)
 Values
   (  N_PL_FOLDER_TEMPLATES_SEQ.nextval, 'GL', 'FIN_GT', 'Global Trade Role Views Vsat', 'Global Trade role Views', 147, 1, 'Global Trade', 'G', NULL, 
    NULL, NULL, 'VIEWS', 'ROLE', NULL,     NULL, 'N', 'Y', '*', 'Y', NULL, 'Noetix', sysdate, 'Noetix', sysdate,    NULL);


Insert into N_PL_FOLDER_TEMPLATES
   (T_FOLDER_ID,   APPLICATION_LABEL, ROLE_LABEL, FOLDER_NAME, FOLDER_DESCRIPTION, PARENT_T_FOLDER_ID, 
    SORT_ORDER, SEARCH_FOLDER_NAME, INSTANCE_TYPE_CODE, KFF_ID_FLEX_CODE, KFF_ID_FLEX_APPLICATION_ID, 
    HIERARCHY_NAME, FOLDER_USAGE_CODE, FOLDER_TYPE_CODE, ORG_TYPE_CODE, DIM_TYPE_CODE, 
    DISPLAY_VIEWS_IN_PARENT_FLAG, ROLE_REQUIRED_IN_PARENT_CODE, PRODUCT_VERSION, INCLUDE_FLAG, USER_INCLUDE_FLAG, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, VERSION_ID)
 Values
   (  N_PL_FOLDER_TEMPLATES_SEQ.nextval, 'GL', 'FIN_GT', 'Global Trade Role Answers Vsat', 'Global Trade role Answers', 147, 1, 'Global Trade Answers', 'G', NULL, 
    NULL, NULL, 'ANS', 'ROLE', NULL,     NULL, 'N', 'N', '*', 'Y', NULL, 'Noetix', sysdate, 'Noetix', sysdate,    NULL);


Insert into N_PL_FOLDER_TEMPLATES
   (T_FOLDER_ID,   APPLICATION_LABEL, ROLE_LABEL, FOLDER_NAME, FOLDER_DESCRIPTION, PARENT_T_FOLDER_ID, 
    SORT_ORDER, SEARCH_FOLDER_NAME, INSTANCE_TYPE_CODE, KFF_ID_FLEX_CODE, KFF_ID_FLEX_APPLICATION_ID, 
    HIERARCHY_NAME, FOLDER_USAGE_CODE, FOLDER_TYPE_CODE, ORG_TYPE_CODE, DIM_TYPE_CODE, 
    DISPLAY_VIEWS_IN_PARENT_FLAG, ROLE_REQUIRED_IN_PARENT_CODE, PRODUCT_VERSION, INCLUDE_FLAG, USER_INCLUDE_FLAG, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, VERSION_ID)
 Values
   (  N_PL_FOLDER_TEMPLATES_SEQ.nextval, 'GL', 'FIN_GT', 'Global Trade Role Views Vsat', 'Global Trade role Views', 998, 1, 'Global Trade', 'G', NULL, 
    NULL, NULL, 'VIEWS', 'ROLE', NULL,     NULL, 'N', 'Y', '*', 'Y', NULL, 'Noetix', sysdate, 'Noetix', sysdate,    NULL);


Insert into N_PL_FOLDER_TEMPLATES
   (T_FOLDER_ID,   APPLICATION_LABEL, ROLE_LABEL, FOLDER_NAME, FOLDER_DESCRIPTION, PARENT_T_FOLDER_ID, 
    SORT_ORDER, SEARCH_FOLDER_NAME, INSTANCE_TYPE_CODE, KFF_ID_FLEX_CODE, KFF_ID_FLEX_APPLICATION_ID, 
    HIERARCHY_NAME, FOLDER_USAGE_CODE, FOLDER_TYPE_CODE, ORG_TYPE_CODE, DIM_TYPE_CODE, 
    DISPLAY_VIEWS_IN_PARENT_FLAG, ROLE_REQUIRED_IN_PARENT_CODE, PRODUCT_VERSION, INCLUDE_FLAG, USER_INCLUDE_FLAG, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, VERSION_ID)
 Values
   (  N_PL_FOLDER_TEMPLATES_SEQ.nextval, 'GL', 'FIN_GT', 'Global Trade Role Answers Vsat', 'Global Trade role Answers', 998, 1, 'Global Trade Answers', 'G', NULL, 
    NULL, NULL, 'ANS', 'ROLE', NULL,     NULL, 'N', 'N', '*', 'Y', NULL, 'Noetix', sysdate, 'Noetix', sysdate,    NULL);


commit;

@utlspoff