-- *******************************************************************************
-- FileName:             NVWB_OKE_Project_Contract_Lines.sql
--
-- Date Created:         2019/Aug/28 06:12:39
-- Created By:           nemuser
--
-- Source:
-- - Package:            Package_2018_P11_B1_DEV_NEW
-- - Environment:        EBSPJD1
-- - NoetixViews Schema: NOETIX_VIEWS
--
-- Versions:
-- - Oracle EBS:   12.1.3
-- - Oracle DB:    11.2.0
-- - NoetixViews:  6.5.1
--
-- *******************************************************************************
-- output to NVWB_OKE_Project_Contract_Lines.lst file

@utlspon NVWB_OKE_Project_Contract_Lines

-- *******************************************************************************
-- Revision Number: 1
-- *******************************************************************************

SET DEFINE OFF;
WHENEVER SQLERROR EXIT 1049;

UPDATE n_view_templates 
   SET application_label = 'OKE',
       description = 'OKE Basic - Project contract line information',
       profile_option = 'OKE_1159_ONWARDS',
       essay = 'This view is modified for applying the custom security requirements for Viasat.  This view returns line level information on the project contracts and the associated projects (if any). This information was supplied in the Contract Line tab of the Contracts Authoring Workbench window of the Project Contracts module in Oracle E-Business suite. A record is returned for each combination of a contract number, contract type and line number. Use this view for getting information about contract lines. This view can also be used to find upcoming expiry and termination of contract lines. This view returns contract details like contract number, type, status, currency, and award date. The view provides information of contract lines such as line number, status, style, start date, end date, quantity, value, and total. The view also provides details about the project, and tasks. The firm, non-firm and total amount columns are shown. The view also displays financial, billing, additional billing and other information of the contract line. Hold details like type, status, reason, apply date and schedule removal date are displayed. The Parent_Line_Number column displays the immediate parent line number of the contract line. The Not_Separately_Priced_Flag column indicates whether or not the item price is included in the rollup document. The Subcontracted_Flag column indicates whether or not the contract line is subcontracted. The Drop_Ship_Flag column indicates whether or not the item can be drop-shipped. The Billable_Flag column indicates whether or not the line can be billed or not. The Defin',
       keywords = 'K{\footnote Project Contract Lines}K{\footnote Contract Expiry Date}',
       product_version = '11.5+',
       include_flag = 'Y',
       user_include_flag = 'Y',
       export_view = 'Y',
       security_code = 'NONE',
       special_process_code = 'NONE',
       sort_layer = null,
       freeze_flag = 'N',
       last_updated_by = 'nemuser',
       last_update_date = TO_DATE('2014-11-19 04:44:57','YYYY-MM-DD HH24:MI:SS'),
       original_version = '5.7.1.383',
       current_version = '5.7.1.383'
 WHERE upper(view_label) = 'OKE_PROJECT_CONTRACT_LINES';


update n_view_templates vt 
   set vt.essay = vt.essay || 'itized_Flag column indicates whether the contract is definitized. The Not_Exceed_Warning_Reqd_Flag indicated whether or not a warning is displayed when the bill amount exceeds the contract total amount. The Hold_Flag column indicates whether the contract line is currently on hold or not. For optimal performance, filter the records by the Contract_Number, Line_Number, and Contract_Start_Date columns.' 
   where upper(vt.view_label) = 'OKE_PROJECT_CONTRACT_LINES';



INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Total_Billed_Amount',
      null,
      '(select sum(pasf.total_billed_amount) from pa.pa_summary_project_fundings pasf where pasf.project_id = plne.project_id)',
      10.200001,
      'EXPR',
      'Total billed amount. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Header_ID',
      'CHDR',
      'ID',
      10.900003,
      'COL',
      'Header identifier. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Projfunc_Baselined_Amount',
      null,
      '(select sum(pasf.projfunc_baselined_amount) from pa.pa_summary_project_fundings pasf where pasf.project_id = plne.project_id)',
      10.400002,
      'EXPR',
      'Project functional baselined amount. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Contract_Project_ID',
      'PLNE',
      'PROJECT_ID',
      10.1,
      'COL',
      'Contract project id. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Line_ID',
      'PLNE',
      'K_LINE_ID',
      11.000004,
      'COL',
      'Line identifier. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Customer_Number',
      null,
      '(select custa.account_number FROM  AR.HZ_CUST_ACCOUNTS CUSTA, AR.HZ_PARTY_SITES PSIT,           AR.HZ_CUST_ACCT_SITES_ALL CAS, AR.HZ_LOCATIONS ADDR WHERE 1=1 AND CAS.CUST_ACCT_SITE_ID = TASK.ADDRESS_ID           AND CAS.PARTY_SITE_ID = PSIT.PARTY_SITE_ID           AND PSIT.LOCATION_ID = ADDR.LOCATION_ID           AND CUSTA.CUST_ACCOUNT_ID(+) = CAS.CUST_ACCOUNT_ID)',
      10.500002,
      'EXPR',
      'Customer number. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Financial_Analyst',
      null,
      ' (SELECT peo.full_name              FROM hr.per_All_people_f peo,                   pa.pa_project_classes pc,                   pa.pa_class_Codes pcod             WHERE     pc.class_category = ''Product Line''                   AND pc.class_code = pcod.class_code                   AND pc.class_category = pcod.class_Category                   AND pc.project_id = plne.project_id                   AND peo.person_id = pcod.attribute5                   AND SYSDATE BETWEEN peo.effective_start_date(+)                                   AND NVL (                                          peo.effective_end_date(+),                                          TO_DATE (''31-DEC-4712'',                                                   ''DD-MON-YYYY'')))',
      10.800003,
      'EXPR',
      'Financial analyst. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Contract_Line_Project_Number',
      null,
      '(SELECT SEGMENT1 FROM PA.PA_PROJECTS_ALL WHERE PROJECT_ID = PLNE.PROJECT_ID)',
      10.600002,
      'EXPR',
      'Project number of the contrat line. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Business_Area',
      null,
      '(SELECT pcod.attribute2              FROM pa.pa_project_classes pc, pa.pa_class_Codes pcod             WHERE     pc.class_category = ''Product Line''                   AND pc.class_code = pcod.class_code                   AND pc.class_category = pcod.class_Category                   AND pc.project_id = plne.project_id)',
      10.700003,
      'EXPR',
      'Business area. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      'Total_Baselined_Amount',
      null,
      '(select sum(pasf.total_baselined_amount) from pa.pa_summary_project_fundings pasf where pasf.project_id = plne.project_id)',
      10.300001,
      'EXPR',
      'Total baselined amount. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OKE_Project_Contract_Lines',
      1.0,
      31.0,
      'AND (PROJ.PROJECT_ID IN (SELECT PROJECT_ID FROM PAG0_USER_PROJECTS_VSAT_BASE WHERE USER_ID = APPS.XXNAO_FND_WRAPPER_PKG.USER_ID))',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );





COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff