-- *******************************************************************************
-- FileName:             NVWB_GL_Balances.sql
--
-- Date Created:         2019/Aug/28 06:12:39
-- Created By:           nemuser
--
-- Source:
-- - Package:            Package_2018_P11_B1_DEV_NEW
-- - Environment:        EBSPJD1
-- - NoetixViews Schema: NOETIX_VIEWS
--
-- Versions:
-- - Oracle EBS:   12.1.3
-- - Oracle DB:    11.2.0
-- - NoetixViews:  6.5.1
--
-- *******************************************************************************
-- output to NVWB_GL_Balances.lst file

@utlspon NVWB_GL_Balances

-- *******************************************************************************
-- Revision Number: 8
-- *******************************************************************************

SET DEFINE OFF;
WHENEVER SQLERROR EXIT 946;

INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'GL_Balances',
      1.0,
      'Project_Type',
      null,
      ' (SELECT ppa.project_type              FROM pa.pa_project_classes ppc, pa.pa_projects_all ppa             WHERE     ppa.project_id = ppc.project_id                   AND acct.segment5 = ppa.segment1                   AND ppc.class_category = ''Product Line'')',
      10.500002,
      'EXPR',
      'Project type. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'GL_Balances',
      1.0,
      'Ledger_ID',
      'GLBAL',
      'LEDGER_ID',
      10.800003,
      'COL',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'GL_Balances',
      1.0,
      'Class_Category',
      null,
      ' (SELECT ppc.class_code              FROM pa.pa_project_classes ppc, pa.pa_projects_all ppa             WHERE     ppa.project_id = ppc.project_id                   AND acct.segment5 = ppa.segment1                   AND ppc.class_category = ''Classification'')',
      10.200001,
      'EXPR',
      'Class category. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'GL_Balances',
      1.0,
      'Division',
      null,
      '(SELECT ppc.class_code              FROM pa.pa_project_classes ppc, pa.pa_projects_all ppa             WHERE     ppa.project_id = ppc.project_id                   AND acct.segment5 = ppa.segment1                   AND ppc.class_category = ''Product Line'')',
      10.300001,
      'EXPR',
      'Division. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'GL_Balances',
      1.0,
      'Ship_To_Address',
      null,
      '(SELECT    p.party_name                   || ''|''                   || sa1.city                   ||  ''|''                   || sa1.state                   ||  ''|''                   || sa1.country              FROM N_PA_LOOKUPS_VL CRV1,                   ar.hz_cust_accounts CV1,                   ar.hz_parties p,                   pa.PA_PROJECT_CUSTOMERS PC1,                   pa.PA_PROJECTS_ALL PPA,                   pa.PA_TASKS PT,                   ar.HZ_LOCATIONS SA1             WHERE     PC1.PROJECT_RELATIONSHIP_CODE = CRV1.LOOKUP_CODE                   AND LOOKUP_TYPE = ''CUSTOMER PROJECT RELATIONSHIP''                   AND P.PARTY_ID = CV1.PARTY_ID                   AND PC1.PROJECT_ID = PPA.PROJECT_ID                   AND PC1.RECEIVER_TASK_ID = PT.TASK_ID(+)                   AND PC1.CUSTOMER_ID = CV1.CUST_ACCOUNT_ID                   AND PC1.SHIP_TO_ADDRESS_ID = SA1.Location_id(+)                   AND acct.segment5 = PPA.segment1                   AND ROWNUM = 1)',
      10.700003,
      'EXPR',
      'Ship to address. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'GL_Balances',
      1.0,
      'Product_Line',
      null,
      '(SELECT pcod.description              FROM pa.pa_project_classes ppc,                   pa.pa_projects_all ppa,                   pa.pa_class_codes pcod             WHERE     ppa.project_id = ppc.project_id                   AND acct.segment5 = ppa.segment1                   AND pcod.class_code = PPC.CLASS_CODE                   AND pcod.class_category = PPC.CLASS_CATEGORY                   AND ppc.class_category = ''Product Line'')',
      10.400002,
      'EXPR',
      'Product line. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'GL_Balances',
      1.0,
      'Business_Area',
      null,
      '(SELECT CASE                      WHEN (   ppc.class_code BETWEEN 0 AND 5                            OR ppc.class_code BETWEEN 8 AND 9                            OR ppc.class_code BETWEEN 1010 AND 1140)                      THEN                         ''CORP''                      WHEN ppc.class_code BETWEEN 6 AND 7                      THEN                         ''TWT''                      WHEN ppc.class_code BETWEEN 10 AND 99                      THEN                         ''GSD''                      WHEN ppc.class_code BETWEEN 200 AND 299                      THEN                         ''BB''                      WHEN ppc.class_code BETWEEN 400 AND 499                      THEN                         ''VSN''                      WHEN ppc.class_code BETWEEN 600 AND 699                      THEN                         ''SGS''                      WHEN ppc.class_code BETWEEN 800 AND 899                      THEN                         ''CL''                      WHEN ppc.class_code BETWEEN 700 AND 749                      THEN                         ''ECC''                      WHEN ppc.class_code BETWEEN 751 AND 755                      THEN                         ''ETI''                      WHEN ppc.class_code BETWEEN 775 AND 775                      THEN                         ''ICT''                      WHEN ppc.class_code BETWEEN 2000 AND 2999                      THEN                         ''USM''                      ELSE                         ppc.class_code                   END              FROM pa.pa_project_classes ppc, pa.pa_projects_all ppa             WHERE     ppa.project_id = ppc.project_id                   AND acct.segment5 = ppa.segment1                   AND ppc.class_category = ''Product Line'')',
      10.600002,
      'EXPR',
      'Business area. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'GL_Balances',
      1.0,
      'Project_Name',
      null,
      '(SELECT ppa.name              FROM pa.pa_projects_all ppa             WHERE ppa.segment1 = acct.segment5)',
      10.1,
      'EXPR',
      'Project name. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );






COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff