-- *******************************************************************************
-- FileName:             NVWB_PO_Release_Distributions.sql
--
-- Date Created:         2019/Aug/28 06:12:39
-- Created By:           nemuser
--
-- Source:
-- - Package:            Package_2018_P11_B1_DEV_NEW
-- - Environment:        EBSPJD1
-- - NoetixViews Schema: NOETIX_VIEWS
--
-- Versions:
-- - Oracle EBS:   12.1.3
-- - Oracle DB:    11.2.0
-- - NoetixViews:  6.5.1
--
-- *******************************************************************************
-- output to NVWB_PO_Release_Distributions.lst file

@utlspon NVWB_PO_Release_Distributions

-- *******************************************************************************
-- Revision Number: 45
-- *******************************************************************************

SET DEFINE OFF;
WHENEVER SQLERROR EXIT 1002;

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'STLOC',
      16.0,
      'HR',
      'HR_LOCATIONS_ALL_TL',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'MPARM',
      15.0,
      'INV',
      'MTL_PARAMETERS',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'AcctVar',
      'DIST',
      'VARIANCE_ACCOUNT_ID',
      10.700003,
      'KEY',
      'Variance account. Custom Field added by Zensar.',
      'GL',
      'GL_CODE_COMBINATIONS',
      null,
      'CODE_COMBINATION_ID',
      null,
      null,
      '101',
      'GL#',
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      8,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctVar'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      null,
      null,
      null,
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      13,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctVar'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      null,
      null,
      null,
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      15,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctVar'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      'FA_COST_CTR',
      'Y',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      15,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctVar'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      'GL_ACCOUNT',
      'Y',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      15,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctVar'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      'GL_BALANCING',
      'Y',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );



INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Line_Cancel_Reason',
      'LINES',
      'CANCEL_REASON',
      13.200012,
      'COL',
      'Line cancel reason. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Line_Received_Quantity',
      'SHIP',
      'QUANTITY_RECEIVED',
      11.800007,
      'COL',
      'Line received quantity. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'N',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Cancel_Flag',
      null,
      'NVl(SHIP.cancel_Flag, ''N'')',
      13.500013,
      'EXPR',
      'Shipment cancel flag. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Order_Cancel_Flag',
      null,
      'NVL(PO.cancel_flag,''N'')',
      12.800011,
      'EXPR',
      'Order cancel flag. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Quantity_Billed',
      null,
      'NVL(SHIP.quantity_billed,0)',
      12.300009,
      'EXPR',
      'Shipment quantity billed. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Line_Cancel_Flag',
      null,
      'NVl(LINES.cancel_Flag, ''N'')',
      13.000011,
      'EXPR',
      'Line cancel flag. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Small_Business_Flag',
      null,
      ' NVl(Vendor_Name.small_business_flag, ''N'')',
      13.300013,
      'EXPR',
      'Small business flag. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Award_Class_PO',
      'DIST',
      'ATTRIBUTE2',
      11.200005,
      'COL',
      'Purchase order award class. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Cancel_Date',
      'SHIP',
      'CANCEL_DATE',
      13.600014,
      'COL',
      'Shipment cancel date. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'AcctAcrl',
      'DIST',
      'ACCRUAL_ACCOUNT_ID',
      10.500002,
      'KEY',
      'Accrual Account. Custom field added by Zensar.',
      'GL',
      'GL_CODE_COMBINATIONS',
      null,
      'CODE_COMBINATION_ID',
      null,
      null,
      '101',
      'GL#',
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      8,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctAcrl'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      null,
      null,
      null,
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      13,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctAcrl'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      null,
      null,
      null,
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      15,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctAcrl'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      'FA_COST_CTR',
      'Y',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      15,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctAcrl'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      'GL_ACCOUNT',
      'Y',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      15,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctAcrl'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      'GL_BALANCING',
      'Y',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );



INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Order_Closure_Status',
      'PO',
      'CLOSED_CODE',
      12.70001,
      'COL',
      'Order closure status. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Delivered_Quantity',
      'DIST',
      'QUANTITY_DELIVERED',
      10.1,
      'COL',
      'Delivered quantity. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Planner',
      null,
      'NOETIX_VIEWS.NOETIX_VSAT_UTILITY_PKG.GETPLANNER ( SHIP.SHIP_TO_ORGANIZATION_ID, LINES.ITEM_ID)',
      11.7000065,
      'EXPR',
      'Planner. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Release_ID',
      'REL',
      'PO_RELEASE_ID',
      10.900003,
      'COL',
      'PO release identifier.. Custom Field added  by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Quantity_Cancelled',
      null,
      'NVL(SHIP.quantity_cancelled,0)',
      14.100016,
      'EXPR',
      'Shipment quantity cancelled. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Quantity',
      null,
      'NVL(SHIP.QUANTITY,0)',
      12.100008,
      'EXPR',
      'Shipment quantity. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Ship_To_Location_Code',
      'STLOC',
      'LOCATION_CODE',
      14.000015,
      'COL',
      'Ship to location code. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Quantity_Shipped',
      null,
      'NVL(SHIP.quantity_shipped,0)',
      12.60001,
      'EXPR',
      'Shipment quantity shipped. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Open_Value',
      null,
      'LINES.UNIT_PRICE*( DIST.quantity_ordered -  NVL (DIST.quantity_cancelled, 0) - NVL (DIST.quantity_delivered, 0))',
      10.200001,
      'EXPR',
      'Open value. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Line_ID',
      'LINES',
      'PO_LINE_ID',
      10.800003,
      'COL',
      'PO line identifier. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Vendor_Number',
      null,
      'NVL( Vendor_Name.segment1, NULL)',
      13.400013,
      'EXPR',
      'Vendor number. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Quantity_Rejected',
      null,
      'NVL(SHIP.quantity_rejected,0)',
      12.50001,
      'EXPR',
      'Shipment quantity rejected. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Ship_To_Organization_Code',
      'MPARM',
      'ORGANIZATION_CODE',
      13.900015,
      'COL',
      'Ship to organization code. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Receipt_Required_Flag',
      null,
      'NVl(SHIP.receipt_required_flag, ''N'')',
      11.900007,
      'EXPR',
      'Receipt required flag. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Line_Quantity',
      'LINES',
      'QUANTITY',
      11.600006,
      'COL',
      'Line quantity. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Quantity_Accepted',
      null,
      'NVL(SHIP.quantity_accepted,0)',
      12.200008,
      'EXPR',
      'Shipment quantity accepted. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Header_ID',
      'PO',
      'PO_HEADER_ID',
      11.100004,
      'COL',
      'Purchase order header identifier. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Unit_Price',
      'LINES',
      'UNIT_PRICE',
      13.8000145,
      'COL',
      'Line unit price. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'On_Time_Delivery_Date',
      null,
      'NVL ( DECODE ( LENGTH (SHIP.ATTRIBUTE9), 9, DECODE (INSTR (SHIP.ATTRIBUTE9, ''/''), 0, TO_DATE (SHIP.ATTRIBUTE9, ''DD-MON-YY''), TO_DATE (SHIP.ATTRIBUTE9, ''MM/DD/YYYY'')), 11, TO_DATE (SHIP.ATTRIBUTE9, ''DD-MON-YYYY''), 20, TO_DATE (SHIP.ATTRIBUTE9, ''DD-MON-YYYY HH24:MI:SS'')), SHIP.PROMISED_DATE)',
      11.300005,
      'EXPR',
      'On time delivery date. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Inspection_Required_Flag',
      null,
      'NVl(SHIP.inspection_required_flag, ''N'')',
      11.400005,
      'EXPR',
      'Inspection required flag. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Cancel_Reason',
      'SHIP',
      'CANCEL_REASON',
      13.700014,
      'COL',
      'Shipment cancel reason. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Line_Cancel_Date',
      'LINES',
      'CANCEL_DATE',
      13.100012,
      'COL',
      'Line cancel date. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Distribution_ID',
      'DIST',
      'PO_DISTRIBUTION_ID',
      10.300001,
      'COL',
      'PO distribution identifier. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Quantity_Received',
      null,
      'NVL(SHIP.quantity_received,0)',
      12.400009,
      'EXPR',
      'Shipment quantity received. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'AcctBdgt',
      'DIST',
      'BUDGET_ACCOUNT_ID',
      10.600002,
      'KEY',
      'Budget account. Custom Field added by Zensar.',
      'GL',
      'GL_CODE_COMBINATIONS',
      null,
      'CODE_COMBINATION_ID',
      null,
      null,
      '101',
      'GL#',
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      8,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctBdgt'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      null,
      null,
      null,
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      13,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctBdgt'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      null,
      null,
      null,
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      15,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctBdgt'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      'FA_COST_CTR',
      'Y',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      15,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctBdgt'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      'GL_ACCOUNT',
      'Y',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      15,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'PO_Release_Distributions'   AND t.query_position     = 1.0   AND t.column_label       = 'AcctBdgt'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      'GL_BALANCING',
      'Y',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );



INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Last_Receipt_Date',
      null,
      '(SELECT MAX (RCVT.TRANSACTION_DATE) FROM po.RCV_TRANSACTIONS RCVT WHERE RCVT.SOURCE_DOCUMENT_CODE = ''PO'' AND RCVT.TRANSACTION_TYPE = ''RECEIVE'' AND SHIP.LINE_LOCATION_ID = RCVT.PO_LINE_LOCATION_ID)',
      11.500006,
      'EXPR',
      'Last receipt date. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Shipment_Order_Quantity',
      null,
      'NVL(SHIP.quantity-SHIP.quantity_cancelled,0)',
      12.000008,
      'EXPR',
      'Shipment ordered quantity. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Award_Class_Current_Contract',
      null,
      'APPS.XXNAO_VSAT_WRAPPER_PKG.GET_AWARD_CLASSIFICATION(dist.project_id)',
      11.000004,
      'EXPR',
      'Award classification. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'FOB_Code',
      'PO',
      'FOB_LOOKUP_CODE',
      10.400002,
      'COL',
      'FOB lookup code. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      'Release_Cancel_Flag',
      'REL',
      'CANCEL_FLAG',
      12.900011,
      'COL',
      'Release cancel flag. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'N',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      70.0,
      'and SHIP.SHIP_TO_LOCATION_ID = STLOC.LOCATION_ID (+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Release_Distributions',
      1.0,
      69.0,
      'and SHIP.SHIP_TO_ORGANIZATION_ID = MPARM.ORGANIZATION_ID(+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );





COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff