-- *******************************************************************************
-- FileName:             NVWB_INV_Time_To_Failure_Vsat.sql
--
-- Date Created:         2019/Aug/28 06:12:39
-- Created By:           nemuser
--
-- Source:
-- - Package:            Package_2018_P11_B1_DEV_NEW
-- - Environment:        EBSPJD1
-- - NoetixViews Schema: NOETIX_VIEWS
--
-- Versions:
-- - Oracle EBS:   12.1.3
-- - Oracle DB:    11.2.0
-- - NoetixViews:  6.5.1
--
-- *******************************************************************************
-- output to NVWB_INV_Time_To_Failure_Vsat.lst file

@utlspon NVWB_INV_Time_To_Failure_Vsat

-- *******************************************************************************
-- Revision Number: 13
-- *******************************************************************************

SET DEFINE OFF;
WHENEVER SQLERROR EXIT 1028;

INSERT INTO n_view_templates(
      view_label,
      application_label,
      description,
      profile_option,
      essay,
      keywords,
      product_version,
      include_flag,
      user_include_flag,
      export_view,
      security_code,
      special_process_code,
      sort_layer,
      freeze_flag,
      created_by,
      last_updated_by,
      original_version,
      current_version
  ) VALUES (
      'INV_Time_To_Failure_Vsat',
      'INV',
      null,
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'Y',
      'NONE',
      'NONE',
      '0',
      'N',
      'nemuser',
      'nemuser',
      null,
      null
  );

INSERT INTO n_view_query_templates(
      view_label,
      query_position,
      union_minus_intersection,
      group_by_flag,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      view_comment,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      null,
      'N',
      null,
      '%',
      'Y',
      'Y',
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'MUT',
      5.0,
      'INV',
      'MTL_UNIT_TRANSACTIONS',
      null,
      '%',
      'Y',
      'Y',
      'Y',
      null,
      'N',
      'nemuser',
      'nemuser',
      'Y'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'XMAP',
      9.0,
      'INV',
      'INV_INV_ACL_MAP_BASE',
      null,
      '%',
      'Y',
      'Y',
      'Y',
      null,
      'N',
      'nemuser',
      'nemuser',
      'Y'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'ITEM',
      4.0,
      'INV',
      'MTL_SYSTEM_ITEMS_B',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'TTYPE',
      1.0,
      'INV',
      'MTL_TRANSACTION_TYPES',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'PROJ',
      8.0,
      'PA',
      'PA_PROJECTS_ALL',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'LOCX',
      12.0,
      'INV',
      'MTL_ITEM_LOCATIONS',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'MUTL',
      14.0,
      'INV',
      'MTL_UNIT_TRANSACTIONS',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'LOC',
      11.0,
      'INV',
      'MTL_ITEM_LOCATIONS',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'TACT',
      2.0,
      'NOETIX',
      'N_MFG_LOOKUPS_VL',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'MATTR',
      6.0,
      'INV',
      'MTL_MATERIAL_TRANSACTIONS',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'TASK',
      7.0,
      'PA',
      'PA_TASKS',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'MPARM',
      10.0,
      'INV',
      'MTL_PARAMETERS',
      null,
      '%',
      'Y',
      'Y',
      'Y',
      null,
      'N',
      'nemuser',
      'nemuser',
      'Y'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'ITEML',
      3.0,
      'INV',
      'MTL_SYSTEM_ITEMS_TL',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'MLN',
      13.0,
      'INV',
      'MTL_TRANSACTION_LOT_NUMBERS',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Subinventory',
      'MATTR',
      'SUBINVENTORY_CODE',
      6.0,
      'COL',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Item_Description',
      'ITEML',
      'description',
      1.0,
      'COL',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Task_Number',
      'TASK',
      'task_number',
      7.0,
      'COL',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Creation_Date',
      'MATTR',
      'CREATION_DATE',
      10.0,
      'COL',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Project_Number',
      'PROJ',
      'segment1',
      5.0,
      'COL',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Shipment_Date',
      'MATTR',
      'TRANSACTION_DATE',
      11.0,
      'COL',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Transaction_Source_Type',
      null,
      'DECODE (              MATTR.TRANSACTION_SOURCE_TYPE_ID,               ''16'', ''Project Contract'',              ''2'', ''Sales order'',              MATTR.TRANSACTION_SOURCE_TYPE_ID) ',
      9.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Locator_KFF',
      null,
      '(   LOC.segment1            || ''.''            || (SELECT segment1                  FROM PA.PA_PROJECTS_ALL                 WHERE project_id = LOC.segment19)            || ''.''            || (SELECT task_number                  FROM PA.pa_tasks                 WHERE task_id = LOC.segment20))',
      10.400002,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Loc_Xfer',
      'LOCX',
      'INVENTORY_LOCATION_ID',
      10.300001,
      'SEGCAT',
      null,
      'INV',
      'MTL_ITEM_LOCATIONS',
      null,
      'INVENTORY_LOCATION_ID',
      null,
      null,
      '401',
      'MTLL',
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      8,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'INV_Time_To_Failure_Vsat'   AND t.query_position     = 1.0   AND t.column_label       = 'Loc_Xfer'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      null,
      null,
      null,
      null,
      null,
      null,
      '%',
      null,
      null,
      null,
      'nemuser',
      'nemuser'
   );



INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Item',
      'ITEM',
      'INVENTORY_ITEM_ID',
      10.1,
      'SEGCAT',
      null,
      'INV',
      'MTL_SYSTEM_ITEMS_B',
      null,
      'INVENTORY_ITEM_ID',
      null,
      null,
      '401',
      'MSTK',
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      8,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'INV_Time_To_Failure_Vsat'   AND t.query_position     = 1.0   AND t.column_label       = 'Item'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      null,
      null,
      null,
      null,
      null,
      null,
      '%',
      null,
      null,
      null,
      'nemuser',
      'nemuser'
   );



INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Serial_Number',
      null,
      'NVL (MUT.serial_number, MUTL.serial_number)',
      2.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'Y',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Transaction_Quantity',
      null,
      'CASE WHEN SIGN (MATTR.TRANSACTION_QUANTITY) = -1 THEN -1 ELSE 1 END',
      8.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Receive_Date',
      null,
      ' (SELECT MIN (RD_MATTR.transaction_date)              FROM inv.mtl_unit_transactions RD_mut,                   inv.mtl_material_transactions RD_mattr,                   INV.MTL_TRANSACTION_LOT_NUMBERS rd_MLN,                   INV.MTL_UNIT_TRANSACTIONS RD_MUTL1             WHERE     1 = 1                   AND RD_mattr.inventory_item_id = mattr.inventory_item_id                   AND RD_mattr.transaction_id = rd_mut.transaction_id(+)                   AND RD_mattr.transaction_id = RD_MLN.transaction_id(+)                   AND RD_MLN.serial_transaction_id =                          rd_mutl1.transaction_id(+)                   AND RD_MATTR.transaction_source_type_id = 12                   AND (RD_mut.serial_number =                           NVL (mut.serial_number, mutl.serial_number)                        OR RD_MUTL1.serial_number =                              NVL (mut.serial_number, mutl.serial_number))                   AND RD_mattr.transaction_date > mattr.transaction_date)',
      12.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Locator',
      'LOC',
      'INVENTORY_LOCATION_ID',
      10.200001,
      'SEGCAT',
      null,
      'INV',
      'MTL_ITEM_LOCATIONS',
      null,
      'INVENTORY_LOCATION_ID',
      null,
      null,
      '401',
      'MTLL',
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      8,
      (SELECT t.t_column_id  FROM n_view_column_templates t WHERE t.view_label         = 'INV_Time_To_Failure_Vsat'   AND t.query_position     = 1.0   AND t.column_label       = 'Locator'   AND REPLACE(NVL(TRIM(t.product_version),'*'),'%','*')     = NVL(TRIM('*'),'*')   AND NVL(t.profile_option,'###NOT_SET###')     = NVL(null,'###NOT_SET###')),
      null,
      null,
      null,
      null,
      null,
      null,
      '%',
      null,
      null,
      null,
      'nemuser',
      'nemuser'
   );



INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Organization_Code',
      'MPARM',
      'organization_code',
      3.0,
      'COL',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      'Customer_Name',
      null,
      '(NOETIX_VSAT_UTILITY_PKG.GETTXNCUSTOMERNAME (               mattr.transaction_id,                            mATTR.transaction_source_id,               NVL (mut.serial_number, mutl.serial_number),               (SELECT UPPER (A.TRANSACTION_SOURCE_TYPE_NAME)                  FROM INV.MTL_TXN_SOURCE_TYPES a                 WHERE A.TRANSACTION_SOURCE_TYPE_ID =                   MATTR.TRANSACTION_SOURCE_TYPE_ID)))',
      4.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      22.0,
      'AND MLN.SERIAL_TRANSACTION_ID = MUTL.TRANSACTION_ID(+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      3.0,
      'and ITEM.ORGANIZATION_ID = MPARM.ORGANIZATION_ID',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      6.0,
      'and MATTR.PROJECT_ID = PROJ.PROJECT_ID (+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      8.0,
      'and ITEML.INVENTORY_ITEM_ID (+) = ITEM.INVENTORY_ITEM_ID',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      11.0,
      'and MATTR.TRANSACTION_ACTION_ID = TACT.LOOKUP_CODE (+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      10.0,
      'and ITEML.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      17.0,
      'AND MATTR.LOCATOR_ID = LOC.INVENTORY_LOCATION_ID(+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      9.0,
      'and ITEML.ORGANIZATION_ID (+) = ITEM.ORGANIZATION_ID',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      1.0,
      'AND MPARM.ORGANIZATION_ID = XMAP.ORGANIZATION_ID',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      18.0,
      'AND MATTR.ORGANIZATION_ID = LOC.ORGANIZATION_ID(+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      12.0,
      'and TACT.LOOKUP_TYPE (+) = ''MTL_TRANSACTION_ACTION''',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      16.0,
      'and MATTR.TRANSACTION_SOURCE_TYPE_ID IN (2,8,16)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      7.0,
      'and MATTR.TASK_ID = TASK.TASK_ID (+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      23.0,
      'AND MATTR.TRANSACTION_TYPE_ID IN (33, 62,77)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      14.0,
      'and TACT.SECURITY_GROUP_ID (+) = NOETIX_APPS_SECURITY_PKG.LOOKUP_SECURITY_GROUP (                     TACT.LOOKUP_TYPE(+),                     TACT.VIEW_APPLICATION_ID(+))',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      19.0,
      'AND MATTR.TRANSFER_LOCATOR_ID = LOCX.INVENTORY_LOCATION_ID(+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      2.0,
      'and MATTR.TRANSACTION_ID = MUT.TRANSACTION_ID (+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      4.0,
      'and MATTR.ORGANIZATION_ID = MPARM.ORGANIZATION_ID',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      13.0,
      'and TACT.LANGUAGE (+) = NOETIX_ENV_PKG.GET_LANGUAGE',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      21.0,
      'AND MATTR.TRANSACTION_ID = MLN.TRANSACTION_ID(+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      15.0,
      'and MATTR.TRANSACTION_TYPE_ID = TTYPE.TRANSACTION_TYPE_ID (+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      5.0,
      'and MATTR.INVENTORY_ITEM_ID = ITEM.INVENTORY_ITEM_ID',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Time_To_Failure_Vsat',
      1.0,
      20.0,
      'AND MATTR.ORGANIZATION_ID = LOCX.ORGANIZATION_ID(+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );





COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;
SET DEFINE OFF;
WHENEVER SQLERROR EXIT 1028;

INSERT INTO n_role_view_templates(
      role_label,
      view_label,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'DEPOT_REPAIR',
      'INV_Time_To_Failure_Vsat',
      '%',
      null,
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_role_view_templates(
      role_label,
      view_label,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INVENTORY',
      'INV_Time_To_Failure_Vsat',
      '%',
      null,
      null,
      'nemuser',
      'nemuser'
   );


COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff