-- *******************************************************************************
-- FileName:             NVWB_PO_Sup_Bus_Class_Vsat_Base.sql
--
-- Date Created:         2019/Aug/28 06:12:40
-- Created By:           nemuser
--
-- Source:
-- - Package:            Package_2018_P11_B1_DEV_NEW
-- - Environment:        EBSPJD1
-- - NoetixViews Schema: NOETIX_VIEWS
--
-- Versions:
-- - Oracle EBS:   12.1.3
-- - Oracle DB:    11.2.0
-- - NoetixViews:  6.5.1
--
-- *******************************************************************************
-- output to NVWB_PO_Sup_Bus_Class_Vsat_Base.lst file

@utlspon NVWB_PO_Sup_Bus_Class_Vsat_Base

-- *******************************************************************************
-- Revision Number: 8
-- *******************************************************************************

SET DEFINE OFF;
WHENEVER SQLERROR EXIT 1274;

INSERT INTO n_view_templates(
      view_label,
      application_label,
      description,
      profile_option,
      essay,
      keywords,
      product_version,
      include_flag,
      user_include_flag,
      export_view,
      security_code,
      special_process_code,
      sort_layer,
      freeze_flag,
      created_by,
      last_updated_by,
      original_version,
      current_version
  ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      'PO',
      null,
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'Y',
      'NONE',
      'BASEVIEW',
      '0',
      'N',
      'nemuser',
      'nemuser',
      null,
      null
  );

INSERT INTO n_view_query_templates(
      view_label,
      query_position,
      union_minus_intersection,
      group_by_flag,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      view_comment,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      null,
      'N',
      null,
      '%',
      'Y',
      'Y',
      null,
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'VEN',
      1.0,
      'AP',
      'AP_SUPPLIERS',
      null,
      '%',
      'Y',
      'Y',
      'Y',
      null,
      'N',
      'nemuser',
      'nemuser',
      'Y'
   );

INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Cert_Isoiec17025',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.lookup_code = ''QMS_CERT_ISO/IEC17025''         and bc.vendor_id=ven.vendor_id         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      6.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Comsec_Cert',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.vendor_id=ven.vendor_id         and bc.lookup_code = ''COMSEC_CERTIFIED''         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      2.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Cert_Ts16949',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.vendor_id=ven.vendor_id         and bc.lookup_code = ''QMS_CERT_TS16949''         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      9.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Reach',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.vendor_id=ven.vendor_id         and bc.lookup_code = ''REACH''         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      10.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Cert_Other',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.vendor_id=ven.vendor_id         and bc.lookup_code = ''QMS_CERT_OTHER''         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      7.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Cert_Tl9000',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.vendor_id=ven.vendor_id         and bc.lookup_code = ''QMS_CERT_TL9000''         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      8.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Vendor_Id',
      'VEN',
      'vendor_id',
      1.0,
      'COL',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Sas3_Eicc',
      null,
      'decode((select BC.status                 from apps.POS_BUS_CLASS_ATTR BC                where bc.vendor_id = ven.vendor_id                  and bc.lookup_code = ''SAS3_EICC''                  and sysdate between bc.start_date_active and                      nvl(bc.end_date_active, sysdate)                  and bc.status = ''A''),               NULL,               ''N'',               ''Y'')',
      10.300001,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Z_CDI_Cert_Compliant',
      null,
      'decode((select BC.status                 from apps.POS_BUS_CLASS_ATTR BC                where bc.vendor_id = ven.vendor_id                  and bc.lookup_code = ''Z-CDI_CERT_COMPLIANT''                  and sysdate between bc.start_date_active and                      nvl(bc.end_date_active, sysdate)                  and bc.status = ''A''),               NULL,               ''N'',               ''Y'')',
      10.600002,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Cert_Iso9001',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.vendor_id=ven.vendor_id         and bc.lookup_code = ''QMS_CERT_ISO9001''         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      5.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Sas2_Env_Mgmt_Sys',
      null,
      'decode((select BC.status                 from apps.POS_BUS_CLASS_ATTR BC                where bc.vendor_id = ven.vendor_id                  and bc.lookup_code = ''SAS2_ENV_MGMT_SYS''                  and sysdate between bc.start_date_active and                      nvl(bc.end_date_active, sysdate)                  and bc.status = ''A''),               NULL,               ''N'',               ''Y'')',
      10.200001,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Rohs',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.vendor_id=ven.vendor_id         and bc.lookup_code = ''ROHS''         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      11.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Board_Relationship',
      null,
      'decode((select BC.status                 from apps.POS_BUS_CLASS_ATTR BC                where bc.vendor_id = ven.vendor_id                  and bc.lookup_code = ''BOARD_RELATIONSHIP''                  and sysdate between bc.start_date_active and                      nvl(bc.end_date_active, sysdate)                  and bc.status = ''A''),               NULL,               ''N'',               ''Y'')',
      10.700003,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Cert_As9100',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.vendor_id=ven.vendor_id         and bc.lookup_code = ''QMS_CERT_AS9100''         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      3.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Sas1_Env_Policy',
      null,
      'decode((select BC.status                 from apps.POS_BUS_CLASS_ATTR BC                where bc.vendor_id = ven.vendor_id                  and bc.lookup_code = ''SAS1_ENV_POLICY''                  and sysdate between bc.start_date_active and                      nvl(bc.end_date_active, sysdate)                  and bc.status = ''A''),               NULL,               ''N'',               ''Y'')',
      10.1,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Cert_Iso14001',
      null,
      'decode((select BC.status         from apps.POS_BUS_CLASS_ATTR BC         where bc.vendor_id=ven.vendor_id         and bc.lookup_code = ''QMS_CERT_ISO14001''         and sysdate between bc.start_date_active and nvl(bc.end_date_active,sysdate)         and bc.status = ''A''),NULL,''N'',''Y'')',
      4.0,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Z_CDI_Cert_Non_Compliant',
      null,
      'decode((select BC.status                 from apps.POS_BUS_CLASS_ATTR BC                where bc.vendor_id = ven.vendor_id                  and bc.lookup_code = ''Z-CDI_CERT_NONCOMPLIANT''                  and sysdate between bc.start_date_active and                      nvl(bc.end_date_active, sysdate)                  and bc.status = ''A''),               NULL,               ''N'',               ''Y'')',
      10.400002,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Sup_Bus_Class_Vsat_Base',
      1.0,
      'Z_CDI_Cert_Compliant_12312017',
      null,
      'decode((select BC.status                 from apps.POS_BUS_CLASS_ATTR BC                where bc.vendor_id = ven.vendor_id                  and bc.lookup_code = ''Z-CDI_CERT_COMPLIANT_12312017''                  and sysdate between bc.start_date_active and                      nvl(bc.end_date_active, sysdate)                  and bc.status = ''A''),               NULL,               ''N'',               ''Y'')',
      10.500002,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '%',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );






COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;
SET DEFINE OFF;
WHENEVER SQLERROR EXIT 1274;

INSERT INTO n_role_view_templates(
      role_label,
      view_label,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PURCHASING',
      'PO_Sup_Bus_Class_Vsat_Base',
      '%',
      null,
      null,
      'nemuser',
      'nemuser'
   );


COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff