-- *******************************************************************************
-- FileName:             NVWB_PO_Blanket_PO_Lines.sql
--
-- Date Created:         2019/Aug/28 06:12:39
-- Created By:           nemuser
--
-- Source:
-- - Package:            Package_2018_P11_B1_DEV_NEW
-- - Environment:        EBSPJD1
-- - NoetixViews Schema: NOETIX_VIEWS
--
-- Versions:
-- - Oracle EBS:   12.1.3
-- - Oracle DB:    11.2.0
-- - NoetixViews:  6.5.1
--
-- *******************************************************************************
-- output to NVWB_PO_Blanket_PO_Lines.lst file

@utlspon NVWB_PO_Blanket_PO_Lines

-- *******************************************************************************
-- Revision Number: 8
-- *******************************************************************************

SET DEFINE OFF;
WHENEVER SQLERROR EXIT 1084;

DELETE 
  FROM n_view_column_templates
 WHERE t_column_id = 152942;

DELETE 
  FROM n_view_column_templates
 WHERE t_column_id = 152911;

INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Blanket_PO_Lines',
      1.0,
      'Total_BPO_Amount_Released',
      null,
      'NOETIX_VSAT_UTILITY_PKG.Total_Blanket_Release_Amount(pohdr.po_header_id)',
      10.600002,
      'EXPR',
      'Total BPO amount released. Custom filed added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '10.0+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Blanket_PO_Lines',
      1.0,
      'Released_Amount_Vsat',
      null,
      'SUM (CASE WHEN NVL(pohdr.Global_agreement_flag,''N'') = ''Y'' THEN                    (select SUM((NVL(PLL.quantity,0)-NVL(PLL.quantity_cancelled,0)) * PLL.price_override)                             from po.po_line_locations_all pll,                                 po.po_lines_all pol                            where pol.po_line_id = pll.po_line_id (+)                            AND pol.from_header_id = POLIN.po_header_id                            AND pol.from_line_id = POLIN.po_line_id)                    ELSE                    (select NVL(SUM(DECODE(POL.order_type_lookup_code,                               ''RATE'',                               PLL.amount - NVL(PLL.amount_cancelled, 0),                               ''FIXED PRICE'',                               PLL.amount - NVL(PLL.amount_cancelled, 0),                               (NVL(PLL.quantity, 0) -                               NVL(PLL.quantity_cancelled, 0)) *                               NVL(PLL.price_override, 0))),                               0)                    FROM po.po_line_locations_all pll,                         po.po_headers_all        poh,                         po.po_lines_all          POL                    WHERE poh.po_header_id = POL.po_header_id                     AND POL.po_line_id = PLL.po_line_id(+)                    AND pll.shipment_type(+) NOT IN (''PRICE BREAK'')                    and pll.line_location_id = ship.line_location_id)                    END)',
      10.800003,
      'EXPR',
      'Vsat released amount. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '10.0+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Blanket_PO_Lines',
      1.0,
      'Total_BPO_Amount_Limit',
      'POHDR',
      'AMOUNT_LIMIT',
      10.700003,
      'COL',
      'Amount limit. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'Y',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '10.0+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Blanket_PO_Lines',
      1.0,
      'Release_ID',
      'REL',
      'PO_RELEASE_ID',
      10.400002,
      'COL',
      'PO release identifier. Custom Field added  by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'Y',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '10.0+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Blanket_PO_Lines',
      1.0,
      'Released_Quantity_Vsat',
      null,
      'SUM (CASE WHEN NVL(pohdr.Global_agreement_flag,''N'') = ''Y'' THEN                    (select SUM((NVL(PLL.quantity,0)-NVL(PLL.quantity_cancelled,0)))                             from po.po_line_locations_all pll,                                 po.po_lines_all pol                            where pol.po_line_id = pll.po_line_id (+)                            AND pol.from_header_id = POLIN.po_header_id                            AND pol.from_line_id = POLIN.po_line_id)                    ELSE                    (select NVL(SUM(DECODE(POL.order_type_lookup_code,                               ''RATE'',                               PLL.amount - NVL(PLL.amount_cancelled, 0),                               ''FIXED PRICE'',                               PLL.amount - NVL(PLL.amount_cancelled, 0),                               (NVL(PLL.quantity, 0) -                               NVL(PLL.quantity_cancelled, 0)))),                               0)                    FROM po.po_line_locations_all pll,                         po.po_headers_all        poh,                         po.po_lines_all          POL                    WHERE poh.po_header_id = POL.po_header_id                     AND POL.po_line_id = PLL.po_line_id(+)                    AND pll.shipment_type(+) NOT IN (''PRICE BREAK'')                    and pll.line_location_id = ship.line_location_id)                    END)',
      10.900003,
      'EXPR',
      'Vsat relased quantity. Custom filed added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '10.0+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Blanket_PO_Lines',
      1.0,
      'Header_ID',
      'POHDR',
      'PO_HEADER_ID',
      10.300001,
      'COL',
      'PO header identifier. Custom field added by zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'Y',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '10.0+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Blanket_PO_Lines',
      1.0,
      'Expiration_Date',
      'POLIN',
      'EXPIRATION_DATE',
      10.1,
      'COL',
      'Expiration date. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'Y',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '10.0+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Blanket_PO_Lines',
      1.0,
      'Line_ID',
      'POLIN',
      'PO_LINE_ID',
      10.200001,
      'COL',
      'PO line identifier. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'Y',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '10.0+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'PO_Blanket_PO_Lines',
      1.0,
      'Total_BPO_Amount_Agreed',
      null,
      'NVL(POHDR.BLANKET_TOTAL_AMOUNT, 0)',
      10.500002,
      'EXPR',
      'Total BPO Amount agreed. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'Y',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '10.0+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );






COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff