-- *******************************************************************************
-- FileName:             NVWB_OE_Holds.sql
--
-- Date Created:         2019/Dec/29 23:07:55
-- Created By:           nemuser
--
-- Source:
-- - Package:            test_column
-- - Environment:        EBSPJD1
-- - NoetixViews Schema: NOETIX_VIEWS
--
-- Versions:
-- - Oracle EBS:   12.1.3
-- - Oracle DB:    11.2.0
-- - NoetixViews:  6.5.1
--
-- *******************************************************************************
-- output to NVWB_OE_Holds.lst file

@utlspon NVWB_OE_Holds

-- *******************************************************************************
-- Revision Number: 2
-- *******************************************************************************

SET DEFINE OFF;
WHENEVER SQLERROR EXIT 903;

INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'HL_Cancelled_Flag',
      null,
      '(DECODE (DECODE (lines.line_id, NULL, ''HEADER'', '' LINE''),                 ''HEADER'', HEAD.cancelled_flag,                 LINES.cancelled_flag))',
      10.700003,
      'EXPR',
      'Cancelled Flag, If Line id is NULL Header cancelled flag will be taken. Custom Field Added By Zensar',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Open_Flag',
      null,
      '(DECODE (DECODE (lines.line_id, NULL, ''HEADER'', '' LINE''),                 ''HEADER'', HEAD.open_flag,                 LINES.open_flag))',
      10.800003,
      'EXPR',
      'Open Flag, Custom Field Added By Zensar',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Cancelled_Flag',
      'LINES',
      'CANCELLED_FLAG',
      10.1,
      'COL',
      'Cancelled flag. Custom Field Added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Total_Value',
      null,
      ' (SELECT SUM (                   NVL (TLINES.UNIT_SELLING_PRICE, 0)                   * DECODE (TLINES.LINE_CATEGORY_CODE,                             ''RETURN'', -NVL (TLINES.ORDERED_QUANTITY, 0),                             NVL (TLINES.ORDERED_QUANTITY, 0)))           FROM ONT.OE_ORDER_LINES_ALL TLINES          WHERE TLINES.HEADER_ID = HEAD.HEADER_ID)',
      10.400002,
      'EXPR',
      'Total value. Custom Field Added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Ship_Org_Code',
      null,
      '(DECODE (DECODE (lines.line_id, NULL, ''HEADER'', '' LINE''),                 ''HEADER'', (SELECT ORGANIZATION_CODE                              FROM INV.MTL_PARAMETERS                             WHERE ORGANIZATION_ID = HEAD.SHIP_FROM_ORG_ID),                 (SELECT ORGANIZATION_CODE                    FROM INV.MTL_PARAMETERS                   WHERE ORGANIZATION_ID = LINES.SHIP_FROM_ORG_ID)))',
      10.500002,
      'EXPR',
      'Shipment organization code. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Line_Category_Code',
      'LINES',
      'LINE_CATEGORY_CODE',
      10.200001,
      'COL',
      'Line category code. Custom Field Added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Program_Manager_Name',
      null,
      '(       select full_name        from HR.per_all_people_f        where person_id = head.attribute5          and nvl(head.creation_date,sysdate) between effective_start_date and nvl(effective_end_date,sysdate+1)          and rownum = 1 ) ',
      10.600002,
      'EXPR',
      'Program manager name. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Hold_Location',
      null,
      'decode (lines.line_id, null, ''HEADER'', '' LINE'')',
      10.300001,
      'EXPR',
      'Hold location. Custom Field Added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Project_Creation_Date',
      null,
      '(select ppa.Creation_Date from pa.pa_projects_all ppa where 1=1 and head.Attribute6= ppa.segment1 and rownum=1)',
      11.100004,
      'EXPR',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Open_Value',
      null,
      ' (SELECT SUM (                   NVL (TLINES.UNIT_SELLING_PRICE, 0)                   * DECODE (                        TLINES.LINE_CATEGORY_CODE,                        ''RETURN'', -NVL (                                      TLINES.ORDERED_QUANTITY                                      - NVL (TLINES.fulfilled_quantity, 0),                                      0),                        NVL (                           TLINES.ORDERED_QUANTITY                           - NVL (TLINES.fulfilled_quantity, 0),                           0)))           FROM ONT.OE_ORDER_LINES_ALL TLINES          WHERE TLINES.HEADER_ID = HEAD.HEADER_ID)',
      10.900003,
      'EXPR',
      'Open Value, Custom Field Added By Zensar',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'OE_Holds',
      2.0,
      'Ship_Organization_Code',
      null,
      '(DECODE (DECODE (lines.line_id, NULL, ''HEADER'', '' LINE''),                 ''HEADER'', (SELECT ORGANIZATION_CODE                              FROM INV.MTL_PARAMETERS                             WHERE ORGANIZATION_ID = HEAD.SHIP_FROM_ORG_ID),                 (SELECT ORGANIZATION_CODE                    FROM INV.MTL_PARAMETERS                   WHERE ORGANIZATION_ID = LINES.SHIP_FROM_ORG_ID)))',
      11.000004,
      'EXPR',
      'Ship organization code. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '11.5+',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );






COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff