-- *******************************************************************************
-- FileName:             NVWB_INV_Transactions.sql
--
-- Date Created:         2019/Oct/15 01:27:38
-- Created By:           nemuser
--
-- Source:
-- - Package:            Package_Test
-- - Environment:        EBSPJD1
-- - NoetixViews Schema: NOETIX_VIEWS
--
-- Versions:
-- - Oracle EBS:   12.1.3
-- - Oracle DB:    11.2.0
-- - NoetixViews:  6.5.1
--
-- *******************************************************************************
-- output to NVWB_INV_Transactions.lst file

@utlspon NVWB_INV_Transactions

-- *******************************************************************************
-- Revision Number: 7
-- *******************************************************************************

SET DEFINE OFF;
WHENEVER SQLERROR EXIT 956;

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Transactions',
      1.0,
      'CQL',
      8.0,
      'BOM',
      'CST_QUANTITY_LAYERS',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

INSERT INTO n_view_table_templates(
      view_label,
      query_position,
      table_alias,
      from_clause_position,
      application_label,
      table_name,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      base_table_flag,
      key_view_label,
      subquery_flag,
      created_by,
      last_updated_by,
      gen_search_by_col_flag
   ) VALUES (
      'INV_Transactions',
      1.0,
      'CCG',
      7.0,
      'BOM',
      'CST_COST_GROUPS',
      null,
      '%',
      'Y',
      'Y',
      'N',
      null,
      'N',
      'nemuser',
      'nemuser',
      'N'
   );

UPDATE n_view_column_templates
   SET view_label = 'INV_Transactions',
       query_position = 1.0,
       column_label = 'Loc_Xfer',
       table_alias = 'MATTR',
       column_expression = 'TRANSFER_LOCATOR_ID',
       column_position = 19.0,
       column_type = 'KEY',
       description = 'Transfer transaction opposing locator. Modified by Zensar.',
       ref_application_label = 'INV',
       ref_table_name = 'MTL_ITEM_LOCATIONS',
       key_view_label = null,
       ref_lookup_column_name = 'INVENTORY_LOCATION_ID',
       ref_description_column_name = null,
       ref_lookup_type = null,
       id_flex_application_id = '401',
       id_flex_code = 'MTLL',
       group_by_flag = 'N',
       format_mask = null,
       format_class = 'STRING',
       gen_search_by_col_flag = 'N',
       lov_view_label = 'INV_Lov_Location_Flexfields',
       lov_column_label = 'Locator',
       profile_option = 'INV_GLOBAL',
       product_version = '10.0+',
       include_flag = 'Y',
       user_include_flag = 'Y',
       last_updated_by = 'nemuser',
       last_update_date = TO_DATE('2016-05-21 04:30:37','YYYY-MM-DD HH24:MI:SS')
 WHERE t_column_id = 115590;


INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      13,
      115590,
      null,
      null,
      null,
      null,
      null,
      null,
      '10.0+',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );



UPDATE n_view_column_templates
   SET view_label = 'INV_Transactions',
       query_position = 1.0,
       column_label = 'Locator',
       table_alias = 'MATTR',
       column_expression = 'LOCATOR_ID',
       column_position = 5.0,
       column_type = 'KEY',
       description = 'Stock locator within a subinventory. Field modified by Zensar.',
       ref_application_label = 'INV',
       ref_table_name = 'MTL_ITEM_LOCATIONS',
       key_view_label = null,
       ref_lookup_column_name = 'INVENTORY_LOCATION_ID',
       ref_description_column_name = null,
       ref_lookup_type = null,
       id_flex_application_id = '401',
       id_flex_code = 'MTLL',
       group_by_flag = 'N',
       format_mask = null,
       format_class = 'STRING',
       gen_search_by_col_flag = 'N',
       lov_view_label = 'INV_Lov_Location_Flexfields',
       lov_column_label = 'Locator',
       profile_option = null,
       product_version = '10.0+',
       include_flag = 'Y',
       user_include_flag = 'Y',
       last_updated_by = 'nemuser',
       last_update_date = TO_DATE('2016-05-21 04:30:37','YYYY-MM-DD HH24:MI:SS')
 WHERE t_column_id = 1192;


INSERT INTO n_view_property_templates(
      view_label,
      query_position,
      property_type_id,
      t_source_pk_id,
      value1,
      value2,
      value3,
      value4,
      value5,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      version_id,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      13,
      1192,
      null,
      null,
      null,
      null,
      null,
      null,
      '10.0+',
      'Y',
      null,
      null,
      'nemuser',
      'nemuser'
   );



INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Loc_Xfer_KFF',
      null,
      '(Loc_Xfer.segment1||''.''|| (select segment1 from PA.PA_PROJECTS_ALL where project_id=Loc_Xfer.segment19) ||''.''|| (select task_number from PA.pa_tasks where task_id=Loc_Xfer.segment20))',
      10.300001,
      'EXPR',
      'Transfer locator flexfield. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'To_Task_Number',
      null,
      '(SELECT task_number              FROM pa.pa_tasks t             WHERE t.task_id = mattr.to_task_id)',
      10.800003,
      'EXPR',
      'To task number. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Receiving_Transaction_Type',
      null,
      ' (SELECT TXN.TRANSACTION_TYPE              FROM po.RCV_TRANSACTIONS txn             WHERE TXN.TRANSACTION_ID = MATTR.RCV_TRANSACTION_ID)',
      11.600006,
      'EXPR',
      'Receiving transaction type. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Transaction_Cost',
      'MATTR',
      'TRANSACTION_COST',
      10.1,
      'COL',
      'Transaction cost. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Shipment_Number',
      'MATTR',
      'SHIPMENT_NUMBER',
      10.600002,
      'COL',
      'Shipment number. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Item_Type',
      null,
      '(SELECT IT.MEANING ITEM_TYPE FROM APPLSYS.FND_LOOKUP_VALUES IT WHERE 1=1 AND ITEM.ITEM_TYPE = IT.LOOKUP_CODE AND IT.LOOKUP_TYPE (+)= ''ITEM_TYPE'')',
      11.200005,
      'EXPR',
      'Item type. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Receipt_Number',
      null,
      '(SELECT rsh.receipt_num receipt_number    FROM po.rcv_shipment_headers rsh, po.rcv_transactions port   WHERE rsh.shipment_header_id = port.shipment_header_id         AND port.transaction_id = mattr.rcv_transaction_id)',
      11.400005,
      'EXPR',
      'Receipt Number. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Transaction_Source',
      null,
      'NOETIX_VSAT_UTILITY_PKG.GetTransSourceAll (              Upper(DECODE (MATTR.TRANSACTION_SOURCE_TYPE_ID,                   ''1'', ''Purchase order'',                   ''10'', ''Physical Inventory'',                   ''103'', ''{Found *''''******''''* *''''******''''* }'',                   ''11'', ''Standard cost update'',                   ''12'', ''RMA'',                   ''120'', ''{LIFO-Transaction *''''******''''* }'',                   ''13'', ''Inventory'',                   ''14'', ''Periodic Cost Update'',                   ''140'', ''{LIFO_TEST1 *''''******''''* *''''****}'',                   ''15'', ''Layer Cost Update'',                   ''16'', ''Project Contract'',                   ''160'', ''{INCR_TEST1 *''''******''''* *''''****}'',                   ''17'', ''External Requisition'',                   ''180'', ''{Temp-Test *''''******''''* *''''*****}'',                   ''2'', ''Sales order'',                   ''201'', ''{test *''''******''''* *''''******''''* *}'',                   ''221'', ''{NL Issue to Project *''''******}'',                   ''240'', ''{Order Capture *''''******''''* *''''*}'',                   ''260'', ''PutAway'',                   ''281'', ''PICK'',                   ''3'', ''Account'',                   ''300'', ''Consignment'',                   ''320'', ''Mobile Field Service'',                   ''4'', ''Move order'',                   ''5'', ''Job or Schedule'',                   ''6'', ''Account alias'',                   ''7'', ''Internal requisition'',                   ''8'', ''Internal order'',                   ''9'', ''Cycle Count'',                   MATTR.TRANSACTION_SOURCE_TYPE_ID)),              mattr.transaction_source_id,              MPARM.ORGANIZATION_ID)',
      10.400002,
      'EXPR',
      'Transaction source. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Actual_Cost',
      'MATTR',
      'ACTUAL_COST',
      10.500002,
      'COL',
      'Actual cost. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Last_Update_Date',
      'MATTR',
      'LAST_UPDATE_DATE',
      11.300005,
      'COL',
      'Last update date. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Receiving_Transaction_Date',
      null,
      '(SELECT TXN.TRANSACTION_DATE              FROM po.RCV_TRANSACTIONS txn             WHERE TXN.TRANSACTION_ID = MATTR.RCV_TRANSACTION_ID)',
      11.500006,
      'EXPR',
      'Receiving transaction date. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Locator_KFF',
      null,
      '(Locator.segment1||''.''|| (select segment1 from PA.PA_PROJECTS_ALL where project_id=Locator.segment19) ||''.''|| (select task_number from PA.pa_tasks where task_id=Locator.segment20))',
      10.200001,
      'EXPR',
      'Locator flexfield. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Cost_Group',
      'CCG',
      'COST_GROUP',
      10.900003,
      'COL',
      'Cost group. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Cost_Group_Item_Cost',
      'CQL',
      'ITEM_COST',
      11.100004,
      'COL',
      'Item cost of the cost group. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'To_Project_Number',
      null,
      '(SELECT segment1              FROM pa.pa_projects_all p             WHERE p.project_id = mattr.to_project_id)',
      10.700003,
      'EXPR',
      'To project number. Custom Field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_column_templates(
      view_label,
      query_position,
      column_label,
      table_alias,
      column_expression,
      column_position,
      column_type,
      description,
      ref_application_label,
      ref_table_name,
      key_view_label,
      ref_lookup_column_name,
      ref_description_column_name,
      ref_lookup_type,
      id_flex_application_id,
      id_flex_code,
      group_by_flag,
      format_mask,
      format_class,
      gen_search_by_col_flag,
      lov_view_label,
      lov_column_label,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      'Transation_Cost',
      'CQL',
      'ITEM_COST',
      11.000004,
      'COL',
      'Transaction item cost. Custom field added by Zensar.',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'N',
      null,
      'STRING',
      'N',
      null,
      null,
      null,
      '*',
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );


INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      332.0,
      'AND MATTR.COST_GROUP_ID = CQL.COST_GROUP_ID (+) AND MATTR.INVENTORY_ITEM_ID = CQL.INVENTORY_ITEM_ID (+) AND MATTR.ORGANIZATION_ID = CQL.ORGANIZATION_ID (+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );

INSERT INTO n_view_where_templates(
      view_label,
      query_position,
      where_clause_position,
      where_clause,
      profile_option,
      product_version,
      include_flag,
      user_include_flag,
      created_by,
      last_updated_by
   ) VALUES (
      'INV_Transactions',
      1.0,
      331.0,
      'AND MATTR.COST_GROUP_ID = CCG.COST_GROUP_ID (+)',
      null,
      null,
      'Y',
      'Y',
      'nemuser',
      'nemuser'
   );





COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff