-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_deliverable_po_pay_dtl_where
--
--SQL Statement which produced this data:
--  select * from n_view_where_templates where  view_label like 'OKE_Deliverable_PO_Pay_Dtl'
--
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 1, 'AND CHDR.ID = KDLVB.K_HEADER_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 1.1, 'AND PHDR.K_HEADER_ID = CHDR.ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/16/2008 23:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 23:45:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 1.2, 'AND CHDR.AUTHORING_ORG_ID = XMAP.ORG_ID', NULL, 
    '%', 'hpothuri', TO_DATE('07/17/2008 02:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/17/2008 02:05:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 2, 'AND CLNE.ID = KDLVB.K_LINE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 2.1, 'AND PLNE.K_LINE_ID = CLNE.ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/16/2008 23:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 23:45:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 3, 'AND RDIST.OKE_CONTRACT_DELIVERABLE_ID = KDLVB.DELIVERABLE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:32:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 4, 'AND RQLIN.REQUISITION_LINE_ID = RDIST.REQUISITION_LINE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 5, 'AND RQHDR.REQUISITION_HEADER_ID  = RQLIN.REQUISITION_HEADER_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 6, 'AND PDSTR.REQ_DISTRIBUTION_ID = RDIST.DISTRIBUTION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 7, 'AND POHDR.PO_HEADER_ID = POLIN.PO_HEADER_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 8, 'AND SHIPM.LINE_LOCATION_ID = PDSTR.LINE_LOCATION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 9, 'AND SHIPM.PO_LINE_ID = POLIN.PO_LINE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 10, 'AND CHRG.INVOICE_DISTRIBUTION_ID = IDSTR.INVOICE_DISTRIBUTION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 11, 'AND CHRG.PO_DISTRIBUTION_ID = PDSTR.PO_DISTRIBUTION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 12, 'AND INV.INVOICE_ID = IDSTR.INVOICE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 13, 'AND TERMS.TERM_ID(+) = INV.TERMS_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('07/18/2008 09:09:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 13.1, 'AND TERMS.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/17/2008 06:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/17/2008 06:13:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 14, 'AND VEND.VENDOR_ID = INV.VENDOR_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 15, 'AND VSITE.VENDOR_SITE_ID = INV.VENDOR_SITE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 16, 'AND ITEM.INVENTORY_ITEM_ID  = KDLVB.ITEM_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 04:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 17, 'AND ITEM.ORGANIZATION_ID  = KDLVB.INVENTORY_ORG_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 18, 'AND PROJ.PROJECT_ID(+) = KDLVB.PROJECT_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 19, ' AND TASK.TASK_ID(+) = KDLVB.TASK_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 22:38:00', 'MM/DD/YYYY HH24:MI:SS'));
@utlspoff
COMMIT;
