-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_prj_contr_funding_hist_column

Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 1, 'COL', 'Project contract number.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Contract_Currency_Code', 'CHDR', 'CURRENCY_CODE', 4, 'ALOOK', 'The currency used for this contract.', 'NOETIX', 'NOETIX_FND_CURRENCIES_VL', 'CURRENCY_CODE', 'NAME', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Contract_Status', 'CHDR', 'STS_CODE', 6, 'LOOK', 'Status of this project contract.', 'OKC', 'OKC_STATUSES_TL', 'CODE', 'MEANING', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Funding_Version', 'FUNDH', 'MAJOR_VERSION', 16, 'COL', 'Major version of the funding for the contract.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 05:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Change_Request_Number', 'FUNDH', 'APPS.XXNAO_OKE_WRAPPER_PKG.GET_CHANGE_REQUEST_NAME(FUNDH.OBJECT_ID,FUNDH.MAJOR_VERSION)', 17, 'EXPR', 'Change request number which impacted the funding.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 05:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Agreement_Number', 'FUNDH', 'AGREEMENT_NUMBER', 19, 'COL', 'Agreement number of the funding.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Amount', 'FUNDH', 'AMOUNT', 20, 'COL', 'Funding amount for the contract and version.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 05:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Initial_Amount', 'FUNDH', 'INITIAL_AMOUNT', 21, 'COL', 'Initial funding amount.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Previous_Amount', 'FUNDH', 'PREVIOUS_AMOUNT', 22, 'COL', 'Previous amount of the funding version record.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 05:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Funding_Currency_Code', 'FUNDH', 'CURRENCY_CODE', 23, 'ALOOK', 'The currency used for this funding.', 'NOETIX', 'NOETIX_FND_CURRENCIES_VL', 'CURRENCY_CODE', 'NAME', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/21/2008 02:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Total_Funded_Amount', 'FUNDS', 'AMOUNT', 7, 'COL', 'The total amount allocated for funding.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Funding_Status', 'FUNDS', 'FUNDING_STATUS', 10, 'LOOK', 'The status of the funding. It can be definitized , undefinitized or NULL.', 'NOETIX', 'N_OKE_LOOKUPS_VL', 'MEANING', 'FUNDING_STATUS', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Invoice_Hard_Limit', 'FUNDS', 'HARD_LIMIT', 11, 'COL', 'Invoice hard limit of the funding as part of this contract.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Revenue_Hard_Limit', 'FUNDS', 'REVENUE_HARD_LIMIT', 12, 'COL', 'Revenue hard limit of the funding as part of this contract.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Effective_Start_Date', 'FUNDS', 'START_DATE_Active', 13, 'COL', 'Date on which funding source becomes active.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Effective_End_Date', 'FUNDS', 'END_DATE_ACTIVE', 14, 'COL', 'Date on which funding source becomes inactive.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Agreement_Organization_Name', 'ORGL', 'NAME', 5, 'COL', 'The organization name that owns this project funding agreement.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Party_Number', 'PRTY', 'PARTY_NUMBER', 8, 'COL', 'The corresponding party number for this funding party.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Party_Name', 'PRTY', 'PARTY_NAME', 9, 'COL', 'Party name indicates the customer who is providing the funding for this contract.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Funding_Hist', 1, 'Contract_Version', 'VERS.MAJOR_VERSION + 1', 2, 'EXPR', 'Project contract version.', 'N', '%', 'kkondaveeti', TO_DATE('06/30/2008 03:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 06:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');

COMMIT;

@utlspoff