-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_project_contract_lines_table
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'CHDR', 2, 'OKC', 'OKC_K_HEADERS_B', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 01:58:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/23/2008 06:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'CHDRL', 3, 'OKC', 'OKC_K_HEADERS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 01:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 01:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'CLNE', 5, 'OKC', 'OKC_K_LINES_B', '%', 'Y', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'CLNEL', 6, 'OKC', 'OKC_K_LINES_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'CORGL', 16, 'HR', 'HR_ALL_ORGANIZATION_UNITS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'HLD', 15.1, 'OKE', 'OKE_K_HOLDS', '%', 'N', 'N', 'hpothuri', TO_DATE('07/15/2008 02:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/15/2008 02:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'HSTSL', 24, 'OKE', 'OKE_HOLD_STATUSES_TL', '%', 'N', 'N', 'hpothuri', TO_DATE('07/15/2008 03:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/15/2008 03:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'IORGL', 17, 'HR', 'HR_ALL_ORGANIZATION_UNITS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'ITEM', 9, 'INV', 'MTL_SYSTEM_ITEMS', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'LINE', 20, 'OKC', 'OKC_K_LINES_B', '%', 'N', 'Y', 'hpothuri', TO_DATE('06/20/2008 04:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/20/2008 04:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'LSTYL', 15, 'OKC', 'OKC_LINE_STYLES_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'MCHDR', 11, 'OKC', 'OKC_K_HEADERS_B', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'OORGL', 18, 'HR', 'HR_ALL_ORGANIZATION_UNITS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'PHDR', 1, 'OKE', 'OKE_K_HEADERS', '%', 'Y', 'OKE_Project_Contracts', 'N', 'Rvattikonda', TO_DATE('06/18/2008 01:58:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'PLNE', 7, 'OKE', 'OKE_K_LINES', '%', 'Y', 'OKE_Project_Contract_Lines', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/23/2008 06:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'PORGL', 19, 'HR', 'HR_ALL_ORGANIZATION_UNITS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'PRCL', 14, 'OKE', 'OKE_PRIORITY_CODES_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'PRGM', 12, 'OKE', 'OKE_PROGRAMS', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'PRJT', 10, 'PA', 'PA_PROJECT_TYPES_ALL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'PROJ', 4, 'PA', 'PA_PROJECTS_ALL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 01:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 01:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'TASK', 8, 'PA', 'PA_TASKS', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'VERS', 13, 'OKC', 'OKC_K_VERS_NUMBERS', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/18/2008 02:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/18/2008 02:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Lines', 1, 'XMAP', 1.1, 'NOETIX', 'OKE_OU_ACL_MAP_BASE', '%', 'N', 'N', 'hpothuri', TO_DATE('06/27/2008 05:53:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/27/2008 05:53:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
COMMIT;
@utlspoff