-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_project_contract_terms_column

Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 3, 'COL', 'Project contract number.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 01:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Contract_Start_Date', 'CHDR', 'START_DATE', 14, 'COL', 'Contract start date.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 05:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 05:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Contract_Expiration_Date', 'CHDR', 'END_DATE', 15, 'COL', 'Contract expiration date.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 05:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 05:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Contract_Status', 'CHDR', 'STS_CODE', 16, 'LOOK', 'Current status of the contract.', 'OKC', 'OKC_STATUSES_TL', 'CODE', 'MEANING', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 05:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 05:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Contract_Line_Number', 'CLINE', 'LINE_NUMBER', 5, 'COL', 'Project contract line number.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 01:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_LOOKUP_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Contr_Term', 'CTERM', 'CONTR_TERM', 2, 'ATTR', 'Terms and conditions descriptive flexfield (OKE_K_Terms).', 'ATTRIBUTE%', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 01:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Term_Value', 'CTERM', 'APPS.XXNAO_OKE_WRAPPER_PKG.GET_TERM_VALUES (CTERM.TERM_CODE, CTERM.TERM_VALUE_PK1, CTERM.TERM_VALUE_PK2, ''MEANING'')', 9, 'EXPR', 'Term value.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 01:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Term_Value_Description', 'CTERM', 'APPS.XXNAO_OKE_WRAPPER_PKG.GET_TERM_VALUES (CTERM.TERM_CODE, CTERM.TERM_VALUE_PK1, CTERM.TERM_VALUE_PK2, ''DESCRIPTION'')', 10, 'EXPR', 'Description of the term value.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 01:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Term_Value_Start_Date', 'CTERM', 'TO_DATE(APPS.XXNAO_OKE_WRAPPER_PKG.GET_TERM_VALUES (CTERM.TERM_CODE, CTERM.TERM_VALUE_PK1, CTERM.TERM_VALUE_PK2, ''START_DATE_ACTIVE''), ''DD-MON-RR'')', 11, 'EXPR', 'Start date of the term value.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 02:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/21/2008 21:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Term_Value_End_Date', 'CTERM', 'TO_DATE(APPS.XXNAO_OKE_WRAPPER_PKG.GET_TERM_VALUES (CTERM.TERM_CODE, CTERM.TERM_VALUE_PK1, CTERM.TERM_VALUE_PK2, ''END_DATE_ACTIVE''), ''DD-MON-RR'')', 12, 'EXPR', 'End date of the term value.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 02:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/21/2008 21:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Operating_Unit_Name', 'ORG', 'NAME', 8, 'COL', 'Name of the operating unit the project contract belongs to.', 'N', 'OKE_XOP_AND_GLOBAL', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/18/2008 03:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Project_Name', 'PROJ', 'NAME', 17, 'COL', 'The name of the project associated with the contract.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 05:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Project_Number', 'PROJ', 'SEGMENT1', 18, 'COL', 'Project numebr associated with the contract.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Contract_Type_Name', 'PTYPL', 'K_TYPE_NAME', 13, 'COL', 'Contract type. Possible value are "Award'', "Bid", "Proposal", "RFP", "IFB" etc.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 05:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 05:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Term_Type', 'TERMB', 'TERM_TYPE_CODE', 1, 'LOOK', 'Term type.', 'NOETIX', 'N_OKE_LOOKUPS_VL', 'MEANING', 'TERM_TYPE', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 01:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'User_Defined_Flag', 'TERMB', 'NVL(USER_DEFINED_FLAG,''N'')', 7, 'EXPR', 'Flag indicates whether or not the term is defined by user.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 02:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Term_Name', 'TERML', 'TERM_NAME', 6, 'COL', 'Term name.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 01:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Terms', 1, 'Contract_Version', 'VERSN', 'MAJOR_VERSION + 1', 4, 'EXPR', 'Project contract version.', 'N', '%', 'jbhattacharya', TO_DATE('12/17/2008 01:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('12/17/2008 01:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');

Insert into N_VIEW_COLUMN_TEMPLATES
   (
   VIEW_LABEL, 
   QUERY_POSITION, 
   COLUMN_LABEL, 
   TABLE_ALIAS, 
   COLUMN_EXPRESSION, 
   COLUMN_POSITION, 
   COLUMN_TYPE, 
   DESCRIPTION, 
   GROUP_BY_FLAG, 
   PRODUCT_VERSION, 
   CREATED_BY, 
   CREATION_DATE, 
   LAST_UPDATED_BY, 
   LAST_UPDATE_DATE, 
   FORMAT_CLASS, 
   GEN_SEARCH_BY_COL_FLAG
   )
 Values
   (
   'OKE_Project_Contract_Terms', 
   1, 
   'Term_Creation_Date', 
   'CTERM', 
   'CREATION_DATE', 
   19, 
   'COL', 
   'Date on which the term was created.', 
   'N', 
   '%', 
   'jbhattacharya', 
   TO_DATE('03/09/2009 04:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
   'jbhattacharya', 
   TO_DATE('03/09/2009 04:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
   'STRING', 
   'N'
   );

Insert into N_VIEW_COLUMN_TEMPLATES
   (
   VIEW_LABEL, 
   QUERY_POSITION, 
   COLUMN_LABEL, 
   TABLE_ALIAS, 
   COLUMN_EXPRESSION, 
   COLUMN_POSITION, 
   COLUMN_TYPE, 
   DESCRIPTION, 
   REF_APPLICATION_LABEL, 
   REF_TABLE_NAME, 
   REF_LOOKUP_COLUMN_NAME, 
   REF_DESCRIPTION_COLUMN_NAME, 
   GROUP_BY_FLAG, 
   PRODUCT_VERSION, 
   CREATED_BY, 
   CREATION_DATE, 
   LAST_UPDATED_BY, 
   LAST_UPDATE_DATE, 
   FORMAT_CLASS, 
   GEN_SEARCH_BY_COL_FLAG
   )
 Values
   (
   'OKE_Project_Contract_Terms', 
   1, 
   'Term_Created_By_User_Name', 
   'CTERM', 
   'CREATED_BY', 
   20, 
   'LOOK', 
   'Name of the user who created the term.', 
   'FND', 
   'FND_USER', 
   'USER_ID', 
   'USER_NAME', 
   'N', 
   '%', 
   'jbhattacharya', 
   TO_DATE('03/09/2009 04:01:00', 'MM/DD/YYYY HH24:MI:SS'), 
   'jbhattacharya', 
   TO_DATE('03/09/2009 04:02:00', 'MM/DD/YYYY HH24:MI:SS'), 
   'STRING', 
   'N'
   );

@utlspoff

COMMIT;
