-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_deliverable_receivables_table
--
--SQL Statement which produced this data:
--  select * from n_view_table_templates where  view_label like 'OKE_Deliverable_Receivables'
--
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'BEVNT', 4, 'OKE', 
    'OKE_K_BILLING_EVENTS', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'CHDR', 1, 'OKC', 
    'OKC_K_HEADERS_B', NULL, '%', 'Y', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:16:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'CLINB', 2, 'OKC', 
    'OKC_K_LINES_B', NULL, '%', 'Y', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:16:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'CTRX', 10, 'AR', 
    'RA_CUSTOMER_TRX_ALL', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'CTRXL', 11, 'AR', 
    'RA_CUSTOMER_TRX_LINES_ALL', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'DINVI', 8, 'PA', 
    'PA_DRAFT_INVOICE_ITEMS', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'EVNT', 5, 'PA', 
    'PA_EVENTS', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'IMPLN', 9, 'PA', 
    'PA_IMPLEMENTATIONS_ALL', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'ITEM', 14, 'INV', 
    'MTL_SYSTEM_ITEMS', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'KDLVB', 3, 'OKE', 
    'OKE_K_DELIVERABLES_B', NULL, '%', 'Y', 'OKE_Prj_Contr_Deliverables', 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:16:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'PHDR', 2.1, 'OKE', 
    'OKE_K_HEADERS', NULL, '%', 'Y', 'OKE_Project_Contracts', 
    'N', 'pvemuru', TO_DATE('07/17/2008 03:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:16:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'PLNE', 2.2, 'OKE', 
    'OKE_K_LINES', NULL, '%', 'Y', 'OKE_Project_Contract_Lines', 
    'N', 'pvemuru', TO_DATE('07/17/2008 03:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:16:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'PROJ', 6, 'PA', 
    'PA_PROJECTS_ALL', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'PSHD', 12, 'OKE', 
    'OKE_AR_PAYMENT_SCHED_BASE', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/17/2008 02:27:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'TASK', 7, 'PA', 
    'PA_TASKS', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'TERM', 13, 'AR', 
    'RA_TERMS_TL', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 03:42:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Receivables', 1, 'XMAP', 1.1, 'NOETIX', 
    'OKE_OU_ACL_MAP_BASE', NULL, '%', 'N', NULL, 
    'N', 'hpothuri', TO_DATE('07/16/2008 05:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/17/2008 02:27:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
    @utlspoff
COMMIT;
