-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_project_contract_roles_table
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'CHDR', 2, 'OKC', 'OKC_K_HEADERS_B', '%', 'Y', 'N', 'Rvattikonda', TO_DATE('06/09/2008 05:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 06:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'CHDRL', 2.1, 'OKC', 'OKC_K_HEADERS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 21:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 21:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'EMP', 9, 'HR', 'PER_ALL_PEOPLE_F', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/09/2008 05:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'KPDFB', 4, 'OKC', 'OKC_PROCESS_DEFS_B', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 05:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/10/2008 01:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'KPDFL', 5, 'OKC', 'OKC_PROCESS_DEFS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 05:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'KPRC', 3, 'OKC', 'OKC_K_PROCESSES', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 05:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/10/2008 02:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'PHDR', 1, 'OKE', 'OKE_K_HEADERS', '%', 'Y', 'OKE_Project_Contracts', 'N', 'Rvattikonda', TO_DATE('06/09/2008 05:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 06:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'PPRTB', 7, 'PA', 'PA_PROJECT_ROLE_TYPES_B', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 05:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/09/2008 05:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'PPRTL', 8, 'PA', 'PA_PROJECT_ROLE_TYPES_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 05:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'PPRTY', 6, 'PA', 'PA_PROJECT_PARTIES', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 05:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/10/2008 02:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'PTYP', 11, 'OKE', 'OKE_K_TYPES_B', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 23:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 06:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'PTYPL', 10, 'OKE', 'OKE_K_TYPES_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/09/2008 23:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 06:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'XMAP', 1.1, 'NOETIX', 'OKE_OU_ACL_MAP_BASE', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/20/2008 06:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/20/2008 06:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
COMMIT;
@utlspoff