-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_project_contracts_column
--
--
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER',
    1, 'COL', 'Project contract number.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/04/2008 00:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:04:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Intent', 'CHDR', '(CASE WHEN CHDR.BUY_OR_SELL = ''S'' THEN ''Sell'' ELSE CASE WHEN CHDR.BUY_OR_SELL = ''B'' THEN ''Buy'' ELSE NULL END END)', 4, 'EXPR', 'Intent of the project contract. Possible values are "Buy" and "Sell".', 'N', '%', 'Rvattikonda', TO_DATE('06/05/2008 21:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('08/06/2008 02:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Status', 'CHDR', 'STS_CODE',
    8, 'LOOK', 'Current status of the contract. Possible value are "Entered", " Submitted", "Active" etc.', 'OKC', 'OKC_STATUSES_TL',
    NULL, 'CODE', 'MEANING', NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri',
    TO_DATE('06/30/2008 02:45:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Currency_Code', 'CHDR', 'CURRENCY_CODE',
    10, 'ALOOK', 'The currency used for this contract.', 'NOETIX', 'NOETIX_FND_CURRENCIES_VL',
    NULL, 'CURRENCY_CODE', 'NAME', NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru',
    TO_DATE('06/30/2008 05:44:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Value', 'CHDR', 'ESTIMATED_AMOUNT',
    13, 'COL', 'Estimated total amount of the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:32:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Start_Date', 'CHDR', 'START_DATE',
    18, 'COL', 'Contract start date.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:55:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Expiry_Date', 'CHDR', 'END_DATE',
    19, 'COL', 'Contract expiry date.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:44:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Approval_Date', 'CHDR', 'DATE_APPROVED',
    32, 'COL', 'Date on which the contract was approved.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:34:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Customer_PO_Number', 'CHDR', 'CUST_PO_NUMBER',
    37, 'COL', 'Customer purchase order number.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:38:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Template_Flag', 'CHDR', 'NVL(CHDR.TEMPLATE_YN, ''N'')',
    72, 'EXPR', 'Indicates if the contract is a template or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/22/2008 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract', 'CHDR', 'CHDR',
    73, 'ATTR', 'Project Contract descriptive flexfield (OKC_K_Headers_B).', NULL, NULL,
    NULL, 'ATTRIBUTE%', NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/06/2008 01:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 00:18:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Termination_Date', 'CHDR', 'DATE_TERMINATED',
    75, 'COL', 'Date on which the contract was terminated.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/20/2008 06:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/22/2008 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Termination_Reason', 'CHDR', 'TRN_CODE',
    76, 'LOOK', 'Reason for termination of the contract.', 'NOETIX', 'N_FND_LOOKUPS_VL',
    NULL, NULL, 'MEANING', 'OKC_TERMINATION_REASON', 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/20/2008 06:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/22/2008 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Termination_Flag', 'CHDR', '(CASE WHEN CHDR.DATE_TERMINATED IS NULL THEN  ''N'' ELSE ''Y'' END)',
    77, 'EXPR', 'Indicates whether the project contract is terminated or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/23/2008 05:47:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/22/2008 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Alias', 'CHDRL', 'COGNOMEN',
    14, 'COL', 'Internal name of the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/27/2008 07:43:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Short_Description', 'CHDRL', 'SHORT_DESCRIPTION',
    25, 'COL', 'Contract short description.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:28:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Description', 'CHDRL', 'DESCRIPTION',
    26, 'COL', 'Contract description.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:29:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/09/2008 02:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Financial_Comments', 'CHDRL', 'COMMENTS',
    71, 'COL', 'Financial comments.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Hold_Type', 'HLD', 'HOLD_TYPE_CODE',
    79, 'LOOK', 'Type of hold applied on the contract.', 'NOETIX', 'N_OKE_LOOKUPS_VL',
    NULL, NULL, 'MEANING', 'HOLD_TYPE', 'N',
    NULL, '%', 'hpothuri', TO_DATE('07/14/2008 04:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/21/2008 06:35:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Hold_Reason', 'HLD', 'HOLD_REASON_CODE',
    80, 'LOOK', 'Reason for putting the contract on hold.', 'NOETIX', 'N_OKE_LOOKUPS_VL',
    NULL, NULL, 'MEANING', 'APPLY_HOLD_REASON', 'N',
    NULL, '%', 'hpothuri', TO_DATE('07/14/2008 04:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/21/2008 06:26:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Hold_Flag', 'HLD', '(CASE WHEN HLD.HOLD_ID IS NULL THEN ''N'' ELSE ''Y'' END)',
    82, 'EXPR', 'Indicates whether the contract is on hold or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'hpothuri', TO_DATE('07/14/2008 04:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/21/2008 06:37:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Hold_Apply_Date', 'HLD', 'APPLY_DATE',
    84, 'COL', 'Date when the hold was applied on the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('07/21/2008 03:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/21/2008 06:52:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Hold_Schedule_Remove_Date', 'HLD', 'SCHEDULE_REMOVE_DATE',
    85, 'COL', 'Date when the hold on the contract is scheduled to be removed.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('07/21/2008 03:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/21/2008 06:29:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Hold_Status', 'HSTSL', 'HOLD_STATUS_NAME',
    81, 'COL', 'Current status of the hold of the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'hpothuri', TO_DATE('07/14/2008 04:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/21/2008 06:30:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Master_Agreement_Name', 'MPHDR', 'K_NUMBER_DISP',
    5, 'COL', 'Master agreement of the project contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:31:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Owning_Organization_Name', 'OORG', 'NAME',
    23, 'COL', 'Owning organization name.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:26:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Operating_Unit_Name', 'ORG', 'NAME',
    22, 'COL', 'Operating unit name.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:26:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Product_Line', 'PHDR', 'PRODUCT_LINE_CODE',
    7, 'LOOK', 'Product line under which the contract can be grouped.', 'NOETIX', 'N_OKE_LOOKUPS_VL',
    NULL, NULL, 'MEANING', 'PRODUCT_LINE', 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:52:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Firm_Total_Amount', 'PHDR', 'LINE_VALUE_TOTAL',
    11, 'COL', 'Contract firm total amount.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:44:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Not_Firm_Total_Amt', 'PHDR', 'UNDEF_LINE_VALUE_TOTAL',
    12, 'COL', 'Not-firm total amount of the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:51:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Award_Date', 'PHDR', 'AWARD_DATE',
    17, 'COL', 'The date on the contract was awarded.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/09/2008 02:39:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Prime_Contract_Alias', 'PHDR', 'PRIME_K_ALIAS',
    20, 'COL', 'Prime contract alias.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:24:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Prime_Contract_Number', 'PHDR', 'PRIME_K_NUMBER',
    21, 'COL', 'Prime contract number.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:25:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Authorize_Date', 'PHDR', 'AUTHORIZE_DATE',
    27, 'COL', 'Authorize date of the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri',
    TO_DATE('06/23/2008 05:31:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Issue_Date', 'PHDR', 'DATE_ISSUED',
    28, 'COL', 'Contract issue date.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Received_Date', 'PHDR', 'DATE_RECEIVED',
    29, 'COL', 'Date on which the contract was received.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:53:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Award_Canceled_Date', 'PHDR', 'AWARD_CANCEL_DATE',
    30, 'COL', 'Date on which the contract award was canceled.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/22/2008 04:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Negotiated_Date', 'PHDR', 'DATE_NEGOTIATED',
    31, 'COL', 'Contract negotiated date.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:33:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_SIC_Code', 'PHDR', 'SIC_CODE',
    33, 'COL', 'Industry classification applicable for the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/22/2008 04:26:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Customer_Signed_Date', 'PHDR', 'DATE_SIGN_BY_CUSTOMER',
    34, 'COL', 'Date on which the contract was signed by the customer.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri',
    TO_DATE('06/23/2008 05:32:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contractor_Signed_Date', 'PHDR', 'DATE_SIGN_BY_CONTRACTOR',
    35, 'COL', 'Date the contract was signed by the contractor.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:33:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'First_Article_Approval_Date', 'PHDR', 'FAA_APPROVE_DATE',
    36, 'COL', 'First article approval date.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Non_Competition_Reason', 'PHDR', 'NO_COMPETITION_AUTHORIZE',
    38, 'COL', 'Non-competition reason.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:42:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Export_Required_Flag', 'PHDR', 'NVL(PHDR.EXPORT_FLAG, ''N'')',
    39, 'EXPR', 'Indicates if export is required for the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:39:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Classified_Flag', 'PHDR', 'NVL(PHDR.CLASSIFIED_FLAG, ''N'')',
    40, 'EXPR', 'Indicates if this contract is classified or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:21:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Penalty_Clause_Applies_Flag', 'PHDR', 'NVL(PHDR.PENALTY_CLAUSE_FLAG, ''N'')',
    41, 'EXPR', 'Indicates if penalty clause applies or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:43:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Reporting_Required_Flag', 'PHDR', 'NVL(PHDR.REPORTING_FLAG, ''N'')',
    42, 'EXPR', 'Indicates if reporting is required.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:44:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:44:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Small_Business_Plan_Reqd_Flg', 'PHDR', 'NVL(PHDR.SB_PLAN_REQ_FLAG,''N'')',
    43, 'EXPR', 'Indicates if small business plan is required.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Small_Business_Report_Reqd_Flg', 'PHDR', 'NVL(PHDR.SB_REPORT_FLAG,''N'')',
    44, 'EXPR', 'Indicates if small business report is required.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Cust_Quality_Accept_Reqd_Flg', 'PHDR', 'NVL(PHDR.CQA_FLAG,''N'')',
    45, 'EXPR', 'Indicates if customer quality acceptance is required or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/25/2008 00:43:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Cust_Furnish_Eqpmt_Reqd_Flg', 'PHDR', 'NVL(PHDR.CFE_FLAG,''N'')',
    46, 'EXPR', 'Indicates if customer furnished equipment is required or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:37:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Proposal_Delivery_Location', 'PHDR', 'PROP_DELIVERY_LOCATION',
    47, 'COL', 'Proposal delivery location.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Proposal_Due_Date', 'PHDR', 'PROP_DUE_DATE_TIME',
    48, 'COL', 'Proposal due date and time.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:53:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru',
    TO_DATE('06/23/2008 06:47:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Proposal_Expiry_Date', 'PHDR', 'PROP_EXPIRE_DATE',
    49, 'COL', 'Proposal expiry date.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:54:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Number_Of_Copies_Required', 'PHDR', 'COPIES_REQUIRED',
    50, 'COL', 'Number of copies required for the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:55:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:44:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Country_Of_Origin_Code', 'PHDR', 'COUNTRY_OF_ORIGIN_CODE',
    51, 'COL', 'Country of origin of the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru',
    TO_DATE('06/23/2008 06:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Tax_Code', 'PHDR', 'VAT_CODE',
    52, 'COL', 'Value added tax code.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/09/2008 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Cost_Of_Sale_Rate', 'PHDR', 'COST_OF_SALE_RATE',
    53, 'COL', 'Cost of sale rate in percentage.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru',
    TO_DATE('06/25/2008 01:56:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Not_To_Exceed_Amount', 'PHDR', 'NTE_AMOUNT',
    54, 'COL', 'Amount limit for the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:58:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:43:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Definitization_Target_Date', 'PHDR', 'DATE_DEFINITIZED',
    55, 'COL', 'Target date of definitization.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:01:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Technical_Data_Withhold_Rate', 'PHDR', 'TECH_DATA_WH_RATE',
    56, 'COL', 'Technical data withholding rate in percentage.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/25/2008 00:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Progress_Payment_Flag', 'PHDR', 'NVL(PHDR.PROGRESS_PAYMENT_FLAG, ''N'')',
    57, 'EXPR', 'Indicates if progress payment is applicable for the contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:45:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Progress_Payment_Rate', 'PHDR', 'PROGRESS_PAYMENT_RATE',
    58, 'COL', 'Progress payment rate in percentage.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/25/2008 00:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Progress_Pay_Alt_Liqdtn_Rate', 'PHDR', 'ALTERNATE_LIQUIDATION_RATE',
    59, 'COL', 'Alternate liquidation rate in percentage.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/25/2008 00:45:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Progress_Pay_Liquidatn_Rate', 'PHDR', 'PROGRESS_PAYMENT_LIQ_RATE',
    60, 'COL', 'Progress payment liquidation rate in percentage.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/25/2008 00:39:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Financial_Cntrl_Verified_Flg', 'PHDR', 'NVL(PHDR.FINANCIAL_CTRL_VERIFIED_FLAG, ''N'')',
    61, 'EXPR', 'Indicates if financial control is verified or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru',
    TO_DATE('06/23/2008 06:45:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Not_Exceed_Warning_Reqd_Flag', 'PHDR', 'NVL(PHDR.NTE_WARNING_FLAG, ''N'')',
    62, 'EXPR', 'Indicates if a warning is displayed for the contract if amount limit is exceeded.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/25/2008 00:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Cost_Accounting_Standard_Flg', 'PHDR', 'NVL(PHDR.CAS_FLAG, ''N'')',
    63, 'EXPR', 'Indicates whether cost accounting standards are applicable for the contract or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/22/2008 04:28:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'DCAA_Audit_Required_Flag', 'PHDR', 'NVL(PHDR.DCAA_AUDIT_REQ_FLAG,''N'')',
    64, 'EXPR', 'Indicates DCAA audit is required or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri',
    TO_DATE('06/30/2008 03:37:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Interim_Report_Required_Flag', 'PHDR', 'NVL(PHDR.INTERIM_RPT_REQ_FLAG,''N'')',
    65, 'EXPR', 'Indicates if interim report is required for the contract or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Cost_Of_Money_Flag', 'PHDR', 'NVL(PHDR.COST_OF_MONEY,''N'')',
    66, 'EXPR', 'Indicates if the cost of money is applicable for the contract or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/22/2008 04:29:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Overhead_Rate_Finalized_Flg', 'PHDR', 'NVL(PHDR.OH_RATES_FINAL_FLAG,''N'')',
    67, 'EXPR', 'Indicates if contract overhead rates are finalized.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/25/2008 00:48:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Cost_Share_Flag', 'PHDR', 'NVL(PHDR.COST_SHARE_FLAG,''N'')',
    68, 'EXPR', 'Indicates if this contract cost is shared or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 06:35:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Definitized_Flag', 'PHDR', 'NVL(PHDR.DEFINITIZED_FLAG,''N'')',
    69, 'EXPR', 'Indicates if this contract is definitized or not.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri',
    TO_DATE('06/09/2008 23:54:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Bill_Without_Definitize_Flag', 'PHDR', 'NVL(PHDR.BILL_WITHOUT_DEF_FLAG,''N'')',
    70, 'EXPR', 'Indicates whether billing can be done without definitization.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:29:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 05:17:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Item_Master_Org_Name', 'PORG', 'NAME',
    24, 'COL', 'Name of the item master organization.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru',
    TO_DATE('07/18/2008 04:34:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Priority_Rating', 'PRCL', 'PRIORITY_NAME',
    15, 'COL', 'Contract priority rating.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda',
    TO_DATE('06/05/2008 21:19:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Program_Name', 'PRGM', 'PROGRAM_NAME',
    6, 'COL', 'Program name under which the contract can be grouped.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('07/22/2008 04:25:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Project_Number', 'PROJ', 'SEGMENT1',
    9, 'COL', 'The project number that is allocated for this contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 04:58:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Project_Name', 'PROJ', 'NAME',
    74, 'COL', 'The name of the project that is allocated for this contract.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'jbhattacharya', TO_DATE('06/10/2008 04:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya',
    TO_DATE('06/10/2008 04:59:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Project_ID', 'PROJ', 'PROJECT_ID',
    83, 'ID', 'Project identifier.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'hpothuri', TO_DATE('07/14/2008 05:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri',
    TO_DATE('07/14/2008 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Type_Class', 'PTYP', 'TYPE_CLASS_CODE',
    3, 'LOOK', 'Classification of the contract type. Possible value are "Proposal", "Awarded Contract", "Solicitation", "Proposal" etc.', 'NOETIX', 'N_OKE_LOOKUPS_VL',
    NULL, NULL, 'MEANING', 'CONTRACT_TYPE_CLASS', 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri',
    TO_DATE('06/30/2008 00:08:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Type_Name', 'PTYPL', 'K_TYPE_NAME',
    2, 'COL', 'Contract type. Possible value are "Award'', "Bid", "Proposal", "RFP", "IFB" etc.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/04/2008 00:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri',
    TO_DATE('06/30/2008 01:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Project_Contracts', 1, 'Contract_Version', NULL, 'VERN.MAJOR_VERSION + 1',
    16, 'EXPR', 'Contract version.', NULL, NULL,
    NULL, NULL, NULL, NULL, 'N',
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti',
    TO_DATE('06/30/2008 06:43:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL,
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contracts', 1, 'Default_Billing_Method', 'BILM', 'BILLING_METHOD_CODE', 86, 'LOOK', 'The default billing method code of project contract.', 'OKE', 'OKE_BILLING_METHODS_TL', 'BILLING_METHOD_CODE', 'BILLING_METHOD_NAME', 'N', '11.5+', 'pvemuru', TO_DATE('11/12/2008 03:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('11/12/2008 03:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');

Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, 
   QUERY_POSITION, 
   COLUMN_LABEL, 
   TABLE_ALIAS, 
   COLUMN_EXPRESSION, 
   COLUMN_POSITION, 
   COLUMN_TYPE, 
   DESCRIPTION, 
   REF_APPLICATION_LABEL, 
   REF_TABLE_NAME, 
   KEY_VIEW_LABEL, 
   REF_LOOKUP_COLUMN_NAME, 
   REF_DESCRIPTION_COLUMN_NAME, 
   REF_LOOKUP_TYPE, 
   GROUP_BY_FLAG, 
   PROFILE_OPTION, 
   PRODUCT_VERSION, 
   CREATED_BY, 
   CREATION_DATE, 
   LAST_UPDATED_BY, 
   LAST_UPDATE_DATE, 
   FORMAT_MASK, 
   FORMAT_CLASS, 
   GEN_SEARCH_BY_COL_FLAG, 
   LOV_VIEW_LABEL, 
   LOV_COLUMN_LABEL
   )
 Values
   ('OKE_Project_Contracts', 
   1, 
   'Proj_Carrying_Out_Org_Name', 
   'PROJ', 
   'CARRYING_OUT_ORGANIZATION_ID', 
    87, 
    'LOOK', 
    'Name of the organization responsible for the project work.', 
    'HR', 
    'HR_ALL_ORGANIZATION_UNITS_TL', 
    NULL, 
    'ORGANIZATION_ID',						
    'NAME',					--REF_DESCRIPTION_COLUMN_NAME
    NULL, 
    'N', 
    NULL, 
    '%', 
    'jbhattacharya', 
    TO_DATE('09/07/2009 05:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('09/07/2009 05:15:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);

COMMIT;

@utlspoff

