-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_pcontract_print_forms_column
--
--SQL Statement which produced this data:
--  select * from n_view_column_templates t1 where t1.VIEW_LABEL = 'OKE_PContract_Print_Forms'
--
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Required_Flag', 'CFORM', 'REQUIRED_FLAG', 1, 'COL', 'Indicates whether or not the print form is mandatory for the contract/ contract line.', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 05:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 05:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Completed_Flag', 'CFORM', 'COMPLETED_FLAG', 2, 'COL', 'Indicates whether or not all the requirements of the print form have been met.', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 05:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 05:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Customer_Furnished_Flag', 'CFORM', 'CUSTOMER_FURNISHED_FLAG', 3, 'COL', 'Indicates whether or not customer is supplying the print form.', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 05:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 05:53:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Context', 'CFORM', 'CASE WHEN CFORM.K_LINE_ID IS NULL THEN ''Line'' ELSE ''Header'' END', 4, 'EXPR', 'Indicates whether the print form belongs to contract header or contract line. Possible values are "Line" and "Header".', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 05:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/16/2009 23:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Creation_Date', 'CFORM', 'CREATION_DATE', 5, 'COL', 'Date on which the print form was created.', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 05:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 05:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Created_By_User', 'CFORM', 'CREATED_BY', 6, 'LOOK', 'Name of the user who created the print form.', 'FND', 'FND_USER', 'USER_ID', 'USER_NAME', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 05:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/17/2009 02:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_LOOKUP_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form', 'CFORM', 'PRINT_FORM', 7, 'ATTR', 'Print form descriptive flexfield (OKE_K_Print_Forms).', 'ATTRIBUTE%', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 06:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 06:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Code', 'CFORM', 'PRINT_FORM_CODE', 8, 'COL', 'Print form code.', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 06:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 06:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Contract_Status', 'CHDR', 'STS_CODE', 14, 'LOOK', 'Current status of the contract.', 'OKC', 'OKC_STATUSES_TL', 'CODE', 'MEANING', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 06:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 06:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Contract_Expiration_Date', 'CHDR', 'END_DATE', 18, 'COL', 'The date the contract gets expired.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 20, 'COL', 'The contract number.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Contract_Start_Date', 'CHDR', 'START_DATE', 21, 'COL', 'Start date of the contract.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Contract_Description', 'CHDRL', 'DESCRIPTION', 17, 'COL', 'The contract description.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Contract_Line_Number', 'CLINE', 'LINE_NUMBER', 19, 'COL', 'The line number.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Item_Description', 'ITEM', 'DESCRIPTION', 34, 'COL', 'Description of the item.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Item_Number', 'ITEM', 'SEGMENT1', 35, 'COL', 'Inventory item number.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Start_Date', 'PFORM', 'START_DATE_ACTIVE', 11, 'COL', 'Effective start date of the print form.', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 06:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 06:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_End_Date', 'PFORM', 'END_DATE_ACTIVE', 12, 'COL', 'Effective end date of the print form.', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 06:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 06:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Type_Name', 'PFORM', 'PRINT_FORM_TYPE_CODE', 13, 'LOOK', 'Print form type.', 'NOETIX', 'N_OKE_LOOKUPS_VL', 'MEANING', 'PRINT_FORM_TYPE', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 06:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 06:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Name', 'PFRMT', 'PRINT_FORM_NAME', 9, 'COL', 'Name of the print form.', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 06:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 06:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Print_Form_Description', 'PFRMT', 'DESCRIPTION', 10, 'COL', 'Description of the print form.', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 06:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 06:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Owning_Organization_Name', 'PHDR', 'OWNING_ORGANIZATION_ID', 15, 'LOOK', 'The name of the organization owning the contract.', 'HR', 'HR_ALL_ORGANIZATION_UNITS_TL', 'ORGANIZATION_ID', 'NAME', 'N', '%', 'jbhattacharya', TO_DATE('03/09/2009 06:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/09/2009 06:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Contract_Award_Date', 'PHDR', 'AWARD_DATE', 16, 'COL', 'The date the contract was awarded.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Total_Estimated_Cost', 'PLINE', 'TOTAL_ESTIMATED_COST', 26, 'COL', 'Total estimated cost for the contract line.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Line_Quantity', 'PLINE', 'LINE_QUANTITY', 27, 'COL', 'The line quantity.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Line_Firm_Total_Amount', 'PLINE', 'LINE_VALUE_TOTAL', 28, 'COL', 'The confirmed total value of the contract line and its sub lines.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Line_Firm_Unit_Price', 'PLINE', 'UNIT_PRICE', 29, 'COL', 'The confirmed unit price of the item.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Customer_Item_Number', 'PLINE', 'CUSTOMER_ITEM_NUMBER', 32, 'COL', 'The customer item number.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Line_Billing_Method', 'PLINE', 'BILLING_METHOD_CODE', 33, 'LOOK', 'The billing method associated with the line.', 'OKE', 'OKE_BILLING_METHODS_TL', 'BILLING_METHOD_CODE', 'BILLING_METHOD_NAME', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Project_Name', 'PROJ', 'NAME', 24, 'COL', 'Name of the project associated with the contract.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Project_Number', 'PROJ', 'SEGMENT1', 25, 'COL', 'Project number associated with the contract.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Contract_Type_Name', 'PTYPL', 'K_TYPE_NAME', 22, 'COL', 'The contract type.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Task_Name', 'TASK', 'TASK_NAME', 36, 'COL', 'The name of the task.', 'N', '%', 'rvattikonda', TO_DATE('03/16/2009 22:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 22:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Task_Number', 'TASK', 'TASK_NUMBER', 37, 'COL', 'The number which identifies the task within a project.', 'N', '%', 'rvattikonda', TO_DATE('03/16/2009 22:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 22:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Contract_Version', 'VERN', 'MAJOR_VERSION + 1', 23, 'COL', 'The current version of the contract document.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 02:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 02:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Billable_Flag', 'NVL(PLINE.BILLABLE_FLAG,''N'')', 30, 'EXPR', 'Indicates whether the contract line is billable or not.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Print_Forms', 1, 'Shippable_Flag', 'NVL(PLINE.SHIPPABLE_FLAG,''N'')', 31, 'EXPR', 'Indicates whether the contract line is shippable or not.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 06:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 06:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
COMMIT;
@utlspoff