-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_deliverable_po_pay_dtl_column
--
--
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 
    1, 'COL', 'Project contract number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 05:06:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Record_Type', 'CHRG', 'RECORD_TYPE', 
    25, 'COL', 'Indicates whether it is an invoice distribution or charge allocation record.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 22:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', 
    TO_DATE('07/21/2008 03:13:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Contract_Line_Number', 'CLNE', 'LINE_NUMBER', 
    2, 'COL', 'Project contract line number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 05:07:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'PO_Line_Type', 'IDSTR', 'LINE_TYPE_LOOKUP_CODE', 
    24, 'LOOK', 'Purchase order line type.', 'NOETIX', 'N_AP_LOOKUPS_VL', 
    NULL, NULL, 'DISPLAYED_FIELD', 'INVOICE DISTRIBUTION TYPE', 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/18/2008 01:15:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Invoice_Type', 'INV', 'INVOICE_TYPE_LOOKUP_CODE', 
    23, 'LOOK', 'Type of invoice.', 'NOETIX', 'N_AP_LOOKUPS_VL', 
    NULL, NULL, 'DISPLAYED_FIELD', 'INVOICE TYPE', 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:12:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Invoice_Number', 'INV', 'INVOICE_NUM', 
    10, 'COL', 'Invoice number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 05:15:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Invoice_Date', 'INV', 'INVOICE_DATE', 
    11, 'COL', 'Invoice date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 05:16:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Invoice_Currency_Code', 'INV', 'INVOICE_CURRENCY_CODE', 
    12, 'ALOOK', 'Currency code of the invoice.', 'NOETIX', 'NOETIX_FND_CURRENCIES_VL', 
    NULL, 'CURRENCY_CODE', 'NAME', NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:12:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Invoice_Amount', 'INV', 'INVOICE_AMOUNT', 
    13, 'COL', 'Invoice amount.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 05:18:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Payment_Currency_Code', 'INV', 'PAYMENT_CURRENCY_CODE', 
    15, 'ALOOK', 'Currency code of payment.', 'NOETIX', 'NOETIX_FND_CURRENCIES_VL', 
    NULL, 'CURRENCY_CODE', 'NAME', NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('07/16/2008 06:55:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Invoice_Paid_Amount', 'INV', 'NVL(INV.AMOUNT_PAID,0)', 
    16, 'EXPR', 'Amount paid against the invoice.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:12:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, 
   COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, 
   KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, 
   PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
   LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL,
ID_FLEX_APPLICATION_ID, ID_FLEX_CODE)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Item', 'ITEM', 'INVENTORY_ITEM_ID', 
    8, 'SEG', 'Inventory item number.', 'INV', 'MTL_SYSTEM_ITEMS_B', 
    NULL, 'INVENTORY_ITEM_ID', NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('07/20/2008 21:57:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, NULL,'401','MSTK');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Item_Number', 'ITEM', 'SEGMENT1', 
    8, 'COL', 'Inventory item number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'pvemuru', TO_DATE('07/20/2008 21:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('07/20/2008 21:57:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Deliverable_Number', 'KDLVB', 'DELIVERABLE_NUM', 
    3, 'COL', 'Deliverable number for the project contract line.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:12:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'PO_Number', 'POHDR', 'SEGMENT1', 
    20, 'COL', 'Purchase order number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 05:30:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'PO_Line_Number', 'POLIN', 'LINE_NUM', 
    21, 'COL', 'Purchase order line number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 05:31:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Project_Number', 'PROJ', 'SEGMENT1', 
    4, 'COL', 'Project number associated with the project contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Project_Name', 'PROJ', 'NAME', 
    5, 'COL', 'Project name associated with the project contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Requisition_Number', 'RQHDR', 'SEGMENT1', 
    26, 'COL', 'Requisition number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/16/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Requisition_Line_Number', 'RQLIN', 'LINE_NUM', 
    27, 'COL', 'Requisition line number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 22:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/16/2008 22:52:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Item_Description', 'RQLIN', 'ITEM_DESCRIPTION', 
    28, 'COL', 'Description of the item in the requisition line.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 23:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:19:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'PO_Shipment_Number', 'SHIPM', 'SHIPMENT_NUM', 
    22, 'COL', 'Shipment line number of the purchase order.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:13:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Received_Quantity', 'SHIPM', 'NVL(SHIPM.QUANTITY_RECEIVED,0)', 
    29, 'EXPR', 'Quantity received against the purchase order shipment.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'jbhattacharya', TO_DATE('07/21/2008 08:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/21/2008 08:39:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Task_Name', 'TASK', 'TASK_NAME', 
    6, 'COL', 'Task name associated with the project contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Task_Number', 'TASK', 'TASK_NUMBER', 
    7, 'COL', 'Task number associated with the project contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:18:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Payment_Term', 'TERMS', 'NAME', 
    14, 'COL', 'Payment term associated with the invoice.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:14:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Supplier_Name', 'VEND', 'VENDOR_NAME', 
    18, 'COL', 'Name of the supplier.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 05:27:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Supplier_Site_Code', 'VSITE', 'VENDOR_SITE_CODE', 
    19, 'COL', 'Supplier Site name.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:29:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);

    set scan off;
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 1, 'Invoice_Unpaid_Amount', NULL, '(SELECT SUM(PSCHD.AMOUNT_REMAINING)      FROM &AP.AP_PAYMENT_SCHEDULES_ALL PSCHD    WHERE INVOICE_ID = INV.INVOICE_ID)', 
    17, 'INLINE', 'Amount which has not yet been paid against the invoice.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 05:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('07/18/2008 09:13:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
    set scan on;

Insert into N_VIEW_COLUMN_TEMPLATES
   (
   VIEW_LABEL, 
   QUERY_POSITION, 
   COLUMN_LABEL, 
   TABLE_ALIAS, 
   COLUMN_EXPRESSION, 
   COLUMN_POSITION, 
   COLUMN_TYPE, 
   DESCRIPTION, 
   REF_APPLICATION_LABEL, 
   REF_TABLE_NAME, 
   KEY_VIEW_LABEL, 
   REF_LOOKUP_COLUMN_NAME, 
   REF_DESCRIPTION_COLUMN_NAME, 
   REF_LOOKUP_TYPE, 
   GROUP_BY_FLAG, 
   PROFILE_OPTION, 
   PRODUCT_VERSION, 
   CREATED_BY, 
   CREATION_DATE, 
   LAST_UPDATED_BY, 
   LAST_UPDATE_DATE, 
   FORMAT_MASK, 
   FORMAT_CLASS, 
   GEN_SEARCH_BY_COL_FLAG, 
   LOV_VIEW_LABEL, 
   LOV_COLUMN_LABEL
   )
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 
   1, 
   'Invoice_Distr_Line_Amount', 
   'IDSTR', 
   'AMOUNT', 
    31, 
    'COL', 
    'Invoice distribution line amount.',
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'N', 
    NULL, 
    '%', 
    'jbhattacharya', 
    TO_DATE('12/15/2008 06:15:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'jbhattacharya', 
    TO_DATE('12/15/2008 06:15:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 
    'STRING', 
    'N', 
    NULL, 
    NULL);

Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, 
   QUERY_POSITION, 
   COLUMN_LABEL, 
   TABLE_ALIAS, 
   COLUMN_EXPRESSION, 
   COLUMN_POSITION, 
   COLUMN_TYPE, 
   DESCRIPTION, 
   REF_APPLICATION_LABEL, 
   REF_TABLE_NAME, 
   KEY_VIEW_LABEL, 
   REF_LOOKUP_COLUMN_NAME, 
   REF_DESCRIPTION_COLUMN_NAME, 
   REF_LOOKUP_TYPE, 
   GROUP_BY_FLAG, 
   PROFILE_OPTION, 
   PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Pay_Dtl', 
   1, 
   'Invoice_Distr_Line_Number', 
   'IDSTR', 
   'DISTRIBUTION_LINE_NUMBER', 
    30, 'COL', 'Invoice distribution line number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'jbhattacharya', TO_DATE('12/15/2008 06:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('12/15/2008 06:14:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);

COMMIT;
@utlspoff;