-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon OKE_Prj_Contr_Deliverables_Where
--
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 1, 'AND CHDR.ID = KDLVB.K_HEADER_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:39:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 1.1, 'AND CHDR.AUTHORING_ORG_ID = XMAP.ORG_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:39:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 1.2, 'AND XMAP.APPLICATION_LABEL     = ''OKE''', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:39:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan off;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 1.3, 'AND XMAP.APPLICATION_INSTANCE = ''&APPLICATION_INSTANCE''', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:39:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 3, 'AND KDLVL.LANGUAGE  (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:39:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 2, 'AND KDLVL.DELIVERABLE_ID(+) = KDLVB.DELIVERABLE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:39:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 4, 'AND CHDRL.ID(+) = CHDR.ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 5, 'AND CHDRL.LANGUAGE  (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 6, 'AND KDLVB.DIRECTION = ''IN''', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 7, 'AND PHDR.K_HEADER_ID = CHDR.ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 8, 'AND PTYP.K_TYPE_CODE = PHDR.K_TYPE_CODE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 9, 'AND PTYPL.K_TYPE_CODE(+) = PTYP.K_TYPE_CODE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 10, 'AND PTYPL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 11, 'AND CLINB.ID = KDLVB.K_LINE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 11.1, 'AND PLNE.K_LINE_ID = CLINB.ID', NULL, 
    '%', 'pvemuru', TO_DATE('07/17/2008 03:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:41:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 12, 'AND LSTYL.ID(+) = CLINB.LSE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/14/2008 05:56:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 13, 'AND LSTYL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 14, 'AND ITEM.INVENTORY_ITEM_ID (+) = KDLVB.ITEM_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 15, 'AND ITEM.ORGANIZATION_ID (+) = KDLVB.INVENTORY_ORG_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 16, 'AND PROJ.PROJECT_ID(+) = KDLVB.PROJECT_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 17, 'AND TASK.TASK_ID(+) = KDLVB.TASK_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 18, 'AND VERN.CHR_ID = KDLVB.K_HEADER_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 19, 'AND EORGL.ORGANIZATION_ID (+) = KDLVB.EXPENDITURE_ORGANIZATION_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 20, 'AND EORGL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 21, 'AND CACT.CUST_ACCOUNT_ID(+) = KDLVB.SHIP_FROM_ORG_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 22, 'AND CSITU.SITE_USE_ID (+) = KDLVB.SHIP_FROM_LOCATION_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
/*
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 23, 'AND CACST.CUST_ACCT_SITE_ID (+) = CSITU.CUST_ACCT_SITE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 24, 'AND PSITE.PARTY_SITE_ID(+) = CACST.PARTY_SITE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 25, 'AND LOC.LOCATION_ID(+) = PSITE.LOCATION_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
*/
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 26, 'AND PRTY.PARTY_ID(+) = CACT.PARTY_ID --PSITE.PARTY_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 27, 'AND (PRTY.PARTY_TYPE IN (''PERSON'', ''ORGANIZATION'') OR PRTY.PARTY_TYPE IS NULL)', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 28, 'AND VEND.VENDOR_ID (+) = KDLVB.SHIP_FROM_ORG_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 29, 'AND VENDS.VENDOR_SITE_ID(+) = KDLVB.SHIP_FROM_LOCATION_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 31, 'AND SORGL.ORGANIZATION_ID (+) = KDLVB.SHIP_TO_ORG_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 32, 'AND SORGL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 33, 'AND SLOCL.LOCATION_ID(+) = KDLVB.SHIP_TO_LOCATION_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 34, 'AND SLOCL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 35, '--AND DLVDT.SOURCE_HEADER_ID (+) = KDLVB.K_HEADER_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 36, '--AND DLVDT.SOURCE_LINE_ID (+) = KDLVB.DELIVERABLE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 37, 'AND HLD.K_HEADER_ID (+) = KDLVB.K_HEADER_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/14/2008 03:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/14/2008 03:08:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 37.1, 'AND HLD.K_LINE_ID (+) = KDLVB.K_LINE_ID', NULL, 
    '%', 'hpothuri', TO_DATE('07/16/2008 22:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/16/2008 22:29:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 37.2, 'AND HLD.DELIVERABLE_ID (+) = KDLVB.DELIVERABLE_ID', NULL, 
    '%', 'hpothuri', TO_DATE('07/16/2008 22:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/16/2008 22:29:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 37.3, 'AND HLD.REMOVE_DATE(+) IS NULL', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/21/2008 03:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/21/2008 03:32:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 38, 'AND HSTSL.HOLD_STATUS_CODE (+) = HLD.HOLD_STATUS_CODE', NULL, 
    '%', 'hpothuri', TO_DATE('07/15/2008 02:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('07/21/2008 07:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 1, 39, 'AND HSTSL.LANGUAGE (+) = NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'hpothuri', TO_DATE('07/15/2008 02:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('07/21/2008 07:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 1, 'AND CHDR.ID = KDLVB.K_HEADER_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:37:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 1.1, 'AND CHDR.AUTHORING_ORG_ID = XMAP.ORG_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:37:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 1.2, 'AND XMAP.APPLICATION_LABEL     = ''OKE''', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:37:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 1.3, 'AND XMAP.APPLICATION_INSTANCE = ''&APPLICATION_INSTANCE''', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:37:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan on;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 2, 'AND KDLVL.DELIVERABLE_ID(+) = KDLVB.DELIVERABLE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 23:37:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 3, 'AND KDLVL.LANGUAGE  (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/21/2008 03:44:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 4, 'AND CHDRL.ID(+) = CHDR.ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 5, 'AND CHDRL.LANGUAGE  (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 6, 'AND KDLVB.DIRECTION = ''OUT''', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/14/2008 06:09:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 7, 'AND PHDR.K_HEADER_ID = CHDR.ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 8, 'AND PTYP.K_TYPE_CODE = PHDR.K_TYPE_CODE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 9, 'AND PTYPL.K_TYPE_CODE(+) = PTYP.K_TYPE_CODE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 10, 'AND PTYPL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 11, 'AND CLINB.ID = KDLVB.K_LINE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 11.1, 'AND PLNE.K_LINE_ID = CLINB.ID', NULL, 
    '%', 'pvemuru', TO_DATE('07/17/2008 03:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:46:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 12, 'AND LSTYL.ID(+) = CLINB.LSE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/14/2008 05:55:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 13, 'AND LSTYL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 14, 'AND ITEM.INVENTORY_ITEM_ID (+) = KDLVB.ITEM_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 15, 'AND ITEM.ORGANIZATION_ID (+) = KDLVB.INVENTORY_ORG_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 16, 'AND PROJ.PROJECT_ID(+) = KDLVB.PROJECT_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 17, 'AND TASK.TASK_ID(+) = KDLVB.TASK_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 18, 'AND VERN.CHR_ID = KDLVB.K_HEADER_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 19, 'AND EORGL.ORGANIZATION_ID (+) = KDLVB.EXPENDITURE_ORGANIZATION_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 20, 'AND EORGL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 21, 'AND CACT.CUST_ACCOUNT_ID(+) = KDLVB.SHIP_TO_ORG_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/16/2008 23:06:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 22, 'AND CSITU.SITE_USE_ID (+) = KDLVB.SHIP_TO_LOCATION_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/16/2008 23:07:00', 'MM/DD/YYYY HH24:MI:SS'));
/*
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 23, 'AND CACST.CUST_ACCT_SITE_ID (+) = CSITU.CUST_ACCT_SITE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 24, 'AND PSITE.PARTY_SITE_ID(+) = CACST.PARTY_SITE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 25, 'AND LOC.LOCATION_ID(+) = PSITE.LOCATION_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
*/
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 26, 'AND PRTY.PARTY_ID(+) = CACT.PARTY_ID --PSITE.PARTY_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 27, 'AND (PRTY.PARTY_TYPE IN (''PERSON'', ''ORGANIZATION'') OR PRTY.PARTY_TYPE IS NULL)', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 31, 'AND SORGL.ORGANIZATION_ID (+) = KDLVB.SHIP_FROM_ORG_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/16/2008 22:59:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 32, 'AND SORGL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 33, 'AND SLOCL.LOCATION_ID(+) = KDLVB.SHIP_FROM_LOCATION_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/16/2008 23:02:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 34, 'AND SLOCL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 35, '--AND DLVDT.SOURCE_HEADER_ID (+) = KDLVB.K_HEADER_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 36, '--AND DLVDT.SOURCE_LINE_ID (+) = KDLVB.DELIVERABLE_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/11/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 37, 'AND HLD.K_HEADER_ID (+) = KDLVB.K_HEADER_ID', NULL, 
    '%', 'kkondaveeti', TO_DATE('07/14/2008 03:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/14/2008 03:08:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 37.1, 'AND HLD.K_LINE_ID (+) = KDLVB.K_LINE_ID', NULL, 
    '%', 'hpothuri', TO_DATE('07/16/2008 22:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/16/2008 22:43:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 37.2, 'AND HLD.DELIVERABLE_ID (+) = KDLVB.DELIVERABLE_ID', NULL, 
    '%', 'hpothuri', TO_DATE('07/16/2008 22:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/16/2008 22:43:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 37.3, 'AND HLD.REMOVE_DATE(+) IS NULL', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/21/2008 03:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/21/2008 03:36:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 50, 'AND HSTSL.HOLD_STATUS_CODE (+) = HLD.HOLD_STATUS_CODE', NULL, 
    '%', 'hpothuri', TO_DATE('07/15/2008 02:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/21/2008 03:49:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Prj_Contr_Deliverables', 2, 51, 'AND HSTSL.LANGUAGE (+) = NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'hpothuri', TO_DATE('07/15/2008 02:29:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/21/2008 03:50:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
@utlspoff;
