-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_deliverable_po_rcp_dtl_column
--
--SQL Statement which produced this data:
--  select * from n_view_column_templates where  view_label like 'OKE_Deliverable_PO_Rcp_Dtl'
--
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 
    1, 'COL', 'Project contract number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:47:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:47:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Contract_Line_Number', 'CLNE', 'LINE_NUMBER', 
    2, 'COL', 'Project contract line number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:48:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Requestion_Buyer', 'EMP', 'FULL_NAME', 
    14, 'COL', 'Name of the buyer for this requisition.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:01:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Receiving_Location_Code', 'HRLOC', 'LOCATION_CODE', 
    29, 'COL', 'Purchase order receiving location.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('07/18/2008 00:08:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, 
   REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, 
   GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, 
   GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL,ID_FLEX_APPLICATION_ID, ID_FLEX_CODE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Item', 'ITEM', 'INVENTORY_ITEM_ID', 
    9, 'SEG', 'Inventory item number.', 'INV', 'MTL_SYSTEM_ITEMS_B', 
    NULL, 'INVENTORY_ITEM_ID', NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:55:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/18/2008 00:42:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL,'401','MSTK');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Item_Number', 'ITEM', 'SEGMENT1', 
    9, 'COL', 'Inventory item number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'pvemuru', TO_DATE('07/20/2008 21:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('07/20/2008 21:57:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Deliverable_Number', 'KDLVB', 'DELIVERABLE_NUM', 
    3, 'COL', 'Deliverable number for this project line.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Requisition_Recv_Loc_Code', 'LOC', 'LOCATION_CODE', 
    17, 'COL', 'Requisition receiving location.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('07/18/2008 00:10:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Ordered_Quantity', 'PDSTR', 'NVL(PDSTR.QUANTITY_ORDERED,0)', 
    21, 'EXPR', 'Quantity ordered on the distribution.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/18/2008 01:29:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Delivered_Quantity', 'PDSTR', 'NVL(PDSTR.QUANTITY_DELIVERED, 0)', 
    22, 'EXPR', 'Quantity delivered against the distribution.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/18/2008 01:28:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Number', 'POHDR', 'SEGMENT1', 
    18, 'COL', 'Purchase order number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('07/17/2008 23:53:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Line_Number', 'POLIN', 'LINE_NUM', 
    19, 'COL', 'Purchase order line number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:08:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Item_UOM_Code', 'POLIN', 'UNIT_MEAS_LOOKUP_CODE', 
    23, 'ALOOK', 'Unit of measure for quantity used in the purchase order.', 'INV', 'MTL_UNITS_OF_MEASURE_TL', 
    NULL, 'UOM_CODE', 'UNIT_OF_MEASURE_TL', NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('07/21/2008 01:53:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Status', 'POSTS', 'MEANING', 
    28, 'COL', 'Purchase order status.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:20:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Buyer_Name', 'PPF', 'FULL_NAME', 
    24, 'COL', 'Name of the buyer for this purchase order.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:16:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Project_Number', 'PROJ', 'SEGMENT1', 
    4, 'COL', 'Project number of the project associated with project contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Project_Name', 'PROJ', 'NAME', 
    5, 'COL', 'Project name of the project associated with project contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:50:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Receipt_Number', 'RCVSH', 'RECEIPT_NUM', 
    33, 'COL', 'Receipt number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:29:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:29:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Actual_Receipt_Date', 'RCVSH', 'CREATION_DATE', 
    34, 'COL', 'Date on which receipt was created.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:30:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Receipt_Line_Number', 'RCVSL', 'LINE_NUM', 
    30, 'COL', 'Receipt line number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:23:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Transaction_Quantity', 'RCVTR', 'NVL(RCVTR.QUANTITY,0)', 
    31, 'EXPR', 'The receipt quantity.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/16/2008 03:56:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Receipt_Item_UOM_Code', 'RCVTR', 'UNIT_OF_MEASURE', 
    32, 'ALOOK', 'Unit of measure for quantity used in receipt.', 'INV', 'MTL_UNITS_OF_MEASURE_TL', 
    NULL, 'UOM_CODE', 'UNIT_OF_MEASURE_TL', NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('07/21/2008 01:53:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Transaction_Type', 'RCVTR', 'TRANSACTION_TYPE', 
    36, 'LOOK', 'Receiving transaction type possible values are "Receive", "Deliver".', 'NOETIX', 'N_PO_LOOKUPS_VL', 
    NULL, NULL, 'MEANING', 'RCV TRANSACTION TYPE', 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', 
    TO_DATE('07/21/2008 03:15:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Requisition_Status', 'REQST', 'MEANING', 
    16, 'COL', 'Status of the requisition, possible values are "approved", "incomplete".', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', 
    TO_DATE('07/21/2008 03:16:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Requisition_Number', 'RQHDR', 'SEGMENT1', 
    10, 'COL', 'Requisition number for the inbound deliverable line.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:57:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Item_Description', 'RQLIN', 'ITEM_DESCRIPTION', 
    8, 'COL', 'Description of the item associated with deliverable line.', 'INV', 'MTL_SYSTEM_ITEMS_B', 
    NULL, 'INVENTORY_ITEM_ID', NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/20/2008 01:47:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Requisition_Line_Number', 'RQLIN', 'LINE_NUM', 
    11, 'COL', 'Requisition Line number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:58:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:58:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Requisition_Quantity', 'RQLIN', 'NVL(RQLIN.QUANTITY,0)', 
    12, 'EXPR', 'Quantity at requisition line.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:59:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Requisition_Item_UOM_Code', 'RQLIN', 'UNIT_MEAS_LOOKUP_CODE', 
    13, 'ALOOK', 'Unit of measure for quantity in requisition.', 'INV', 'MTL_UNITS_OF_MEASURE_TL', 
    NULL, 'UOM_CODE', 'UNIT_OF_MEASURE_TL', NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('07/21/2008 01:53:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Requisition_Need_By_Date', 'RQLIN', 'NEED_BY_DATE', 
    15, 'COL', 'Date the requisition is needed internally.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:02:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Shipment_Number', 'SHIPM', 'SHIPMENT_NUM', 
    20, 'COL', 'Shipment line number on purchase order.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:09:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'PO_Need_By_Date', 'SHIPM', 'NEED_BY_DATE', 
    25, 'COL', 'Need By Date for the shipment schedule.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 02:17:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Planned_Receipt_Date', 'SHIPM', 'PROMISED_DATE', 
    35, 'COL', 'Vendor promised delivery date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('07/17/2008 23:45:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Task_Name', 'TASK', 'TASK_NAME', 
    6, 'COL', 'Task name associated with the project.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:51:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Task_Number', 'TASK', 'TASK_NUMBER', 
    7, 'COL', 'Task number associated with the project.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 01:53:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/15/2008 01:53:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Supplier_Name', 'VEND', 'VENDOR_NAME', 
    26, 'COL', 'Name of the vendor.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('07/17/2008 23:59:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 'Supplier_Number', 'VEND', 'SEGMENT1', 
    27, 'COL', 'Vendor number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/15/2008 02:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('07/17/2008 23:59:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
    @utlspoff
COMMIT;
