-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_pa_pcontract_projects_where

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 1, 'AND CHDR.ID = PHDR.K_HEADER_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('06/04/2008 00:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:30:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 1.1, 'AND CHDR.AUTHORING_ORG_ID = XMAP.ORG_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/27/2008 06:37:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 1.2, 'AND XMAP.APPLICATION_LABEL     = ''OKE''', NULL, 
    '%', 'kkondaveeti', TO_DATE('06/20/2008 06:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/27/2008 06:37:00', 'MM/DD/YYYY HH24:MI:SS'));

set scan off;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 1.3, 'AND XMAP.APPLICATION_INSTANCE  = ''&APPLICATION_INSTANCE''', NULL, 
    '%', 'kkondaveeti', TO_DATE('06/20/2008 06:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/27/2008 06:37:00', 'MM/DD/YYYY HH24:MI:SS'));

set scan on;

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 2, 'AND CHDRL.ID(+) = CHDR.ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 2.1, 'AND CHDRL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'hpothuri', TO_DATE('06/15/2008 22:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/15/2008 22:03:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 3, 'AND PROJ.PROJECT_ID = PHDR.PROJECT_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 03:12:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 5, 'AND PTYP.K_TYPE_CODE = PHDR.K_TYPE_CODE', NULL, 
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 6, 'AND PTYPL.K_TYPE_CODE(+) = PTYP.K_TYPE_CODE', NULL, 
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 7, 'AND PTYPL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL, 
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:32:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PA_PContract_Projects', 1, 8, 'AND  VERN.CHR_ID = CHDR.ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/30/2008 02:41:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
@utlspoff
