-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_project_contract_lines_view
set escape off;
Insert into N_VIEW_TEMPLATES
   (VIEW_LABEL, APPLICATION_LABEL, DESCRIPTION, PROFILE_OPTION, ESSAY, KEYWORDS, PRODUCT_VERSION, EXPORT_VIEW, SECURITY_CODE, SPECIAL_PROCESS_CODE, FREEZE_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, ORIGINAL_VERSION, CURRENT_VERSION)
 Values
   ('OKE_Project_Contract_Lines', 'OKE', 'OKE Basic - Project contract line information', 'OKE_1159_ONWARDS', 'This view returns line level information on the project contracts and the associated projects (if any). This information was supplied in the Contract Line tab of the Contracts Authoring Workbench window of the Project Contracts module in Oracle E-Business suite. A record is returned for each combination of a contract number, contract type and line number. Use this view for getting information about contract lines. This view can also be used to find upcoming expiry and termination of contract lines. This view returns contract details like contract number, type, status, currency, and award date. The view provides information of contract lines such as line number, status, style, start date, end date, quantity, value, and total. The view also provides details about the project, and tasks. The firm, non-firm and total amount columns are shown. The view also displays financial, billing, additional billing and other information of the contract line. Hold details like type, status, reason, apply date and schedule removal date are displayed. The Parent_Line_Number column displays the immediate parent line number of the contract line. The Not_Separately_Priced_Flag column indicates whether or not the item price is included in the rollup document. The Subcontracted_Flag column indicates whether or not the contract line is subcontracted. The Drop_Ship_Flag column indicates whether or not the item can be drop-shipped. The Billable_Flag column indicates whether or not the line can be billed or not. The Definitized_Flag column indicates whether the contract is definitized. The Not_Exceed_Warning_Reqd_Flag indicated whether or not a warning is displayed when the bill amount exceeds the contract total amount. The Hold_Flag column indicates whether the contract line is currently on hold or not. For optimal performance, filter the records by the Contract_Number, Line_Number, and Contract_Start_Date columns.', 'K{\footnote Project Contract Lines} K{\footnote Contract Expiry Date}', '11.5+', 'Y', 'NONE', 'NONE', 'N', 'Rvattikonda', TO_DATE('06/18/2008 01:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/22/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'), '5.7.1.383', '5.7.1.383');

COMMIT;
set escape on;

@utlspoff