-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_deliverable_std_notes_table

Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'CHDR', 2, 'OKC', 'OKC_K_HEADERS_B', '11.5+', 'Y', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'CHDRL', 4, 'OKC', 'OKC_K_HEADERS_TL', '11.5+', 'N', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'CLNE', 5, 'OKC', 'OKC_K_LINES_B', '11.5+', 'Y', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'KDLVB', 7, 'OKE', 'OKE_K_DELIVERABLES_B', '11.5+', 'Y', 'OKE_Prj_Contr_Deliverables', 'N', 'hpothuri', TO_DATE('12/11/2008 21:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'NOTE', 8, 'OKE', 'OKE_K_STANDARD_NOTES_B', '11.5+', 'Y', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'NOTL', 9, 'OKE', 'OKE_K_STANDARD_NOTES_TL', '11.5+', 'N', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'OORG', 12, 'HR', 'HR_ALL_ORGANIZATION_UNITS_TL', '11.5+', 'N', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'ORG', 13, 'HR', 'HR_ALL_ORGANIZATION_UNITS_TL', 'OKE_XOP_AND_GLOBAL', '11.5+', 'N', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/18/2008 04:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'PHDR', 1, 'OKE', 'OKE_K_HEADERS', '11.5+', 'Y', 'OKE_Project_Contracts', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'PLNE', 6, 'OKE', 'OKE_K_LINES', '11.5+', 'Y', 'OKE_Project_Contract_Lines', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'PROJ', 11, 'PA', 'PA_PROJECTS_ALL', '11.5+', 'N', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'PTYPL', 14, 'OKE', 'OKE_K_TYPES_TL', '11.5+', 'N', 'N', 'hpothuri', TO_DATE('12/18/2008 21:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/18/2008 21:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'VERN', 10, 'OKC', 'OKC_K_VERS_NUMBERS', '11.5+', 'N', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Deliverable_Std_Notes', 1, 'XMAP', 3, 'NOETIX', 'OKE_OU_ACL_MAP_BASE', '11.5+', 'N', 'N', 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('12/11/2008 21:43:52', 'MM/DD/YYYY HH24:MI:SS'), 'N');
@utlspoff
COMMIT;
