-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_deliverable_shipments_where

SET SCAN OFF

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 1, 'AND CONTH.ID = PHDR.K_HEADER_ID', '%', 'pvemuru', TO_DATE('07/16/2008 22:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 1.1, 'AND CONTH.AUTHORING_ORG_ID = XMAP.ORG_ID', '%', 'hpothuri', TO_DATE('07/16/2008 05:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:27:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 1.4, 'AND DLVDT.SOURCE_HEADER_ID = CONTH.ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:30:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 2, 'AND DLVDT.SOURCE_CODE = ''OKE''', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 3, 'AND ASGN.DELIVERY_DETAIL_ID = DLVDT.DELIVERY_DETAIL_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 4, 'AND DLV.DELIVERY_ID(+) = ASGN.DELIVERY_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 5, 'AND KDLV.DELIVERABLE_ID = DLVDT.SOURCE_LINE_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 6, 'AND CONTL.ID = KDLV.K_LINE_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 06:53:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 6.1, 'AND PLNE.K_LINE_ID = CONTL.ID', '%', 'pvemuru', TO_DATE('07/16/2008 22:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:40:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 6.2, 'AND ITEM.INVENTORY_ITEM_ID (+) = KDLV.ITEM_ID', '%', 'pvemuru', TO_DATE('07/16/2008 22:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:52:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 6.3, 'AND ITEM.ORGANIZATION_ID (+) = KDLV.INVENTORY_ORG_ID', '%', 'pvemuru', TO_DATE('07/16/2008 22:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:52:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 7, 'AND HZT.LOCATION_ID (+) = DLVDT.SHIP_TO_LOCATION_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 07:03:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 8, 'AND HZF.LOCATION_ID (+) = DLVDT.SHIP_FROM_LOCATION_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 07:03:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 9, 'AND HRT.LOCATION_ID (+) = DLVDT.SHIP_TO_LOCATION_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 07:03:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 10, 'AND HRF.LOCATION_ID (+) = DLVDT.SHIP_FROM_LOCATION_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 07:03:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 11, 'AND PROJ.PROJECT_ID (+) = KDLV.PROJECT_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 07:03:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 12, 'AND TASK.TASK_ID (+) = KDLV.TASK_ID', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 07:03:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 13, 'AND DLVST.LOOKUP_TYPE (+) = ''DELIVERY_STATUS''', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('08/05/2008 23:27:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 14, 'AND DLVST.LOOKUP_CODE (+) = NVL (DLV.STATUS_CODE, ''OP'')', '%', 'kkondaveeti', TO_DATE('07/15/2008 22:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('08/05/2008 23:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_Shipments', 1, 15, 'AND DLVST.LANGUAGE  (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'kkondaveeti', TO_DATE('07/16/2008 23:47:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('07/16/2008 23:47:00', 'MM/DD/YYYY HH24:MI:SS'));

SET SCAN ON

COMMIT;

@utlspoff