-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_pa_pcontract_projects_column

Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 
    1, 'COL', 'Project contract number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/04/2008 00:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/05/2008 21:04:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Intent', 'CHDR', 'BUY_OR_SELL', 
    4, 'LOOK', 'Project contract Intent. Possible value are "Buy" or "Sell".', 'NOETIX', 'N_OKE_LOOKUPS_VL', 
    NULL, NULL, 'MEANING', 'BUY_SELL', 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/09/2008 02:42:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Status', 'CHDR', 'STS_CODE', 
    8, 'LOOK', 'Current status of the contract. Possible value are "Entered", " Submitted", "Active" etc.', 'OKC', 'OKC_STATUSES_TL', 
    NULL, 'CODE', 'MEANING', NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('06/30/2008 02:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Currency_Code', 'CHDR', 'CURRENCY_CODE', 
    10, 'ALOOK', 'The currency used for this contract.', 'NOETIX', 'NOETIX_FND_CURRENCIES_VL', 
    NULL, 'CURRENCY_CODE', 'NAME', NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('06/30/2008 05:44:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Value', 'CHDR', 'ESTIMATED_AMOUNT', 
    13, 'COL', 'Estimated total amount of the contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:53:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Start_Date', 'CHDR', 'START_DATE', 
    18, 'COL', 'Contract start date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:52:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Expiry_Date', 'CHDR', 'END_DATE', 
    19, 'COL', 'Contract expiry date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Approval_Date', 'CHDR', 'DATE_APPROVED', 
    32, 'COL', 'Contract approval date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:48:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Customer_PO_Number', 'CHDR', 'CUST_PO_NUMBER', 
    37, 'COL', 'Customer purchase order number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:53:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Template_Flag', 'CHDR', 'NVL(CHDR.TEMPLATE_YN, ''N'')', 
    72, 'EXPR', 'Indicates if this contract is a template or not.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('06/23/2008 07:07:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Internal_Contract_Name', 'CHDRL', 'COGNOMEN', 
    14, 'COL', 'Internal name of the contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:54:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Short_Description', 'CHDRL', 'SHORT_DESCRIPTION', 
    25, 'COL', 'Contract short description.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/05/2008 21:28:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Description', 'CHDRL', 'DESCRIPTION', 
    26, 'COL', 'Contract description.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:29:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/09/2008 02:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Firm_Total_Amount', 'PHDR', 'LINE_VALUE_TOTAL', 
    11, 'COL', 'Contract firm total amount.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Not_Firm_Total_Amt', 'PHDR', 'UNDEF_LINE_VALUE_TOTAL', 
    12, 'COL', 'Not-firm total amount of the contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:50:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Award_Date', 'PHDR', 'AWARD_DATE', 
    17, 'COL', 'The date on which the contract was awarded.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:48:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Prime_Contract_Number', 'PHDR', 'PRIME_K_NUMBER', 
    21, 'COL', 'Prime contract number.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/05/2008 21:25:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Authorize_Date', 'PHDR', 'AUTHORIZE_DATE', 
    27, 'COL', 'Contract authorization date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('06/23/2008 03:04:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Issue_Date', 'PHDR', 'DATE_ISSUED', 
    28, 'COL', 'Contract issue date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 04:44:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Received_Date', 'PHDR', 'DATE_RECEIVED', 
    29, 'COL', 'Contract received date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/05/2008 21:32:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Negotiated_Date', 'PHDR', 'DATE_NEGOTIATED', 
    31, 'COL', 'Contract negotiated date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/05/2008 21:33:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Customer_Signed_Date', 'PHDR', 'DATE_SIGN_BY_CUSTOMER', 
    34, 'COL', 'Date on which the contract was signed by the customer.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:54:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contractor_Signed_Date', 'PHDR', 'DATE_SIGN_BY_CONTRACTOR', 
    35, 'COL', 'Date on which the contract was signed by the contractor.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:53:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Proposal_Delivery_Location', 'PHDR', 'PROP_DELIVERY_LOCATION', 
    47, 'COL', 'Proposal delivery location.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/05/2008 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Proposal_Due_Date', 'PHDR', 'PROP_DUE_DATE_TIME', 
    48, 'COL', 'Due date of the proposal due date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:53:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('06/23/2008 06:18:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Proposal_Expiry_Date', 'PHDR', 'PROP_EXPIRE_DATE', 
    49, 'COL', 'Proposal expiry date.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/05/2008 21:54:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Tax_Code', 'PHDR', 'VAT_CODE', 
    52, 'COL', 'Value added tax code.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('06/09/2008 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Not_To_Exceed_Amount', 'PHDR', 'NTE_AMOUNT', 
    54, 'COL', 'Amount limit of the contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:58:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 06:54:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Target_Definitization_Date', 'PHDR', 'DATE_DEFINITIZED', 
    55, 'COL', 'Target date of definitization.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('06/23/2008 06:20:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Definitized_Flag', 'PHDR', 'NVL(PHDR.DEFINITIZED_FLAG,''N'')', 
    69, 'EXPR', 'Indicates if this contract is definitized or not.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 22:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('06/09/2008 23:54:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Project_Number', 'PROJ', 'SEGMENT1', 
    9, 'COL', 'The project number that is allocated for this contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 04:46:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Project_Name', 'PROJ', 'NAME', 
    73, 'COL', 'The name of the project that is allocated for this contract.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'jbhattacharya', TO_DATE('06/10/2008 04:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 04:46:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Project_Start_Date', 'PROJ', 'START_DATE', 
    74, 'COL', 'The start date of the project.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'jbhattacharya', TO_DATE('06/10/2008 04:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 04:46:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Project_Completion_Date', 'PROJ', 'COMPLETION_DATE', 
    75, 'COL', 'The completion date of the project.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'jbhattacharya', TO_DATE('06/10/2008 04:47:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('06/10/2008 04:47:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Project_ID', 'PROJ', 'PROJECT_ID', 
    76, 'ID', 'Project idetifier.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'hpothuri', TO_DATE('07/14/2008 05:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('07/14/2008 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Type_Class', 'PTYP', 'TYPE_CLASS_CODE', 
    3, 'LOOK', 'Classification of the contract type. Possible value are "Proposal", "Awarded Contract", "Solicitation", "Proposal" etc.', 'NOETIX', 'N_OKE_LOOKUPS_VL', 
    NULL, NULL, 'MEANING', 'CONTRACT_TYPE_CLASS', 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('06/30/2008 00:08:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Type_Name', 'PTYPL', 'K_TYPE_NAME', 
    2, 'COL', 'Contract type. Possible value are "Award'', "Bid", "Proposal", "RFP", "IFB" etc.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/04/2008 00:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('06/30/2008 01:40:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_PA_PContract_Projects', 1, 'Contract_Version', NULL, 'VERN.MAJOR_VERSION + 1', 
    16, 'EXPR', 'Contract version.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('06/05/2008 21:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', 
    TO_DATE('06/30/2008 06:43:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
COMMIT;
@utlspoff
