-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_ap_invoices_base_table
--
--SQL Statement which produced this data:
--  select * from n_view_table_templates where  view_label like 'OKE_AP_Invoices_Base'
--
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_AP_Invoices_Base', 1, 'INVD', 1, 'AP', 
    'AP_INVOICE_DISTRIBUTIONS_ALL', NULL, '%', 'N', NULL, 
    'N', 'Rvattikonda', TO_DATE('07/16/2008 21:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 21:41:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_AP_Invoices_Base', 2, 'ICHRG', 1, 'AP', 
    'AP_CHRG_ALLOCATIONS_ALL', NULL, '%', 'N', NULL, 
    'N', 'Rvattikonda', TO_DATE('07/16/2008 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_AP_Invoices_Base', 2, 'IDSTR', 2, 'AP', 
    'AP_INVOICE_DISTRIBUTIONS_ALL', NULL, '%', 'N', NULL, 
    'N', 'Rvattikonda', TO_DATE('07/16/2008 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 21:52:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
    @utlspoff
COMMIT;
