-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_ap_invoices_base_column
--
--SQL Statement which produced this data:
--  select * from n_view_column_templates where  view_label like 'OKE_AP_Invoices_Base'
--
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_AP_Invoices_Base', 1, 'Invoice_Distribution_ID', 'INVD', 'INVOICE_DISTRIBUTION_ID', 
    1, 'COL', 'Identifier of the invoice.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 21:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', 
    TO_DATE('07/17/2008 02:58:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_AP_Invoices_Base', 1, 'Allocated_Amount', 'INVD', 'AMOUNT', 
    2, 'COL', 'Invoice distribution amount.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 21:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/16/2008 21:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_AP_Invoices_Base', 1, 'PO_Distribution_ID', 'INVD', 'PO_DISTRIBUTION_ID', 
    3, 'COL', 'Purchase order distribution line identifier for purchase order or receipt matched invoice distributions.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 21:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('07/17/2008 23:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_AP_Invoices_Base', 1, 'Record_Type', NULL, 'Invoice Distribution', 
    4, 'CONST', 'Record type indicates whether charge is allocated for a record or it is invoice distribution.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 22:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/16/2008 22:07:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_AP_Invoices_Base', 2, 'Invoice_Distribution_ID', 'ICHRG', 'CHARGE_DIST_ID', 
    1, 'COL', 'Identifier of the invoice distribution.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 22:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('07/17/2008 23:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_AP_Invoices_Base', 2, 'Allocated_Amount', 'ICHRG', 'ALLOCATED_AMOUNT', 
    2, 'COL', 'Amount allocated in invoice currency.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 22:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/16/2008 22:02:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_AP_Invoices_Base', 2, 'PO_Distribution_ID', 'IDSTR', 'PO_DISTRIBUTION_ID', 
    3, 'COL', 'Purchase order distribution line identifier for purchase order or receipt matched invoice distributions.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 22:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', 
    TO_DATE('07/17/2008 23:49:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_AP_Invoices_Base', 2, 'Record_Type', NULL, 'Charge Allocated', 
    4, 'CONST', 'Record type indicates whether charge is allocated for a record or it is invoice distribution.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'Rvattikonda', TO_DATE('07/16/2008 22:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', 
    TO_DATE('07/16/2008 22:06:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);
    @utlspoff
COMMIT;
