-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_prj_contr_fund_sources_column

Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Contract_Currency_Code', 'CHDR', 'CURRENCY_CODE', 2, 'ALOOK', 'The currency used for this contract.', 'NOETIX', 'NOETIX_FND_CURRENCIES_VL', 'CURRENCY_CODE', 'NAME', 'N', '%', 'kkondaveeti', TO_DATE('06/26/2008 22:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 3, 'COL', 'Project contract number.', 'N', '%', 'kkondaveeti', TO_DATE('06/26/2008 23:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/26/2008 23:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Contract_Status', 'CHDR', 'STS_CODE', 21, 'LOOK', 'Status of this project contract.', 'OKC', 'OKC_STATUSES_TL', 'CODE', 'MEANING', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 02:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Funding_Pool_Name', 'FPOOL', 'NAME', 14, 'COL', 'Name of the funding pool. By creating funding pool you can have the ability to fund multiple contracts from this pool.', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 00:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/27/2008 00:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Exchange_Rate_Date', 'FUNDS', 'K_CONVERSION_DATE', 5, 'COL', 'Date of currency exchange rate to contract currency.', 'N', '%', 'kkondaveeti', TO_DATE('06/26/2008 23:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 23:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Exchange_Rate', 'FUNDS', 'K_CONVERSION_RATE', 6, 'COL', 'Currency exchange rate to contract currency.', 'N', '%', 'kkondaveeti', TO_DATE('06/26/2008 23:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 23:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Exchange_Rate_Type_Code', 'FUNDS', 'K_CONVERSION_TYPE', 7, 'COL', 'Exchange rate type for conversion to contract currency.', 'N', '%', 'kkondaveeti', TO_DATE('06/26/2008 23:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 23:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Effective_End_Date', 'FUNDS', 'END_DATE_ACTIVE', 8, 'COL', 'Date on which funding source becomes inactive.', 'N', '%', 'kkondaveeti', TO_DATE('06/26/2008 23:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/26/2008 23:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Effective_Start_Date', 'FUNDS', 'START_DATE_ACTIVE', 9, 'COL', 'Date on which funding source becomes active.', 'N', '%', 'kkondaveeti', TO_DATE('06/26/2008 23:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/26/2008 23:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Fund_Across_Oper_Unit', NULL, 'TO_CHAR(NULL)', 10, 'EXPR', 'OBSOLETE COLUMN. This column should no longer be used. The replacement column is Fund_Across_Operating_Unit_Flg. This column will be removed in a future release.', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 03:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Fund_Currency_Code', 'FUNDS', 'CURRENCY_CODE', 11, 'ALOOK', 'The currency used for this funding.', 'NOETIX', 'NOETIX_FND_CURRENCIES_VL', 'CURRENCY_CODE', 'NAME', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 00:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Fund_Previous_Amount', 'FUNDS', 'PREVIOUS_AMOUNT', 12, 'COL', 'Amount from the previous version of the funding source.', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 00:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/27/2008 00:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Funding_Amount', 'FUNDS', 'AMOUNT', 13, 'COL', 'The amount funded for this funding.', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 00:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/27/2008 00:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Initial_Amount', 'FUNDS', 'INITIAL_AMOUNT', 15, 'COL', 'Initial funding source amount.', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 00:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/27/2008 00:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Invoice_Hard_Limit', 'FUNDS', 'HARD_LIMIT', 16, 'COL', 'Invoice hard limit of the funding as part of this contract.', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 00:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 03:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Revenue_Hard_Limit', 'FUNDS', 'REVENUE_HARD_LIMIT', 19, 'COL', 'Revenue hard limit of the funding as part of this contract.', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 01:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/30/2008 03:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Funding_Status', 'FUNDS', 'FUNDING_STATUS', 22, 'LOOK', 'The status of the funding. It can be definitized, undefinitized or NULL.', 'NOETIX', 'N_OKE_LOOKUPS_VL', 'MEANING', 'FUNDING_STATUS', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 04:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/21/2008 03:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_LOOKUP_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Fundsrc', 'FUNDS', 'FUNDSRC', 23, 'ATTR', 'Funding source descriptive flexfield (OKE_K_Funding_Sources).', 'ATTRIBUTTE%', 'N', '%', 'hpothuri', TO_DATE('06/29/2008 23:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/29/2008 23:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_LOOKUP_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Pafundsrc', 'FUNDS', 'PAFUNDSRC', 24, 'ATTR', 'Project funding source descriptive flexfield (OKE_K_Funding_Sources).', 'PA_ATTRIBUTE%', 'N', '%', 'hpothuri', TO_DATE('06/29/2008 23:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/29/2008 23:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Agreement_Organization_Name', 'ORGL', 'NAME', 1, 'COL', 'The organization name that owns this project funding agreement.', 'N', '%', 'kkondaveeti', TO_DATE('06/26/2008 22:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/26/2008 22:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Party_Name', 'PRTY', 'PARTY_NAME', 17, 'COL', 'Party name indicates the customer who is providing the funding for this contract.', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 00:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/27/2008 00:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Party_Number', 'PRTY', 'PARTY_NUMBER', 18, 'COL', 'The corresponding party number for this funding party.', 'N', '%', 'kkondaveeti', TO_DATE('06/27/2008 00:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/27/2008 00:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Contract_Version', 'VERS.MAJOR_VERSION + 1', 4, 'EXPR', 'Project contract version.', 'N', '%', 'kkondaveeti', TO_DATE('06/26/2008 23:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/30/2008 06:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');

Insert into N_VIEW_COLUMN_TEMPLATES
   (
   VIEW_LABEL, 
   QUERY_POSITION, 
   COLUMN_LABEL, 
   TABLE_ALIAS, 
   COLUMN_EXPRESSION, 
   COLUMN_POSITION, 
   COLUMN_TYPE, 
   DESCRIPTION, 
   GROUP_BY_FLAG, 
   PRODUCT_VERSION, 
   CREATED_BY, 
   CREATION_DATE, 
   LAST_UPDATED_BY, 
   LAST_UPDATE_DATE, 
   FORMAT_CLASS, 
   GEN_SEARCH_BY_COL_FLAG
   )
 Values
   (
   'OKE_Prj_Contr_Fund_Sources', 
   1, 
   'Agreement_Number', 
   'FUNDS', 
   'AGREEMENT_NUMBER', 
   25, 
   'COL', 
   'Project agreement number related to the funding source.', 
   'N', 
   '11.5+', 
   'pvemuru', 
   TO_DATE('09/17/2008 23:37:00', 'MM/DD/YYYY HH24:MI:SS'), 
   'pvemuru', 
   TO_DATE('09/17/2008 23:37:00', 'MM/DD/YYYY HH24:MI:SS'), 
   'STRING', 
   'N'
   );

   Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, KEY_VIEW_LABEL, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_MASK, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG, LOV_VIEW_LABEL, LOV_COLUMN_LABEL)
 Values
   ('OKE_Prj_Contr_Fund_Sources', 1, 'Fund_Across_Operating_Unit_Flg', NULL, 'NVL(FUNDS.FUNDING_ACROSS_OU,''N'')', 
    26, 'EXPR', 'Indicates whether or not the operating unit(s) of the funded project(s) can be different from the operating unit of the funding source.', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, '%', 'jbhattacharya', TO_DATE('09/08/2009 04:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', 
    TO_DATE('09/08/2009 04:38:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'STRING', 'N', NULL, 
    NULL);

COMMIT;

@utlspoff