-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_pcontract_articles_column
--
--SQL Statement which produced this data:
--  select * from n_view_column_templates t1 where t1.VIEW_LABEL = 'OKE_PContract_Articles'
--
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Created_By_User', 'ACRBY', 'USER_NAME', 3, 'COL', 'Name of the user who created the article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Last_Updated_By_User', 'ALUPD', 'USER_NAME', 4, 'COL', 'Name of the user who last updated the article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_LOOKUP_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article', 'ARTB', 'ARTB', 24, 'ATTR', 'Article descriptive flexfield (OKC_K_Articles_B).', 'ATTRIBUTE%', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/17/2009 02:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Name', 'ARTCL', 'ARTICLE_TITLE', 23, 'COL', 'Name of the article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 04:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Creation_Date', 'ARTCL', 'CREATION_DATE', 1, 'COL', 'Creation date of the article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Last_Update_Date', 'ARTCL', 'LAST_UPDATE_DATE', 2, 'COL', 'Last update date of the article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Subject', 'ARTCL', 'ARTICLE_TYPE', 18, 'LOOK', 'Subject of the article.', 'NOETIX', 'N_FND_LOOKUPS_VL', 'MEANING', 'OKC_SUBJECT', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Text', 'AVERN', 'ARTICLE_TEXT', 25, 'COL', 'Textual content of the article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Std_Article_Release_Number', 'AVERN', 'SAV_RELEASE', 26, 'COL', 'Release number of the standard article to which the contract is associated with.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 04:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 04:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Comment', 'AVERN', 'ARTICLE_DESCRIPTION', 27, 'COL', 'Article Comment.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 04:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Status', 'CHDR', 'STS_CODE', 37, 'LOOK', 'Current status of the contract.', 'OKC', 'OKC_STATUSES_TL', 'CODE', 'MEANING', 'N', '%', 'rvattikonda', TO_DATE('03/16/2009 20:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 20:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 5, 'COL', 'The contract number.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Expiry_Date', 'CHDR', 'END_DATE', 7, 'COL', 'The date the contract gets expired.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Start_Date', 'CHDR', 'START_DATE', 8, 'COL', 'Start date of the contract.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Termination_Date', 'CHDR', 'DATE_TERMINATED', 9, 'COL', 'Date on which the contract was terminated.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Description', 'CHDRL', 'DESCRIPTION', 38, 'COL', 'The contract description.', 'N', '%', 'rvattikonda', TO_DATE('03/16/2009 20:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 20:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_LOOKUP_COLUMN_NAME, REF_DESCRIPTION_COLUMN_NAME, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Line_Status', 'CLINE', 'STS_CODE', 36, 'LOOK', 'The line status.', 'OKC', 'OKC_STATUSES_TL', 'MEANING', 'CODE', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 05:44:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:44:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Line_Number', 'CLINE', 'LINE_NUMBER', 6, 'COL', 'The line number.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Line_Start_Date', 'CLINE', 'START_DATE', 10, 'COL', 'Start date of the contract line.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Line_Termination_Date', 'CLINE', 'DATE_TERMINATED', 11, 'COL', 'Date on which line was terminated.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Version', 'CVERN', 'MAJOR_VERSION + 1', 16, 'COL', 'The current version of the contract document.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Item_Description', 'ITEM', 'DESCRIPTION', 33, 'COL', 'Description of the item.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 05:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Item_Number', 'ITEM', 'SEGMENT1', 34, 'COL', 'Inventory item number.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 05:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Line_Style_Name', 'LSTYL', 'NAME', 35, 'COL', 'The line style name.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 05:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Award_Date', 'PHDR', 'AWARD_DATE', 39, 'COL', 'The date the contract was awarded.', 'N', '%', 'rvattikonda', TO_DATE('03/16/2009 20:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 20:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Item_UOM_Code', 'PLINE', 'UOM_CODE', 28, 'COL', 'The unit of measure code of the line item.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 05:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Total_Estimated_Cost', 'PLINE', 'TOTAL_ESTIMATED_COST', 29, 'COL', 'Total estimated cost for the contract line.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 05:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Line_Quantity', 'PLINE', 'LINE_QUANTITY', 30, 'COL', 'The line quantity.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 05:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Line_Firm_Total_Amount', 'PLINE', 'LINE_VALUE_TOTAL', 31, 'COL', 'The confirmed total value of the contract line and its sub lines.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Line_Firm_Unit_Price', 'PLINE', 'UNIT_PRICE', 32, 'COL', 'The confirmed unit price of the item.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 05:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Project_Name', 'PROJ', 'NAME', 12, 'COL', 'Name of the project associated with the contract.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Project_Number', 'PROJ', 'SEGMENT1', 13, 'COL', 'Project number associated with the contract.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Contract_Type_Name', 'PTYPL', 'K_TYPE_NAME', 40, 'COL', 'The contract type.', 'N', '%', 'rvattikonda', TO_DATE('03/16/2009 20:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 20:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_End_Date', 'SVERN', 'END_DATE', 21, 'COL', 'Effective end date of the article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Status', 'SVERN', 'ARTICLE_STATUS', 22, 'COL', 'Current status of the article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Start_Date', 'SVERN', 'START_DATE', 20, 'COL', 'Effective start date of the article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Task_Name', 'TASK', 'TASK_NAME', 14, 'COL', 'The name of the task.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Task_Number', 'TASK', 'TASK_NUMBER', 15, 'COL', 'The number which identifies the task within a project.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Article_Context', 'CASE
          WHEN CLINE.LINE_NUMBER IS NOT NULL
             THEN ''Line''
          ELSE ''Header''
       END', 17, 'EXPR', 'Indicates whether the article belongs to contract header or contract line. Possible values are "Line" and "Header".', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('03/16/2009 23:58:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PContract_Articles', 1, 'Standard_Article_Flag', ' (CASE ARTB.CAT_TYPE
           WHEN ''STA''
              THEN ''Y''
           ELSE ''N''
        END)', 19, 'EXPR', 'Flag to indicate whether or not the article is a standard article.', 'N', '%', 'rvattikonda', TO_DATE('03/13/2009 03:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 03:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
COMMIT;
@utlspoff