-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_pa_pcontract_projects_table

Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PA_PContract_Projects', 1, 'CHDR', 2, 'OKC', 
    'OKC_K_HEADERS_B', NULL, '%', 'Y', NULL, 
    'N', 'Rvattikonda', TO_DATE('06/04/2008 00:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:55:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PA_PContract_Projects', 1, 'CHDRL', 3, 'OKC', 
    'OKC_K_HEADERS_TL', NULL, '%', 'N', NULL, 
    'N', 'Rvattikonda', TO_DATE('06/05/2008 03:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/10/2008 02:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PA_PContract_Projects', 1, 'PHDR', 1, 'OKE', 
    'OKE_K_HEADERS', NULL, '%', 'Y', 'OKE_Project_Contracts', 
    'N', 'Rvattikonda', TO_DATE('06/04/2008 00:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:55:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PA_PContract_Projects', 1, 'PROJ', 4, 'PA', 
    'PA_PROJECTS_ALL', NULL, '%', 'Y', NULL, 
    'N', 'Rvattikonda', TO_DATE('06/05/2008 03:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 03:24:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PA_PContract_Projects', 1, 'PTYP', 6, 'OKE', 
    'OKE_K_TYPES_B', NULL, '%', 'N', NULL, 
    'N', 'Rvattikonda', TO_DATE('06/05/2008 03:58:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 03:58:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PA_PContract_Projects', 1, 'PTYPL', 7, 'OKE', 
    'OKE_K_TYPES_TL', NULL, '%', 'N', NULL, 
    'N', 'Rvattikonda', TO_DATE('06/05/2008 03:59:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 03:59:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PA_PContract_Projects', 1, 'VERN', 8, 'OKC', 
    'OKC_K_VERS_NUMBERS', NULL, '%', 'N', NULL, 
    'N', 'Rvattikonda', TO_DATE('06/05/2008 04:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/30/2008 02:42:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PROFILE_OPTION, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_PA_PContract_Projects', 1, 'XMAP', 2.1, 'NOETIX', 
    'OKE_OU_ACL_MAP_BASE', NULL, '%', 'N', NULL, 
    'N', 'kkondaveeti', TO_DATE('06/20/2008 06:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/20/2008 06:35:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N');
COMMIT;
@utlspoff
