-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_proj_contract_parties_table
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'CHDR', 2, 'OKC', 'OKC_K_HEADERS_B', '%', 'Y', 'N', 'kkondaveeti', TO_DATE('06/06/2008 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'PHDR', 1, 'OKE', 'OKE_K_HEADERS', '%', 'Y', 'OKE_Project_Contracts', 'N', 'kkondaveeti', TO_DATE('06/18/2008 03:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'PRTYB', 3, 'OKC', 'OKC_K_PARTY_ROLES_B', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/06/2008 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/18/2008 03:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'PRTYL', 4, 'OKC', 'OKC_K_PARTY_ROLES_TL', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/06/2008 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/18/2008 03:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'XMAP', 1.1, 'NOETIX', 'OKE_OU_ACL_MAP_BASE', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/20/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/20/2008 05:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'CHDR', 3, 'OKC', 'OKC_K_HEADERS_B', '%', 'Y', 'N', 'kkondaveeti', TO_DATE('06/06/2008 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'CLINB', 2, 'OKC', 'OKC_K_LINES_B', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/18/2008 04:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/18/2008 04:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'PHDR', 3.1, 'OKE', 'OKE_K_HEADERS', '%', 'Y', 'OKE_Project_Contracts', 'N', 'pvemuru', TO_DATE('07/01/2008 06:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 06:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'PLNE', 1, 'OKE', 'OKE_K_LINES', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/18/2008 04:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:57:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'PRTYB', 4, 'OKC', 'OKC_K_PARTY_ROLES_B', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/06/2008 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/18/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'PRTYL', 5, 'OKC', 'OKC_K_PARTY_ROLES_TL', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/06/2008 03:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/18/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'XMAP', 1.1, 'NOETIX', 'OKE_OU_ACL_MAP_BASE', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/20/2008 05:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/20/2008 05:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
COMMIT;
@utlspoff