-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_pcontract_articles_where
--
--SQL Statement which produced this data:
--  select * from n_view_where_templates t1 where t1.VIEW_LABEL = 'OKE_PContract_Articles'
--
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 1, 'AND ARTB.DNZ_CHR_ID = CHDR.ID', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 2, 'AND CHDR.ID = PHDR.K_HEADER_ID', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 3, 'AND CVERN.CHR_ID = CHDR.ID', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 3.1, 'AND XMAP.ORG_ID = CHDR.AUTHORING_ORG_ID', '%', 'rvattikonda', TO_DATE('03/15/2009 21:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/15/2009 21:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 3.2, 'AND XMAP.APPLICATION_LABEL     = ''OKE''', '%', 'rvattikonda', TO_DATE('03/15/2009 21:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/15/2009 21:19:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan off;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 3.3, 'AND XMAP.APPLICATION_INSTANCE  = ''&APPLICATION_INSTANCE''', '%', 'rvattikonda', TO_DATE('03/15/2009 21:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/15/2009 21:19:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan on;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 4, 'AND PLINE.K_LINE_ID(+) = CLINE.ID', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 5, 'AND ARTB.CLE_ID = CLINE.ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 5.1, 'AND CHDR.ID = CHDRL.ID(+)', '%', 'rvattikonda', TO_DATE('03/16/2009 20:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 20:41:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 5.2, 'AND CHDRL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'rvattikonda', TO_DATE('03/16/2009 20:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 20:41:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 5.3, 'AND PTYPL.K_TYPE_CODE(+) = PHDR.K_TYPE_CODE', '%', 'rvattikonda', TO_DATE('03/16/2009 20:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 20:41:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 5.4, 'AND PTYPL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'rvattikonda', TO_DATE('03/16/2009 20:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/16/2009 20:41:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 6, 'AND PHDR.PROJECT_ID = PROJ.PROJECT_ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 7, 'AND PLINE.TASK_ID = TASK.TASK_ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 8, 'AND ARTB.ARTICLE_VERSION_ID = AVERN.ARTICLE_VERSION_ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 9, 'AND ARTB.SAV_SAE_ID = ARTCL.ARTICLE_ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 10, 'AND AVERN.STD_ARTICLE_VERSION_ID = SVERN.ARTICLE_VERSION_ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 11, 'AND ARTCL.CREATED_BY = ACRBY.USER_ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 12, 'AND ARTCL.LAST_UPDATED_BY = ALUPD.USER_ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 04:27:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 13, 'AND PLINE.INVENTORY_ITEM_ID = ITEM.INVENTORY_ITEM_ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 05:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:46:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 14, 'AND (ITEM.ORGANIZATION_ID = CHDR.INV_ORGANIZATION_ID OR ITEM.ORGANIZATION_ID IS NULL)', '%', 'rvattikonda', TO_DATE('03/13/2009 05:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:46:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 15, 'AND CLINE.LSE_ID =  LSTYL.ID(+)', '%', 'rvattikonda', TO_DATE('03/13/2009 05:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:46:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_PContract_Articles', 1, 16, 'AND LSTYL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'rvattikonda', TO_DATE('03/13/2009 05:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'rvattikonda', TO_DATE('03/13/2009 05:46:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
@utlspoff