-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_proj_contr_user_attrs_table

Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 1, 'CHDR', 2, 'OKC', 'OKC_K_HEADERS_B', '%', 'Y', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 1, 'CHDRL', 3, 'OKC', 'OKC_K_HEADERS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/06/2008 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 1, 'DFCTL', 5, 'FND', 'FND_DESCR_FLEX_CONTEXTS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/06/2008 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 1, 'PHDR', 1, 'OKE', 'OKE_K_HEADERS', '%', 'Y', 'OKE_Project_Contracts', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 1, 'PTYP', 6, 'OKE', 'OKE_K_TYPES_B', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/06/2008 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 1, 'PTYPL', 7, 'OKE', 'OKE_K_TYPES_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/06/2008 03:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 1, 'UATR', 4, 'OKE', 'OKE_K_USER_ATTRIBUTES', '%', 'Y', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/10/2008 02:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 1, 'XMAP', 1.1, 'NOETIX', 'OKE_OU_ACL_MAP_BASE', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/20/2008 06:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/20/2008 06:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'CHDR', 2, 'OKC', 'OKC_K_HEADERS_B', '%', 'Y', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'CHDRL', 3, 'OKC', 'OKC_K_HEADERS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/06/2008 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'CLINB', 1.2, 'OKC', 'OKC_K_LINES_B', '%', 'N', 'N', 'pvemuru', TO_DATE('06/19/2008 23:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/19/2008 23:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'DFCTL', 5, 'FND', 'FND_DESCR_FLEX_CONTEXTS_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/06/2008 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, KEY_VIEW_LABEL, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'PHDR', 1, 'OKE', 'OKE_K_HEADERS', '%', 'Y', 'OKE_Project_Contracts', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:07:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/01/2008 05:56:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'PLNE', 1.1, 'OKE', 'OKE_K_LINES', '%', 'N', 'N', 'pvemuru', TO_DATE('06/19/2008 23:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/19/2008 23:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'PTYP', 6, 'OKE', 'OKE_K_TYPES_B', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/06/2008 03:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'PTYPL', 7, 'OKE', 'OKE_K_TYPES_TL', '%', 'N', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/06/2008 03:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'UATR', 4, 'OKE', 'OKE_K_USER_ATTRIBUTES', '%', 'Y', 'N', 'Rvattikonda', TO_DATE('06/06/2008 03:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/10/2008 02:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y');
Insert into N_VIEW_TABLE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, TABLE_ALIAS, FROM_CLAUSE_POSITION, APPLICATION_LABEL, TABLE_NAME, PRODUCT_VERSION, BASE_TABLE_FLAG, SUBQUERY_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contr_User_Attrs', 2, 'XMAP', 2.1, 'NOETIX', 'OKE_OU_ACL_MAP_BASE', '%', 'N', 'N', 'kkondaveeti', TO_DATE('06/20/2008 06:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/20/2008 06:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
COMMIT;
@utlspoff