-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_deliverable_po_rcp_dtl_where
--
--SQL Statement which produced this data:
--  select * from n_view_where_templates where  view_label like 'OKE_Deliverable_PO_Rcp_Dtl'
--
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 1, 'AND CHDR.ID = KDLVB.K_HEADER_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:21:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 1.1, 'AND CHDR.AUTHORING_ORG_ID = XMAP.ORG_ID', NULL, 
    '%', 'hpothuri', TO_DATE('07/16/2008 06:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/16/2008 06:04:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 2, 'AND CLNE.ID = KDLVB.K_LINE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 2.1, 'AND PHDR.K_HEADER_ID = CHDR.ID', NULL, 
    '%', 'pvemuru', TO_DATE('07/16/2008 22:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:43:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 2.2, 'AND PLNE.K_LINE_ID = CLNE.ID', NULL, 
    '%', 'pvemuru', TO_DATE('07/16/2008 22:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:43:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 3, 'AND PROJ.PROJECT_ID(+) = KDLVB.PROJECT_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 4, 'AND TASK.TASK_ID(+) = KDLVB.TASK_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 5, 'AND ITEM.INVENTORY_ITEM_ID(+)  = KDLVB.ITEM_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:46:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 6, 'AND ITEM.ORGANIZATION_ID(+)  = KDLVB.INVENTORY_ORG_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/16/2008 22:46:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 7, 'AND RDIST.OKE_CONTRACT_DELIVERABLE_ID = KDLVB.DELIVERABLE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 8, 'AND RQLIN.REQUISITION_LINE_ID = RDIST.REQUISITION_LINE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 9, 'AND RQLIN.REQUISITION_HEADER_ID = RQHDR.REQUISITION_HEADER_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 10, 'AND LOC.LOCATION_ID  = RQLIN.DELIVER_TO_LOCATION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 11, 'AND EMP.PERSON_ID(+) = RQLIN.SUGGESTED_BUYER_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 12, 'AND TRUNC (SYSDATE) BETWEEN NVL (EMP.EFFECTIVE_START_DATE(+), SYSDATE - 1)', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 13, 'AND NVL (EMP.EFFECTIVE_END_DATE(+), SYSDATE + 1)', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:26:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 14, 'AND REQST.LOOKUP_CODE(+) = NVL (RQHDR.AUTHORIZATION_STATUS, ''INCOMPLETE'')', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 03:05:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 15, 'AND REQST.LOOKUP_TYPE(+) = ''AUTHORIZATION STATUS''', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/16/2008 03:05:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 16, 'AND PDSTR.REQ_DISTRIBUTION_ID(+) = RDIST.DISTRIBUTION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:32:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 17, 'AND POLIN.PO_LINE_ID(+) = PDSTR.PO_LINE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:32:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 18, 'AND POHDR.PO_HEADER_ID(+) = PDSTR.PO_HEADER_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:32:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 19, 'AND SHIPM.LINE_LOCATION_ID(+) = PDSTR.LINE_LOCATION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 20, 'AND HRLOC.LOCATION_ID(+) = SHIPM.SHIP_TO_LOCATION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 21, 'AND VEND.VENDOR_ID(+) = POHDR.VENDOR_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 22, 'AND PPF.PERSON_ID(+) = POHDR.AGENT_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:34:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 23, 'AND TRUNC (SYSDATE) BETWEEN NVL (PPF.EFFECTIVE_START_DATE(+), SYSDATE - 1)', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:34:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 24, 'AND NVL (PPF.EFFECTIVE_END_DATE (+), SYSDATE + 1)', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:34:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 25, 'AND POSTS.LOOKUP_TYPE(+) = ''AUTHORIZATION STATUS''', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:35:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 26, 'AND POSTS.LOOKUP_CODE(+) = CASE WHEN POHDR.PO_HEADER_ID IS NULL THEN NULL ELSE NVL (POHDR.AUTHORIZATION_STATUS, ''INCOMPLETE'') END', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:35:00', 'MM/DD/YYYY HH24:MI:SS'));
/*
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 27, 'AND RCVTR.PO_DISTRIBUTION_ID(+) = PDSTR.PO_DISTRIBUTION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:36:00', 'MM/DD/YYYY HH24:MI:SS'));
*/
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 27.1, 'AND RCVTR.PO_LINE_LOCATION_ID(+) = PDSTR.LINE_LOCATION_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:36:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 28, 'AND RCVSL.SHIPMENT_LINE_ID(+) = RCVTR.SHIPMENT_LINE_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:36:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Deliverable_PO_Rcp_Dtl', 1, 29, 'AND RCVSH.SHIPMENT_HEADER_ID(+) = RCVSL.SHIPMENT_HEADER_ID', NULL, 
    '%', 'Rvattikonda', TO_DATE('07/15/2008 01:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/15/2008 01:36:00', 'MM/DD/YYYY HH24:MI:SS'));
@utlspoff
COMMIT;
