-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_project_contracts_where
--
--SQL Statement which produced this data:
--  select * from n_view_where_templates where  view_label like 'OKE_Project_Contracts'
--
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 1, 'AND CHDR.ID = PHDR.K_HEADER_ID', NULL,
    '%', 'Rvattikonda', TO_DATE('06/04/2008 00:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 03:30:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 1.1, 'AND CHDR.AUTHORING_ORG_ID = XMAP.ORG_ID', NULL,
    '%', 'jbhattacharya', TO_DATE('06/10/2008 03:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/27/2008 06:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 1.2, 'AND XMAP.APPLICATION_LABEL     = ''OKE''', NULL,
    '%', 'hpothuri', TO_DATE('06/27/2008 06:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/27/2008 06:01:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan off;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 1.3, 'AND XMAP.APPLICATION_INSTANCE  = ''&APPLICATION_INSTANCE''', NULL,
    '%', 'hpothuri', TO_DATE('06/27/2008 06:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/27/2008 06:01:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan on;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 2, 'AND CHDRL.ID(+) = CHDR.ID', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 03:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 2.1, 'AND CHDRL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL,
    '%', 'jbhattacharya', TO_DATE('06/10/2008 03:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 03:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 3, 'AND PROJ.PROJECT_ID(+) = PHDR.PROJECT_ID', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 4, 'AND MPHDR.K_HEADER_ID(+) = PHDR.BOA_ID', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 5, 'AND PTYP.K_TYPE_CODE = PHDR.K_TYPE_CODE', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 6, 'AND PTYPL.K_TYPE_CODE(+) = PTYP.K_TYPE_CODE', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:31:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 7, 'AND PTYPL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:32:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 8, 'AND PRGM.PROGRAM_ID(+) = PHDR.PROGRAM_ID', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:32:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 11, 'AND  PRCL.PRIORITY_CODE(+) = PHDR.PRIORITY_CODE', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 12, 'AND PRCL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 13, 'AND  VERN.CHR_ID = CHDR.ID', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 13.1, 'AND HLD.K_HEADER_ID (+) = PHDR.K_HEADER_ID', NULL,
    '%', 'hpothuri', TO_DATE('07/14/2008 03:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/14/2008 03:16:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 13.2, 'AND HLD.REMOVE_DATE(+) IS NULL', NULL,
    '%', 'Rvattikonda', TO_DATE('07/21/2008 03:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('07/21/2008 03:21:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, 
   QUERY_POSITION, 
   WHERE_CLAUSE_POSITION, 
   WHERE_CLAUSE, 
   PROFILE_OPTION, 
   PRODUCT_VERSION, 
   CREATED_BY, 
   CREATION_DATE, 
   LAST_UPDATED_BY, 
   LAST_UPDATE_DATE
   )
 Values
   ('OKE_Project_Contracts', 
   1, 
   13.3, 
   'AND HLD.K_LINE_ID(+) IS NULL', 
   NULL,
    '%', 
    'jbhattacharya', 
    TO_DATE('01/21/2009 03:16:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'jbhattacharya', 
    TO_DATE('01/21/2009 03:16:00', 'MM/DD/YYYY HH24:MI:SS')
    );

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, 
   QUERY_POSITION, 
   WHERE_CLAUSE_POSITION, 
   WHERE_CLAUSE, 
   PROFILE_OPTION, 
   PRODUCT_VERSION, 
   CREATED_BY, 
   CREATION_DATE, 
   LAST_UPDATED_BY, 
   LAST_UPDATE_DATE
   )
 Values
   ('OKE_Project_Contracts', 
   1, 
   13.4, 
   'AND HLD.DELIVERABLE_ID(+) IS NULL', 
   NULL,
    '%', 
    'jbhattacharya', 
    TO_DATE('01/21/2009 03:21:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'jbhattacharya', 
    TO_DATE('01/21/2009 03:21:00', 'MM/DD/YYYY HH24:MI:SS')
    );


Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 14, 'AND ORG.ORGANIZATION_ID(+) = CHDR.AUTHORING_ORG_ID', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/21/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 15, 'AND ORG.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 16, 'AND OORG.ORGANIZATION_ID(+) = PHDR.OWNING_ORGANIZATION_ID', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 17, 'AND OORG.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:35:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 18, 'AND PORG.ORGANIZATION_ID(+) = CHDR.INV_ORGANIZATION_ID', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:36:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 19, 'AND PORG.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', NULL,
    '%', 'Rvattikonda', TO_DATE('06/05/2008 04:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/05/2008 04:36:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 20, 'AND HSTSL.HOLD_STATUS_CODE (+) = HLD.HOLD_STATUS_CODE', NULL,
    '%', 'hpothuri', TO_DATE('07/15/2008 03:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('07/21/2008 06:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PROFILE_OPTION, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 21, 'AND HSTSL.LANGUAGE (+) = NOETIX_ENV_PKG.GET_LANGUAGE', NULL,
    '%', 'hpothuri', TO_DATE('07/15/2008 03:24:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('07/21/2008 06:33:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 22, 'AND BILM.K_HEADER_ID (+) = PHDR.K_HEADER_ID', '%', 'pvemuru', TO_DATE('11/12/2008 03:44:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('11/12/2008 03:44:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contracts', 1, 23, 'AND BILM.DEFAULT_FLAG (+) = ''Y''', '%', 'pvemuru', TO_DATE('11/12/2008 03:44:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('11/12/2008 03:44:00', 'MM/DD/YYYY HH24:MI:SS'));

@utlspoff;
COMMIT;
