-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_project_contract_roles_column
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 1, 'COL', 'Project contract number.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Contract_Start_Date', 'CHDR', 'START_DATE', 9, 'COL', 'Contract start date.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 23:08:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Contract_Expiry_Date', 'CHDR', 'END_DATE', 10, 'COL', 'Contract expiration date.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:09:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Contract_Value', 'CHDR', 'ESTIMATED_AMOUNT', 13, 'COL', 'Estimated total amount of the contract.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:12:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Contract_Short_Description', 'CHDRL', 'SHORT_DESCRIPTION', 11, 'COL', 'Contract short description.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 23:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Contract_Description', 'CHDRL', 'DESCRIPTION', 12, 'COL', 'Contract description.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 23:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Employee_Name', 'EMP', 'FULL_NAME', 5, 'COL', 'Name of the employee.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Workflow_Usage_Type_Name', 'KPDFB', 'USAGE', 2, 'LOOK', 'Usage type of the workflow.', 'NOETIX', 'N_FND_LOOKUPS_VL', 'MEANING', 'OKC_PROCESS_USAGE_TYPES', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:27:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Approv_Workflow_Process_Name', 'KPDFB', 'WF_PROCESS_NAME', 4, 'COL', 'Approval workflow process name of the contract.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:34:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Approval_Workflow_Name', 'KPDFL', 'NAME', 3, 'COL', 'Approval workflow name of the contract.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:33:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Employee_Role_Name', 'PPRTL', 'MEANING', 6, 'COL', 'Role of the employee in the contract. Possible value are "Program manager", "Contract administrator".', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:37:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('07/21/2008 03:55:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Employee_Role_Start_Date', 'PPRTY', 'START_DATE_ACTIVE', 7, 'COL', 'Start date of the employee role in the contract.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Employee_Role_End_Date', 'PPRTY', 'END_DATE_ACTIVE', 8, 'COL', 'End date of the employee role in the contract.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:39:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Project_Contract_Roles', 1, 'Contract_Type_Name', 'PTYPL', 'K_TYPE_NAME', 14, 'COL', 'Contract type. Possible value are "Award'', "Bid", "Proposal", "RFP", "IFB" etc.', 'N', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/30/2008 01:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
COMMIT;
@utlspoff