-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_proj_contract_events_where
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 1, 'AND CHDR.ID = PHDR.K_HEADER_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:53:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 1.1, 'AND CHDR.AUTHORING_ORG_ID = XMAP.ORG_ID', '%', 'hpothuri', TO_DATE('07/16/2008 06:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:52:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan off;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 1.2, 'AND XMAP.APPLICATION_INSTANCE  = ''&APPLICATION_INSTANCE''', '%', 'hpothuri', TO_DATE('07/16/2008 06:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:52:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan on;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 1.3, 'AND XMAP.APPLICATION_LABEL = ''OKE''', '%', 'hpothuri', TO_DATE('07/16/2008 06:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:52:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 2, 'AND PHDR.K_HEADER_ID = EVNT.K_HEADER_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:53:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 3, 'AND CLNE.ID = EVNT.K_LINE_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:53:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 4, 'AND PLNE.K_LINE_ID = CLNE.ID', '%', 'pvemuru', TO_DATE('07/17/2008 03:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/17/2008 03:53:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 5, 'AND KDLVB.DELIVERABLE_ID = EVNT.DELIVERABLE_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 6, 'AND PEVNT.EVENT_ID(+) = EVNT.PA_EVENT_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 7, 'AND PTYPL.K_TYPE_CODE(+) = PHDR.K_TYPE_CODE', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 8, 'AND PTYPL.LANGUAGE(+) = NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 9, 'AND CLNE1.ID(+) = EVNT.BILL_LINE_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 10, 'AND CREQ.CHG_REQUEST_ID (+) = EVNT.BILL_CHG_REQ_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 11, 'AND ITEM.INVENTORY_ITEM_ID(+) = EVNT.BILL_ITEM_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 12, 'AND (ITEM.INVENTORY_ITEM_ID IS NULL OR ITEM.ORGANIZATION_ID = KDLVB.INVENTORY_ORG_ID)', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 13, 'AND PROJ.PROJECT_ID(+) = EVNT.BILL_PROJECT_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 14, 'AND TASK.TASK_ID(+) = EVNT.BILL_TASK_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 15, 'AND ORGL.ORGANIZATION_ID(+) = EVNT.BILL_ORGANIZATION_ID', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Proj_Contract_Events', 1, 16, 'AND ORGL.LANGUAGE(+) = NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('07/15/2008 03:54:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
@utlspoff