-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_project_contract_roles_where
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 1, 'AND CHDR.ID = PHDR.K_HEADER_ID', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/10/2008 07:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 1.1, 'AND CHDR.AUTHORING_ORG_ID = XMAP.ORG_ID', '%', 'hpothuri', TO_DATE('06/10/2008 07:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/20/2008 06:28:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 1.2, 'AND CHDRL.ID(+) = CHDR.ID', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/10/2008 07:19:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 1.3, 'AND CHDRL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'hpothuri', TO_DATE('06/10/2008 07:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/10/2008 07:17:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 2, 'AND KPRC.CHR_ID (+) = CHDR.ID', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:41:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 2.1, 'AND XMAP.APPLICATION_LABEL     = ''OKE''', '%', 'kkondaveeti', TO_DATE('06/20/2008 06:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/20/2008 06:28:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan off;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 2.2, 'AND XMAP.APPLICATION_INSTANCE  = ''&APPLICATION_INSTANCE''', '%', 'kkondaveeti', TO_DATE('06/20/2008 06:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/20/2008 06:28:00', 'MM/DD/YYYY HH24:MI:SS'));
set scan on;
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 3, 'AND KPDFB.ID = KPRC.PDF_ID', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:42:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 4, 'AND KPDFB.ID = KPDFL.ID', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:42:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 5, 'AND KPDFL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 6, 'AND PPRTY.OBJECT_ID = CHDR.ID', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 7, 'AND PPRTY.OBJECT_TYPE = ''OKE_K_HEADERS''', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:43:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 8, 'AND PPRTY.RESOURCE_TYPE_ID = 101', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:44:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:44:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 9, 'AND PPRTB.PROJECT_ROLE_ID = PPRTY.PROJECT_ROLE_ID', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:44:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:44:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 10, 'AND PPRTB.ROLE_PARTY_CLASS = ''PERSON''', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:45:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 11, 'AND PPRTL.PROJECT_ROLE_ID = PPRTB.PROJECT_ROLE_ID', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:45:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 12, 'AND PPRTL.LANGUAGE (+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:45:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 13, 'AND EMP.PERSON_ID = PPRTY.RESOURCE_SOURCE_ID', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:46:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 14, 'AND PPRTY.CREATION_DATE BETWEEN EMP.EFFECTIVE_START_DATE AND EMP.EFFECTIVE_END_DATE', '%', 'Rvattikonda', TO_DATE('06/09/2008 05:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 05:46:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 15, 'AND PTYP.K_TYPE_CODE = PHDR.K_TYPE_CODE', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 23:05:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 16, 'AND PTYPL.K_TYPE_CODE(+) = PTYP.K_TYPE_CODE', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 23:05:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into N_VIEW_WHERE_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, WHERE_CLAUSE_POSITION, WHERE_CLAUSE, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('OKE_Project_Contract_Roles', 1, 17, 'AND PTYPL.LANGUAGE(+) LIKE NOETIX_ENV_PKG.GET_LANGUAGE', '%', 'Rvattikonda', TO_DATE('06/09/2008 23:06:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/09/2008 23:06:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
@utlspoff