-- 07-Apr-2011 HChodavarapu Verified for 602 build.
@utlspon oke_proj_contract_parties_column
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 1, 'COL', 'Contract number.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/06/2008 04:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Contract_Party_Role_Name', 'PRTYB', 'RLE_CODE', 2, 'LOOK', 'Role of the contract party.', 'NOETIX', 'N_FND_LOOKUPS_VL', 'MEANING', 'OKC_ROLE', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Contract_Party_Name', 'PRTYB', 'SUBSTR(APPS.XXNAO_OKE_WRAPPER_PKG.GET_PARTY_NAME(PRTYB.ID), 1, INSTR(APPS.XXNAO_OKE_WRAPPER_PKG.GET_PARTY_NAME(PRTYB.ID),''~'',1)-1)', 3, 'EXPR', 'Contract party name.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/06/2008 05:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Minority_Group_Name', 'PRTYB', 'MINORITY_GROUP_LOOKUP_CODE', 7, 'COL', 'Minority group name.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'pvemuru', TO_DATE('06/23/2008 06:38:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Government_Code', 'PRTYB', 'CODE', 10, 'COL', 'Government identifying code.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/06/2008 04:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Government_Facility', 'PRTYB', 'FACILITY', 11, 'COL', 'Government facility.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/09/2008 05:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Contract_Party_Known_As', 'PRTYL', 'COGNOMEN', 5, 'COL', 'The name the party is known as.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/18/2008 03:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Contract_Party_Alias', 'PRTYL', 'ALIAS', 6, 'COL', 'Another name for the contract.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:44:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/09/2008 05:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Contract_Party_Description', 'SUBSTR(APPS.XXNAO_OKE_WRAPPER_PKG.GET_PARTY_NAME(PRTYB.ID), INSTR(APPS.XXNAO_OKE_WRAPPER_PKG.GET_PARTY_NAME(PRTYB.ID),''~'',1)+1)', 4, 'EXPR', 'Contract party description.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/06/2008 05:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Small_Business_Flag', 'NVL(PRTYB.SMALL_BUSINESS_FLAG,''N'')', 8, 'EXPR', 'Indicates if the party is a small business or not.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:47:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Women_Owned_Flag', 'NVL(PRTYB.WOMEN_OWNED_FLAG,''N'')', 9, 'EXPR', 'Indicates the party is owned by women or not.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/18/2008 03:30:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 1, 'Line_Number', 'TO_CHAR(NULL)', 12, 'EXPR', 'Contract Line number.', 'N', '%', 'kkondaveeti', TO_DATE('06/18/2008 03:46:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/18/2008 03:47:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Contract_Number', 'CHDR', 'CONTRACT_NUMBER', 1, 'COL', 'Contract number.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/06/2008 04:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Line_Number', 'CLINB', 'LINE_NUMBER', 12, 'COL', 'Contract Line number.', 'N', '%', 'kkondaveeti', TO_DATE('06/18/2008 04:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/18/2008 04:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, REF_APPLICATION_LABEL, REF_TABLE_NAME, REF_DESCRIPTION_COLUMN_NAME, REF_LOOKUP_TYPE, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Contract_Party_Role_Name', 'PRTYB', 'RLE_CODE', 2, 'LOOK', 'Role of the contract party.', 'NOETIX', 'N_FND_LOOKUPS_VL', 'MEANING', 'OKC_ROLE', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:26:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Contract_Party_Name', 'PRTYB', 'SUBSTR(APPS.XXNAO_OKE_WRAPPER_PKG.GET_PARTY_NAME(PRTYB.ID), 1, INSTR(APPS.XXNAO_OKE_WRAPPER_PKG.GET_PARTY_NAME(PRTYB.ID),''~'',1)-1)', 3, 'EXPR', 'Contract party name.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:32:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/06/2008 05:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Minority_Group_Name', 'PRTYB', 'MINORITY_GROUP_LOOKUP_CODE', 7, 'COL', 'Minority group name.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:02:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Government_Code', 'PRTYB', 'CODE', 10, 'COL', 'Government identifying code.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/06/2008 04:11:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Government_Facility', 'PRTYB', 'FACILITY', 11, 'COL', 'Government facility.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:50:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/09/2008 05:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Contract_Party_Known_As', 'PRTYL', 'COGNOMEN', 5, 'COL', 'The name party is known as.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:43:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, TABLE_ALIAS, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Contract_Party_Alias', 'PRTYL', 'ALIAS', 6, 'COL', 'Another name for the contract.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:44:00', 'MM/DD/YYYY HH24:MI:SS'), 'hpothuri', TO_DATE('06/09/2008 05:40:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Contract_Party_Description', 'SUBSTR(APPS.XXNAO_OKE_WRAPPER_PKG.GET_PARTY_NAME(PRTYB.ID), INSTR(APPS.XXNAO_OKE_WRAPPER_PKG.GET_PARTY_NAME(PRTYB.ID),''~'',1)+1)', 4, 'EXPR', 'Contract party description.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'kkondaveeti', TO_DATE('06/06/2008 05:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Small_Business_Flag', 'NVL(PRTYB.SMALL_BUSINESS_FLAG,''N'')', 8, 'EXPR', 'Indicates if the party is a small business or not.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:47:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
Insert into N_VIEW_COLUMN_TEMPLATES
   (VIEW_LABEL, QUERY_POSITION, COLUMN_LABEL, COLUMN_EXPRESSION, COLUMN_POSITION, COLUMN_TYPE, DESCRIPTION, GROUP_BY_FLAG, PRODUCT_VERSION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FORMAT_CLASS, GEN_SEARCH_BY_COL_FLAG)
 Values
   ('OKE_Proj_Contract_Parties', 2, 'Women_Owned_Flag', 'NVL(PRTYB.WOMEN_OWNED_FLAG,''N'')', 9, 'EXPR', 'Indicates the party is women owned or not.', 'N', '%', 'kkondaveeti', TO_DATE('06/06/2008 03:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'jbhattacharya', TO_DATE('06/10/2008 07:01:00', 'MM/DD/YYYY HH24:MI:SS'), 'STRING', 'N');
COMMIT;
@utlspoff