-- 07-Apr-2011 HChodavarapu Verified for 602 build.
-- 17-Oct-2014 N Mohan added metadata to work with 6.3 changes.
--
@utlspon project_contracts_role

Insert into N_ROLE_TEMPLATES
   (ROLE_LABEL, APPLICATION_LABEL, DESCRIPTION, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, META_DATA_TYPE, ORIGINAL_VERSION, CURRENT_VERSION)
 Values
   ('PROJECT_CONTRACTS', 'OKE', 'Project Contracts', 'Rvattikonda', TO_DATE('06/04/2008 00:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'Rvattikonda', TO_DATE('06/04/2008 00:48:00', 'MM/DD/YYYY HH24:MI:SS'), 'Views', '5.7.1.383', '5.7.2.380');

-- Project cont
Insert into N_PL_FOLDER_TEMPLATES
   (T_FOLDER_ID,   APPLICATION_LABEL, ROLE_LABEL, FOLDER_NAME, FOLDER_DESCRIPTION, PARENT_T_FOLDER_ID, 
    SORT_ORDER, SEARCH_FOLDER_NAME, INSTANCE_TYPE_CODE, KFF_ID_FLEX_CODE, KFF_ID_FLEX_APPLICATION_ID, 
    HIERARCHY_NAME, FOLDER_USAGE_CODE, FOLDER_TYPE_CODE, ORG_TYPE_CODE, DIM_TYPE_CODE, 
    DISPLAY_VIEWS_IN_PARENT_FLAG, ROLE_REQUIRED_IN_PARENT_CODE, PRODUCT_VERSION, INCLUDE_FLAG, USER_INCLUDE_FLAG, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, VERSION_ID)
 Values
   (  N_PL_FOLDER_TEMPLATES_SEQ.nextval, 'OKE', 'PROJECT_CONTRACTS', 'Project Contracts Views', 'Project Contracts Views', 147, 1, 'Project Contracts', 'G', NULL, 
    NULL, NULL, 'VIEWS', 'ROLE', NULL,     NULL, 'N', 'Y', '*', 'Y', NULL, 'Noetix', sysdate, 'Noetix', sysdate,    NULL);


Insert into N_PL_FOLDER_TEMPLATES
   (T_FOLDER_ID,   APPLICATION_LABEL, ROLE_LABEL, FOLDER_NAME, FOLDER_DESCRIPTION, PARENT_T_FOLDER_ID, 
    SORT_ORDER, SEARCH_FOLDER_NAME, INSTANCE_TYPE_CODE, KFF_ID_FLEX_CODE, KFF_ID_FLEX_APPLICATION_ID, 
    HIERARCHY_NAME, FOLDER_USAGE_CODE, FOLDER_TYPE_CODE, ORG_TYPE_CODE, DIM_TYPE_CODE, 
    DISPLAY_VIEWS_IN_PARENT_FLAG, ROLE_REQUIRED_IN_PARENT_CODE, PRODUCT_VERSION, INCLUDE_FLAG, USER_INCLUDE_FLAG, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, VERSION_ID)
 Values
   (  N_PL_FOLDER_TEMPLATES_SEQ.nextval, 'OKE', 'PROJECT_CONTRACTS', 'Project Contracts Answers', 'Project Contracts Answers', 147, 1, 'Internet Expenses', 'G', NULL, 
    NULL, NULL, 'ANS', 'ROLE', NULL,     NULL, 'N', 'N', '*', 'Y', NULL, 'Noetix', sysdate, 'Noetix', sysdate,    NULL);


COMMIT;

@utlspoff