@utlspon SI_TYPE_VIEWS_POC

SET DEFINE OFF;
WHENEVER SQLERROR EXIT 920;

Insert into NOETIX_VIEWS.N_JOIN_KEY_TEMPLATES
   (T_JOIN_KEY_ID, VIEW_LABEL, KEY_NAME, DESCRIPTION, KEY_TYPE_CODE, COLUMN_TYPE_CODE, KEY_RANK, KEY_CARDINALITY_CODE, PRODUCT_VERSION, INCLUDE_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (2685, 'HR_Emp_Asg_Details', 'PK1', 'HR_Emp_Asg_Details view Primary Key for column label based join relationships.', 
    'PK', 'COL', 1, 
    'N', '*', 'Y', 'NOETIX', TO_DATE('09/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'dpagadala', TO_DATE('09/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into NOETIX_VIEWS.N_JOIN_KEY_TEMPLATES
   (T_JOIN_KEY_ID, VIEW_LABEL, KEY_NAME, DESCRIPTION, KEY_TYPE_CODE, COLUMN_TYPE_CODE, OUTERJOIN_FLAG, KEY_RANK, KEY_CARDINALITY_CODE, REFERENCED_PK_T_JOIN_KEY_ID, PRODUCT_VERSION, INCLUDE_FLAG, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (2686, 'HR_SI_Type', 'FK', 'HR_SI_Type view Foreign Key for column label based join relationships.', 
    'FK', 'COL', 'Y', 1, 
    'N', 2685, '*', 
    'Y', 'NOETIX', TO_DATE('09/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'dpagadala', TO_DATE('09/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;

Insert into NOETIX_VIEWS.N_JOIN_KEY_COL_TEMPLATES
   (T_JOIN_KEY_COLUMN_ID, T_JOIN_KEY_ID, T_COLUMN_POSITION, COLUMN_LABEL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (2607, 2685, 1, 'Employee_Number', 
    'NOETIX', TO_DATE('09/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'dpagadala', TO_DATE('09/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into NOETIX_VIEWS.N_JOIN_KEY_COL_TEMPLATES
   (T_JOIN_KEY_COLUMN_ID, T_JOIN_KEY_ID, T_COLUMN_POSITION, COLUMN_LABEL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (2608, 2686, 1, 'Employee_Number', 
    'NOETIX', TO_DATE('09/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'dpagadala', TO_DATE('09/29/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;

COMMIT;
SET DEFINE ON;
WHENEVER SQLERROR CONTINUE;

@utlspoff